# Generated by Django 2.0.2 on 2018-06-14 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('determinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='determination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='determination',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Update time'),
            preserve_default=False,
        ),
    ]
