# Generated by Django 2.0.2 on 2018-06-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('determinations', '0002_add_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='determination',
            name='determination_message',
            field=models.TextField(blank=True, verbose_name='Determination message'),
        ),
    ]
