# Generated by Django 2.0.2 on 2018-06-18 23:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('determinations', '0003_determination_determination_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='determination',
            name='determination',
            field=models.IntegerField(choices=[(0, 'Rejected'), (1, 'Needs more info'), (2, 'Accepted')], default=1, verbose_name='Determination'),
        ),
        migrations.AlterField(
            model_name='determination',
            name='determination_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
