# Generated by Django 2.0.2 on 2018-06-19 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('determinations', '0004_determination_tweaks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='determination',
            old_name='determination_data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='determination',
            old_name='determination_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='determination',
            old_name='determination',
            new_name='outcome',
        ),
        migrations.AlterUniqueTogether(
            name='determination',
            unique_together=set(),
        ),
    ]
