# Generated by Django 2.0.2 on 2018-09-05 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('determinations', '0005_determination_drupal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='determination',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='determinations', to='funds.ApplicationSubmission'),
        ),
    ]
