# Generated by Django 2.0.9 on 2018-12-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('determinations', '0006_allow_multiple_determinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='determination',
            name='outcome',
            field=models.IntegerField(choices=[(0, 'Dismissed'), (1, 'Needs more info'), (2, 'Approved'), (3, 'Invited to proposal')], default=1, verbose_name='Determination'),
        ),
    ]
