# Generated by Django 3.2.17 on 2023-02-14 06:58

from django.db import migrations
import wagtail.images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_customimage_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='file',
            field=wagtail.images.models.WagtailImageField(height_field='height', upload_to=wagtail.images.models.get_upload_to, verbose_name='file', width_field='width'),
        ),
        migrations.AlterField(
            model_name='rendition',
            name='file',
            field=wagtail.images.models.WagtailImageField(height_field='height', upload_to=wagtail.images.models.get_rendition_upload_to, width_field='width'),
        ),
    ]
