# Generated by Django 4.2.17 on 2025-01-14 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0006_alter_rendition_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customimage",
            name="drupal_id",
        ),
    ]
