# Generated by Django 4.2.27 on 2026-01-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0007_remove_drupal_id_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="description"
            ),
        ),
    ]
