# Generated by Django 5.2.11 on 2026-03-03 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0008_customimage_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customimage",
            options={
                "verbose_name": "custom image",
                "verbose_name_plural": "custom images",
            },
        ),
        migrations.AlterModelOptions(
            name="rendition",
            options={"verbose_name": "rendition", "verbose_name_plural": "renditions"},
        ),
    ]
