# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectfunding'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='status',
            field=models.CharField(choices=[('idea', 'Just an Idea (Pre-alpha)'), ('exists', 'It Exists! (Alpha/Beta)'), ('release', "It's basically done. (Release)"), ('production', 'People Use It. (Production)')], default='idea', max_length=25),
        ),
    ]
