# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectpage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='categories',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
    ]
