# Generated by Django 2.0.2 on 2018-08-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectpage_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='introduction',
        ),
    ]
