# Generated by Django 2.2.14 on 2020-08-17 12:05

from django.db import migrations
import hypha.reset_network.reset_network_person.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('reset_network_people', '0002_auto_20200303_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetnetworkpeoplepage',
            name='section_1',
            field=wagtail.core.fields.StreamField([('sub_heading', wagtail.core.blocks.CharBlock(icon='tag')), ('sub_text', wagtail.core.blocks.TextBlock()), ('persons', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('person', wagtail.snippets.blocks.SnippetChooserBlock(hypha.reset_network.reset_network_person.models.ResetNetworkPerson))], icon='user'), icon='group'))], blank=True, verbose_name='Content - Section 1 (People)'),
        ),
    ]
