# Generated by Django 2.2.24 on 2021-11-22 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_add_news_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAPIKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='home.HomePage')),
            ],
            options={
                'verbose_name': 'Public HomePage API key',
                'verbose_name_plural': 'Public HomePage API keys',
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
