# Generated by Django 4.2.9 on 2024-01-07 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_alter_homepage_our_work"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="social_image",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="social_text",
        ),
    ]
