# Generated by Django 3.2.16 on 2023-01-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_homepage_our_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='news_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='news_link_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='news_title',
        ),
    ]
