# Generated by Django 4.2.9 on 2024-01-29 07:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_alter_promotedlabs_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HomePage",
        ),
    ]
