# Generated by Django 3.2.21 on 2023-10-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="user_group",
            field=models.ManyToManyField(
                blank=True, related_name="task", to="auth.Group"
            ),
        ),
    ]
