# Generated by Django 2.2.9 on 2020-02-04 11:42

from django.db import migrations, models
import django.db.models.deletion
import opentech.reset_network.reset_network_person.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetNetworkPeoplePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content_heading', models.CharField(max_length=255, verbose_name='Heading')),
                ('content_text', models.TextField(blank=True, verbose_name='Text')),
                ('section_1', wagtail.core.fields.StreamField([('sub_heading', wagtail.core.blocks.CharBlock(icon='tag')), ('persons', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('person', wagtail.snippets.blocks.SnippetChooserBlock(opentech.reset_network.reset_network_person.models.ResetNetworkPerson))], icon='user'), icon='group'))], blank=True, verbose_name='Content - Section 1 (People)')),
            ],
            options={
                'verbose_name': 'Reset Network People Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
