# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newspageauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspageauthor',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.Page'),
            preserve_default=False,
        ),
    ]
