# Generated by Django 2.0.9 on 2018-11-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newspage_drupal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsindex',
            name='introduction',
            field=models.TextField(blank=True),
        ),
    ]
