# Generated by Django 2.0.9 on 2019-02-07 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newsindex_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspagerelatedpage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='newsprojectrelatedpage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_mentions', to='wagtailcore.Page'),
        ),
    ]
