repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/rtts/djhtml
    rev: "3.0.7"
    hooks:
      - id: djhtml
        files: .*/templates/.*\.html$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.12.0
    hooks:
      - id: eslint
        files: .*/static_src/javascript/.*\.js$
        additional_dependencies:
          - eslint@9.12.0
          - globals@15.11.0
          - eslint-config-prettier@8.10.0
          - eslint-plugin-template@0.7.0
          - eslint-plugin-jsdoc@50.3.1
          - "@eslint/js@9.12.0"
          - "@eslint/eslintrc@3.1.0"

  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: "0.0.2"
    hooks:
      - id: stylelint
        files: .*/static_src/sass/.*\.scss$
        additional_dependencies:
          - stylelint@16.10.0
          - stylelint-config-standard@36.0.1
          - stylelint-config-standard-scss@13.1.0

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
