repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: "0.6.4"
    hooks:
      - id: uv-export
        name: uv-export requirements/prod.txt
        args:
          [
            "--frozen",
            "--no-group",
            "dev",
            "--no-group",
            "docs",
            "-o",
            "requirements/prod.txt",
          ]

      - id: uv-export
        name: uv-export requirements/dev.txt
        args: ["--frozen", "--group", "dev", "-o", "requirements/dev.txt"]

      - id: uv-export
        name: uv-export requirements/docs.txt
        args:
          ["--frozen", "--only-group", "docs", "-o", "requirements/docs.txt"]

      - id: uv-export
        name: uv-export requirements/translate.txt
        args:
          [
            "--frozen",
            "--only-group",
            "translate",
            "-o",
            "requirements/translate.txt",
          ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.10"
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/rtts/djhtml
    rev: "3.0.7"
    hooks:
      - id: djhtml
        files: .*/templates/.*\.html$

  - repo: local
    hooks:
      - id: rustywind
        name: rustywind Tailwind CSS class linter
        language: node
        additional_dependencies:
          - rustywind@latest
        entry: rustywind
        args: [--write]
        types_or: [html]

  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.6.1"
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.9.4"]

  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: "0.0.2"
    hooks:
      - id: stylelint
        files: .*/static_src/sass/.*\.scss$
        additional_dependencies:
          - stylelint@16.11.0
          - stylelint-config-standard-scss@13.1.0
