site_name: Hypha Documentation
site_url: https://docs.hypha.app/
site_description: "Documentation for Hypha, an open source submission management platform."
copyright: Copyright &copy; 2018 - 2023 - Open Technology Fund
repo_name: HyphaApp/hypha
repo_url: https://github.com/HyphaApp/hypha
edit_uri: edit/main/docs/

dev_addr: localhost:9100
site_dir: docs_build
extra_css:
  - assets/extra.css

theme:
  name: material
  favicon: https://www.hypha.app/favicon-32x32.png
  logo: data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPHN2ZyB2aWV3Qm94PSIwIDAgNTAwIDUwMCIgd2lkdGg9IjUwMCIgaGVpZ2h0PSI1MDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgPGcgZmlsbD0iI2ZmZiIgdHJhbnNmb3JtPSJtYXRyaXgoMSwgMCwgMCwgMSwgLTAuMTg4NzI4LCAwLjY4NjI4OCkiPgogICAgPHBhdGggc3Ryb2tlPSIjZmZmIiBzdHJva2Utd2lkdGg9IjAiIGQ9Ik0uNiAxNDAuMmMuMiA3Ny41LjYgMTQzIDEgMTQ1LjYuMyAyLjYgMS4xIDcuMiAxLjcgMTAuM2wxLjYgOS44Yy4zIDIuMyAxLjggOC40IDMgMTMuNmEyNDEuNiAyNDEuNiAwIDAgMCAxNDkuNCAxNjQuOWMxMCAzLjcgMTAgMy43IDEwLjIgMS4zYTM1Ni42IDM1Ni42IDAgMCAxIDk5LjMtMjE1LjRBMzU1IDM1NSAwIDAgMSA0MjkuNCAxNzRsMTIuNC0zIDE0LTMuMWExNDg2LjYgMTQ4Ni42IDAgMCAxIDMyLTVjLjktMS0xMi40LTMxLTE5LTQyLjZhMjQxLjkgMjQxLjkgMCAwIDAtMTQ4LTExMy40Yy0xLjMtLjItNC4xLTEtNi40LTEuNS0yLjMtLjYtNS44LTEuNC03LjgtMS43bC02LjEtMWMtMS41LS4yLTQuNS0uOC02LjgtMS0yLjItLjUtNS40LTEtNy4yLTEuMi0xLjYtLjMtNjYuNy0uNy0xNDQuNy0uOEwuMy0uN3ptMjgyLjMtNDMuOGExNTggMTU4IDAgMCAxIDUyLjIgMTkuMmMxIDAgMTcgMTEuNyAxNyAxMi40IDAgLjUtMSAxLjItMi4zIDEuNWE0OTUuNiA0OTUuNiAwIDAgMC00OC4zIDIzLjQgNDk0LjkgNDk0LjkgMCAwIDAtNDEuMyAyNy4xIDMzNy44IDMzNy44IDAgMCAwLTQwLjggMzYgNzY2LjcgNzY2LjcgMCAwIDAtMTcuNSAxOC4ybC04LjggMTAuOWE0MDQuOCA0MDQuOCAwIDAgMC01NC43IDg5LjhjMCAuMy0xIDMuMS0yLjUgNi4yYTQzLjUgNDMuNSAwIDAgMC0zLjYgOS4yYy0xLjQgMy42LTIuNCAyLjgtOS43LTcuNi0xMi42LTE4LTIxLjEtMzguNy0yNS4yLTYxLjUtLjMtMS44LS43LTQ0LjQtMS05NC44TDk2IDk0LjhsOTEuNy40YzUwLjMuMiA5My4yLjcgOTUuMiAxLjJ6Ii8+CiAgICA8cGF0aCBkPSJNNDg4LjggMjM1YTMzNiAzMzYgMCAwIDAtNzguNSAyMC42Yy0yMC40IDguNS01MSAyNS45LTYwLjYgMzQuMy0xIC45IDQ5IDUxLjYgNTAuNiA1MS42YTMzIDMzIDAgMCAwIDYtMy40IDIxNi42IDIxNi42IDAgMCAxIDcxLTMwLjFsNy4zLTEuNWEzMzYuNiAzMzYuNiAwIDAgMSAxNC45LTIuNmMuNC0uMi42LTE1LjguNi0zNC44di0zNC40SDQ5NmMtMi4zIDAtNS41LjEtNy4yLjN6TTI4OSAzNTMuMWEzMDEuMiAzMDEuMiAwIDAgMC01MCAxMzkuMmwtLjcgNi43aDcwLjJsLjYtNi4yYzIuOC0yNS4zIDE1LTYwLjUgMjktODMuNyAyLjctNC41IDUuMi04LjUgNS4zLTkgLjQtLjYtNDkuOS01MS4zLTUwLjgtNTEuMy0uMiAwLTEuOCAyLTMuNiA0LjN6bTIwMS44IDIzLjJjLTU0LjMgMTIuNi05Mi4xIDQ4LjEtMTA3LjMgMTAxLTIuNiA5LTMuMiAxMS43LTQgMTguNmwtLjQgMy4xaDYwLjVsNjAuNS0uMXYtNjEuOGMwLTU0LjItLjItNjEuOC0xLjUtNjItLjgtLjEtNC40LjQtNy44IDEuMnoiLz4KICA8L2c+Cjwvc3ZnPg==
  icon:
    repo: fontawesome/brands/github
  #   palette:
  #     primary: black
  #     accent: deep purple
  font: false
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.follow

plugins:
  - awesome-pages
  - search
  - git-revision-date-localized:
      type: timeago

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      guess_lang: false
      linenums: false
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys

nav:
  - Home: index.md
  - ...
  - Issues: https://github.com/HyphaApp/hypha/issues

extra:
  social:
    - icon: material/chat
      link: https://chat.hypha.app/
      name: Hypha Chat

    - icon: material/forum
      link: https://we.hypha.app/
      name: Hypha Forum

    - icon: material/github
      link: https://github.com/HyphaApp/
      name: GitHub Org
