# Generated by Django 2.0.2 on 2018-08-29 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_fundreviewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wagtailcore.Page'),
        ),
    ]
