# Generated by Django 2.0.2 on 2018-08-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_personpage_drupal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpage',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
