# Generated by Django 2.0.2 on 2018-08-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_personpage_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcontactinfomation',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('irc', 'IRC'), ('im', 'IM/Jabber/XMPP'), ('phone', 'Phone'), ('pgp', 'PGP fingerprint'), ('otr', 'OTR fingerprint')], max_length=255),
        ),
    ]
