# Generated by Django 4.2.9 on 2024-01-07 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0015_alter_personpage_biography"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personindexpage",
            name="social_image",
        ),
        migrations.RemoveField(
            model_name="personindexpage",
            name="social_text",
        ),
        migrations.RemoveField(
            model_name="personpage",
            name="social_image",
        ),
        migrations.RemoveField(
            model_name="personpage",
            name="social_text",
        ),
    ]
