# Generated by Django 3.2.16 on 2022-11-10 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0005_alter_calltoactionsnippet_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="systemmessagessettings",
            options={"verbose_name": "System settings"},
        ),
    ]
