# Generated by Django 3.2.19 on 2023-06-08 08:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0006_alter_systemmessagessettings_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemmessagessettings",
            name="site",
        ),
    ]
