# Generated by Django 3.2.16 on 2023-01-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_alter_systemmessagessettings_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemmessagessettings',
            name='footer_content',
        ),
    ]
