# Generated by Django 3.2.20 on 2023-10-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0007_remove_systemmessagessettings_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemmessagessettings",
            name="nav_content",
            field=models.TextField(
                blank=True,
                help_text="This will overwrite the default front page navigation bar, html tags is allowed.",
                verbose_name="Front page navigation content",
            ),
        ),
    ]
