# Generated by Django 4.2.7 on 2023-11-28 13:51

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0008_systemmessagessettings_nav_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemmessagessettings",
            name="body_403",
            field=wagtail.fields.RichTextField(
                default="<p>You might not have access to the requested resource.</p>",
                verbose_name="Text",
            ),
        ),
        migrations.AddField(
            model_name="systemmessagessettings",
            name="title_403",
            field=models.CharField(
                default="Permission Denied", max_length=255, verbose_name="Title"
            ),
        ),
    ]
