# Generated by Django 4.2.9 on 2024-01-07 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0009_systemmessagessettings_body_403_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SocialMediaSettings",
        ),
    ]
