# Generated by Django 4.2.9 on 2024-01-11 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0010_delete_socialmediasettings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CallToActionSnippet",
        ),
    ]
