# Generated by Django 4.2.9 on 2024-01-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0011_delete_calltoactionsnippet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemmessagessettings",
            name="footer_content",
            field=models.TextField(
                blank=True,
                default="<p>Configure this text in Wagtail admin -> Settings -> System settings.</p>",
                help_text="This will be added to the footer, html tags is allowed.",
                verbose_name="Footer content",
            ),
        ),
    ]
