# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 16:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0005_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='round',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
