# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 11:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0006_add_dates_to_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='If no end date is provided the round will remain open.', null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
