# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0012_add_fullname_email_block_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundtype',
            name='confirmation_text_extra',
            field=models.TextField(blank=True, help_text='Additional text for the application confirmation message.'),
        ),
        migrations.AddField(
            model_name='fundtype',
            name='from_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='from address'),
        ),
        migrations.AddField(
            model_name='fundtype',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='fundtype',
            name='to_address',
            field=models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, verbose_name='to address'),
        ),
    ]
