# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 16:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0014_applicationsubmission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsubmission',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
