# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0018_add_addressfield'),
        ('funds', '0016_protect_submissions_from_deletion'),
    ]

    operations = [
    ]
