# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0020_add_workflow_and_status_to_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationsubmission',
            old_name='workflow',
            new_name='workflow_name',
        ),
        migrations.RenameField(
            model_name='fundtype',
            old_name='workflow',
            new_name='workflow_name',
        ),
        migrations.RenameField(
            model_name='labtype',
            old_name='workflow',
            new_name='workflow_name',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='workflow',
            new_name='workflow_name',
        ),
        migrations.AlterField(
            model_name='applicationsubmission',
            name='workflow_name',
            field=models.CharField(choices=[('single', 'Single Stage'), ('double', 'Two Stage')], default='single', max_length=100, verbose_name='Workflow'),
        ),
        migrations.AlterField(
            model_name='fundtype',
            name='workflow_name',
            field=models.CharField(choices=[('single', 'Single Stage'), ('double', 'Two Stage')], default='single', max_length=100, verbose_name='Workflow'),
        ),
        migrations.AlterField(
            model_name='labtype',
            name='workflow_name',
            field=models.CharField(choices=[('single', 'Single Stage'), ('double', 'Two Stage')], default='single', max_length=100, verbose_name='Workflow'),
        ),
        migrations.AlterField(
            model_name='round',
            name='workflow_name',
            field=models.CharField(choices=[('single', 'Single Stage'), ('double', 'Two Stage')], default='single', max_length=100, verbose_name='Workflow'),
        ),
    ]
