# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0021_rename_workflow_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsubmission',
            name='status_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
