# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0021_rename_workflow_field'),
        ('funds', '0020_applicationsubmission_form_fields'),
    ]

    operations = [
    ]
