# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-16 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0023_round_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsubmission',
            name='search_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
