# Generated by Django 2.0.2 on 2018-03-01 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0025_update_with_file_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundform',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funds.ApplicationForm'),
        ),
        migrations.AlterField(
            model_name='labform',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funds.ApplicationForm'),
        ),
        migrations.AlterField(
            model_name='round',
            name='lead',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Staff'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roundform',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funds.ApplicationForm'),
        ),
    ]
