# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-08 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0026_add_leads_to_submission_and_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsubmission',
            name='drupal_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
