# Generated by Django 2.0.2 on 2018-03-14 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0028_update_on_delete_django2'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsubmission',
            name='next',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='funds.ApplicationSubmission'),
        ),
    ]
