# Generated by Django 2.0.2 on 2018-03-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0032_make_reviewers_optional_in_all_instances'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsubmission',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update time'),
        ),
    ]
