# Generated by Django 2.0.2 on 2018-06-21 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funds', '0034_create_revisions_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationrevision',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationrevision',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
