# Generated by Django 2.0.2 on 2018-08-01 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import opentech.apply.stream_forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0006_remove_review_review'),
        ('funds', '0036_fundreviewform_labreviewform'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForPartners',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, verbose_name='to address')),
                ('from_address', models.CharField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('workflow_name', models.CharField(choices=[('single', 'Request'), ('double', 'Concept & Proposal')], default='single', max_length=100, verbose_name='Workflow')),
                ('confirmation_text_extra', models.TextField(blank=True, help_text='Additional text for the application confirmation message.')),
                ('reviewers', modelcluster.fields.ParentalManyToManyField(blank=True, limit_choices_to={'groups__name': 'Reviewer'}, related_name='requestforpartners_reviewers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RFP',
            },
            bases=(opentech.apply.stream_forms.models.BaseStreamForm, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='RFPForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funds.ApplicationForm')),
                ('rfp', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='funds.RequestForPartners')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFPReviewForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='review.ReviewForm')),
                ('rfp', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_forms', to='funds.RequestForPartners')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='fundtype',
            name='reviewers',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, limit_choices_to={'groups__name': 'Reviewer'}, related_name='fundtype_reviewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
