# Generated by Django 2.0.2 on 2018-08-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0037_add_rfp_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='sealed',
            field=models.BooleanField(default=False),
        ),
    ]
