# Generated by Django 2.0.2 on 2018-08-02 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0038_recreate_objects_that_exist'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForPartners',
            fields=[
                ('applicationbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='funds.ApplicationBase')),
            ],
            options={
                'verbose_name': 'RFP',
            },
            bases=('funds.applicationbase',),
        ),
        migrations.CreateModel(
            name='SealedRound',
            fields=[
                ('roundbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='funds.RoundBase')),
            ],
            options={
                'abstract': False,
            },
            bases=('funds.roundbase',),
        ),
        migrations.AddField(
            model_name='roundbase',
            name='sealed',
            field=models.BooleanField(default=False),
        ),
    ]
