# Generated by Django 2.0.9 on 2018-12-19 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funds', '0047_add_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsubmission',
            name='partners',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Partner'}, related_name='submissions_partner', to=settings.AUTH_USER_MODEL),
        ),
    ]
