# Generated by Django 2.0.9 on 2019-01-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('funds', '0049_screening_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundsAndLabs',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('wagtailcore.page',),
        ),
    ]
