# Generated by Django 2.0.10 on 2019-02-06 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0003_customimage_drupal_id'),
        ('funds', '0050_roundsandlabs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSubmissionReviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('order', models.IntegerField(blank=True, help_text='The order this role should appear in the Update Reviewers form.', null=True)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage')),
            ],
        ),
        migrations.AddField(
            model_name='applicationsubmissionreviewer',
            name='reviewer_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='funds.ReviewerRole', verbose_name='screening status'),
        ),
        migrations.AddField(
            model_name='applicationsubmissionreviewer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_reviewers', to='funds.ApplicationSubmission'),
        ),
    ]
