# Generated by Django 2.0.10 on 2019-02-04 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funds', '0050_roundsandlabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsubmission',
            name='partners',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Partner'}, related_name='submissions_partner', to=settings.AUTH_USER_MODEL),
        ),
    ]
