# Generated by Django 2.0.10 on 2019-02-05 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funds', '0051_reviewerrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSubmissionReviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_reviewer', to=settings.AUTH_USER_MODEL)),
                ('reviewer_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='funds.ReviewerRole', verbose_name='screening status')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_reviewers', to='funds.ApplicationSubmission')),
            ],
        ),
    ]
