# Generated by Django 4.2.11 on 2024-05-16 11:49

from django.db import migrations, models
from hypha.apply.users.models import User


def add_newsletter_signup_field(apps, schema_editor):
    field = models.BooleanField(default=True)
    field.column = "newsletter_signup"
    schema_editor.add_field(
        User,
        field,
    )


def remove_newsletter_signup_field(apps, schema_editor):
    field = models.BooleanField(default=True)
    field.column = "newsletter_signup"
    schema_editor.remove_field(
        User,
        field,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_merge_0021_groupdesc_0022_confirmaccesstoken"),
    ]

    operations = [
        migrations.RunPython(
            add_newsletter_signup_field, remove_newsletter_signup_field
        )
    ]
