# Generated by Django 4.2.9 on 2024-01-07 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("standardpages", "0006_alter_informationpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indexpage",
            name="social_image",
        ),
        migrations.RemoveField(
            model_name="indexpage",
            name="social_text",
        ),
        migrations.RemoveField(
            model_name="informationpage",
            name="social_image",
        ),
        migrations.RemoveField(
            model_name="informationpage",
            name="social_text",
        ),
    ]
