# Generated by Django 4.2.9 on 2024-01-11 11:37

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("standardpages", "0007_remove_indexpage_social_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indexpage",
            name="listing_image",
        ),
        migrations.RemoveField(
            model_name="indexpage",
            name="listing_summary",
        ),
        migrations.RemoveField(
            model_name="indexpage",
            name="listing_title",
        ),
        migrations.RemoveField(
            model_name="informationpage",
            name="listing_image",
        ),
        migrations.RemoveField(
            model_name="informationpage",
            name="listing_summary",
        ),
        migrations.RemoveField(
            model_name="informationpage",
            name="listing_title",
        ),
        migrations.AlterField(
            model_name="informationpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.CharBlock(
                            form_classname="full title", icon="title"
                        ),
                    ),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    (
                        "box",
                        wagtail.blocks.StructBlock(
                            [
                                ("box_content", wagtail.blocks.RichTextBlock()),
                                ("box_class", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        "more",
                        wagtail.blocks.StructBlock(
                            [
                                ("more_content", wagtail.blocks.RichTextBlock()),
                                ("more_content_more", wagtail.blocks.RichTextBlock()),
                                (
                                    "more_class",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                            ]
                        ),
                    ),
                    (
                        "apply_link",
                        wagtail.blocks.StructBlock(
                            [("application", wagtail.blocks.PageChooserBlock())]
                        ),
                    ),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        "quote",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "quote",
                                    wagtail.blocks.CharBlock(form_classname="title"),
                                ),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                ("job_title", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    ),
                    ("embed", wagtail.embeds.blocks.EmbedBlock()),
                    (
                        "document",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "document",
                                    wagtail.documents.blocks.DocumentChooserBlock(),
                                ),
                                ("title", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
