# Generated by Django 4.2.9 on 2024-01-11 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("standardpages", "0008_remove_indexpage_listing_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="informationpage",
            name="header_image",
        ),
        migrations.RemoveField(
            model_name="informationpage",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="informationpagerelatedpage",
            name="page",
        ),
        migrations.RemoveField(
            model_name="informationpagerelatedpage",
            name="source_page",
        ),
        migrations.DeleteModel(
            name="IndexPage",
        ),
        migrations.DeleteModel(
            name="InformationPage",
        ),
        migrations.DeleteModel(
            name="InformationPageRelatedPage",
        ),
    ]
