# Generated by Django 4.2.11 on 2024-03-26 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel("Flag", "Bookmark"),
        migrations.RunSQL("INSERT INTO bookmarks_bookmark (SELECT * FROM flags_flag);"),
        migrations.RunSQL("DROP TABLE flags_flag;"),
    ]
