# Generated by Django 5.2.13 on 2026-04-13 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apply_home", "0002_add_apply_homepage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applyhomepage",
            options={
                "verbose_name": "Apply home page",
                "verbose_name_plural": "Apply home page",
            },
        ),
    ]
