# Generated by Django 2.0.9 on 2019-02-24 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0021_add_review_delete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='activity',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='edited',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='previous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.Activity'),
        ),
    ]
