# Generated by Django 2.0.13 on 2019-07-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0029_migrate_old_submission_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='submission',
        ),
    ]
