# Generated by Django 2.0.13 on 2019-08-13 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0028_migrate_messages_with_visibility'),
        ('activity', '0039_add_remove_document'),
    ]

    operations = [
    ]
