# Generated by Django 2.0.2 on 2018-06-22 14:23

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('determinations', '0003_message_template_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='determination',
            name='outcome',
            field=models.IntegerField(choices=[(0, 'Dismissed'), (1, 'Needs more info'), (2, 'Approved')], default=1, verbose_name='Determination'),
        ),
        migrations.AlterField(
            model_name='determinationmessagesettings',
            name='concept_accepted',
            field=wagtail.core.fields.RichTextField(verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='determinationmessagesettings',
            name='concept_rejected',
            field=wagtail.core.fields.RichTextField(verbose_name='Dismissed'),
        ),
        migrations.AlterField(
            model_name='determinationmessagesettings',
            name='proposal_accepted',
            field=wagtail.core.fields.RichTextField(verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='determinationmessagesettings',
            name='proposal_rejected',
            field=wagtail.core.fields.RichTextField(verbose_name='Dismissed'),
        ),
        migrations.AlterField(
            model_name='determinationmessagesettings',
            name='request_accepted',
            field=wagtail.core.fields.RichTextField(verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='determinationmessagesettings',
            name='request_rejected',
            field=wagtail.core.fields.RichTextField(verbose_name='Dismissed'),
        ),
    ]
