# Generated by Django 2.0.13 on 2019-09-12 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('determinations', '0006_allow_multiple_determinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeterminationFormSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_principles_label', models.CharField(default='Goals and principles', max_length=255, verbose_name='label')),
                ('concept_principles_help_text', models.TextField(blank=True, verbose_name='help text')),
                ('concept_technical_label', models.CharField(default='Technical merit', max_length=255, verbose_name='label')),
                ('concept_technical_help_text', models.TextField(blank=True, verbose_name='help text')),
                ('concept_sustainable_label', models.CharField(default='Reasonable, realistic and sustainable', max_length=255, verbose_name='label')),
                ('concept_sustainable_help_text', models.TextField(blank=True, verbose_name='help text')),
                ('proposal_liked_label', models.CharField(default='Positive aspects', max_length=255, verbose_name='label')),
                ('proposal_liked_help_text', models.TextField(blank=True, verbose_name='help text')),
                ('proposal_concerns_label', models.CharField(default='Concerns', max_length=255, verbose_name='label')),
                ('proposal_concerns_help_text', models.TextField(blank=True, verbose_name='help text')),
                ('proposal_red_flags_label', models.CharField(default='Items that must be addressed', max_length=255, verbose_name='label')),
                ('proposal_red_flags_help_text', models.TextField(blank=True, verbose_name='help text')),
                ('proposal_overview_label', models.CharField(default='Project overview questions and comments', max_length=255, verbose_name='label')),
                ('proposal_overview_help_text', models.TextField(blank=True, verbose_name='help text')),
                ('proposal_objectives_label', models.CharField(default='Objectives questions and comments', max_length=255, verbose_name='label')),
                ('proposal_objectives_help_text', models.TextField(blank=True, verbose_name='help text')),
                ('proposal_strategy_label', models.CharField(default='Methods and strategy questions and comments', max_length=255, verbose_name='label')),
                ('proposal_strategy_help_text', models.TextField(blank=True, verbose_name='help text')),
                ('proposal_technical_label', models.CharField(default='Technical feasibility questions and comments', max_length=255, verbose_name='label')),
                ('proposal_technical_help_text', models.TextField(blank=True, verbose_name='help text')),
                ('proposal_alternative_label', models.CharField(default='Alternative analysis - "red teaming" questions and comments', max_length=255, verbose_name='label')),
                ('proposal_alternative_help_text', models.TextField(blank=True, verbose_name='help text')),
                ('proposal_usability_label', models.CharField(default='Usability questions and comments', max_length=255, verbose_name='label')),
                ('proposal_usability_help_text', models.TextField(blank=True, verbose_name='help text')),
                ('proposal_sustainability_label', models.CharField(default='Sustainability questions and comments', max_length=255, verbose_name='label')),
                ('proposal_sustainability_help_text', models.TextField(blank=True, verbose_name='help text')),
                ('proposal_collaboration_label', models.CharField(default='Collaboration questions and comments', max_length=255, verbose_name='label')),
                ('proposal_collaboration_help_text', models.TextField(blank=True, verbose_name='help text')),
                ('proposal_realism_label', models.CharField(default='Cost realism questions and comments', max_length=255, verbose_name='label')),
                ('proposal_realism_help_text', models.TextField(blank=True, verbose_name='help text')),
                ('proposal_qualifications_label', models.CharField(default='Qualifications questions and comments', max_length=255, verbose_name='label')),
                ('proposal_qualifications_help_text', models.TextField(blank=True, verbose_name='help text')),
                ('proposal_evaluation_label', models.CharField(default='Evaluation questions and comments', max_length=255, verbose_name='label')),
                ('proposal_evaluation_help_text', models.TextField(blank=True, verbose_name='help text')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'determination settings',
            },
        ),
    ]
