# Generated by Django 2.2.10 on 2020-02-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('determinations', '0008_rename_more_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='determination',
            name='send_notice',
            field=models.BooleanField(default=True, verbose_name='Send message to applicant'),
        ),
    ]
