# Generated by Django 3.1 on 2022-01-11 13:14

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("determinations", "0010_add_determination_stream_field_forms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="determination",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="determination",
            name="form_data",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
