# Generated by Django 2.2.13 on 2020-06-26 12:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('determinations', '0014_auto_20200626_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='determination',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
