# Generated by Django 3.2.16 on 2022-11-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('determinations', '0014_alter_determination_formfield_send_notice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='determinationformsettings',
            options={'verbose_name': 'determination form settings'},
        ),
    ]
