# Generated by Django 2.2.13 on 2020-06-30 12:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('determinations', '0016_auto_20200630_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='determination',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
