# Generated by Django 4.2.17 on 2025-01-14 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("determinations", "0016_rename_section_text_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="determination",
            name="drupal_id",
        ),
    ]
