# Generated by Django 5.2.11 on 2026-03-03 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("determinations", "0018_help_text_rich_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="determination",
            options={
                "verbose_name": "determination",
                "verbose_name_plural": "determinations",
            },
        ),
        migrations.AlterModelOptions(
            name="determinationform",
            options={
                "verbose_name": "determination form",
                "verbose_name_plural": "determination forms",
            },
        ),
    ]
