# Generated by Django 5.2.12 on 2026-03-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("determinations", "0019_alter_determination_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="determination",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="determination",
            name="is_draft",
            field=models.BooleanField(default=False, verbose_name="draft"),
        ),
        migrations.AlterField(
            model_name="determination",
            name="message",
            field=models.TextField(blank=True, verbose_name="determination message"),
        ),
        migrations.AlterField(
            model_name="determination",
            name="outcome",
            field=models.IntegerField(
                choices=[
                    (0, "Dismissed"),
                    (1, "More information requested"),
                    (2, "Approved"),
                ],
                default=1,
                verbose_name="determination",
            ),
        ),
        migrations.AlterField(
            model_name="determination",
            name="send_notice",
            field=models.BooleanField(
                default=True, verbose_name="send message to applicant"
            ),
        ),
        migrations.AlterField(
            model_name="determination",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="update time"),
        ),
    ]
