# Generated by Django 4.2.18 on 2025-01-31 07:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0006_use_category_options_as_submission_filter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="metaterm",
            options={"verbose_name": "Tag", "verbose_name_plural": "Tags"},
        ),
    ]
