# Generated by Django 5.2.13 on 2026-04-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0007_rename_meta_terms_to_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="option",
            options={"verbose_name": "option", "verbose_name_plural": "options"},
        ),
        migrations.AlterField(
            model_name="metaterm",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Archived terms can be viewed but not set on content.",
                verbose_name="archived",
            ),
        ),
    ]
