# Generated by Django 5.2.17 on 2026-09-21 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0008_alter_category_options_alter_option_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="option",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "option",
                "verbose_name_plural": "options",
            },
        ),
    ]
