# Generated by Django 5.2.12 on 2026-03-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0008_alter_category_options_alter_option_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metaterm",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Archived terms can be viewed but not set on content.",
                verbose_name="archived",
            ),
        ),
    ]
