# Generated by Django 2.2.9 on 2020-02-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset_network_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetnetworkworkpage',
            name='region_heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heading'),
        ),
    ]
