# Generated by Django 2.0.2 on 2018-03-01 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_funding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpagepersontype',
            name='person_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.PersonType'),
        ),
    ]
