# Generated by Django 2.0.2 on 2018-08-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_change_the_contact_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='personindexpage',
            name='introduction',
            field=models.TextField(blank=True),
        ),
    ]
