# Generated by Django 4.2.22 on 2025-06-17 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
