# Generated by Django 5.2.11 on 2026-03-03 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project_reports", "0002_report_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={
                "ordering": ("-end_date",),
                "verbose_name": "report",
                "verbose_name_plural": "reports",
            },
        ),
        migrations.AlterModelOptions(
            name="reportconfig",
            options={
                "verbose_name": "report config",
                "verbose_name_plural": "report configs",
            },
        ),
        migrations.AlterModelOptions(
            name="reportprivatefiles",
            options={
                "verbose_name": "report private file",
                "verbose_name_plural": "report private files",
            },
        ),
        migrations.AlterModelOptions(
            name="reportversion",
            options={
                "verbose_name": "report version",
                "verbose_name_plural": "report versions",
            },
        ),
    ]
