# Generated by Django 5.2.11 on 2026-03-03 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flags", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flag",
            options={"verbose_name": "flag", "verbose_name_plural": "flags"},
        ),
    ]
