# Generated by Django 4.2.9 on 2024-01-07 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("partner", "0002_currency_symbol_setting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partnerindexpage",
            name="social_image",
        ),
        migrations.RemoveField(
            model_name="partnerindexpage",
            name="social_text",
        ),
        migrations.RemoveField(
            model_name="partnerpage",
            name="social_image",
        ),
        migrations.RemoveField(
            model_name="partnerpage",
            name="social_text",
        ),
    ]
