# Generated by Django 2.2.16 on 2020-09-17 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('categories', '0005_alter_is_archived_field_on_terms'),
        ('partner', '0002_remove_partnerpage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentCategorySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(help_text='Select the categories that should be used in investments.', to='categories.Category')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Investment Category Settings',
            },
        ),
    ]
