# Generated by Django 4.2.9 on 2024-01-10 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("partner", "0003_remove_partnerindexpage_social_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investmentcategory",
            name="investment",
        ),
        migrations.RemoveField(
            model_name="investmentcategorysettings",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="investmentcategorysettings",
            name="site",
        ),
        migrations.RemoveField(
            model_name="partnerindexpage",
            name="header_image",
        ),
        migrations.RemoveField(
            model_name="partnerindexpage",
            name="listing_image",
        ),
        migrations.RemoveField(
            model_name="partnerindexpage",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="partnerpage",
            name="header_image",
        ),
        migrations.RemoveField(
            model_name="partnerpage",
            name="listing_image",
        ),
        migrations.RemoveField(
            model_name="partnerpage",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="partnerpage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="Investment",
        ),
        migrations.DeleteModel(
            name="InvestmentCategory",
        ),
        migrations.DeleteModel(
            name="InvestmentCategorySettings",
        ),
        migrations.DeleteModel(
            name="PartnerIndexPage",
        ),
        migrations.DeleteModel(
            name="PartnerPage",
        ),
    ]
