# Generated by Django 2.2.16 on 2020-09-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_forms", "0002_add_document_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="formfield",
            name="clean_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Safe name of the form field, the label converted to ascii_snake_case",
                max_length=255,
                verbose_name="name",
            ),
        ),
    ]
