# Generated by Django 4.2.9 on 2024-01-07 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_forms", "0004_auto_20220722_0844"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formpage",
            name="social_image",
        ),
        migrations.RemoveField(
            model_name="formpage",
            name="social_text",
        ),
    ]
