# Generated by Django 4.2.9 on 2024-01-11 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_forms", "0005_remove_formpage_social_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formpage",
            name="header_image",
        ),
        migrations.RemoveField(
            model_name="formpage",
            name="listing_image",
        ),
        migrations.RemoveField(
            model_name="formpage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="FormField",
        ),
        migrations.DeleteModel(
            name="FormPage",
        ),
    ]
