# Generated by Django 2.0.13 on 2019-08-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0005_add_user_to_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contact_phone',
            field=models.TextField(default='', verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='project',
            name='proposed_end',
            field=models.DateTimeField(null=True, verbose_name='Proposed Start Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='proposed_start',
            field=models.DateTimeField(null=True, verbose_name='Proposed Start Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='user_has_updated_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_address',
            field=models.TextField(default='', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_email',
            field=models.TextField(default='', verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_legal_name',
            field=models.TextField(default='', verbose_name='Person or Organisation name'),
        ),
    ]
