# Generated by Django 2.0.13 on 2019-08-07 08:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0007_fix_proposed_end_date_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
