# Generated by Django 2.0.13 on 2019-08-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0017_add_sent_to_compliance_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='value',
            new_name='requested_value',
        ),
    ]
