# Generated by Django 2.0.13 on 2019-09-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0020_add_finance_email_to_project_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='sent_to_finance_at',
            field=models.DateTimeField(null=True),
        ),
    ]
