# Generated by Django 2.1.11 on 2019-11-12 11:57

from django.db import migrations, models
import opentech.apply.projects.models
import opentech.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0024_allow_no_comments_on_pr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(storage=opentech.storage_backends.PrivateMediaStorage(), upload_to=opentech.apply.projects.models.contract_path),
        ),
        migrations.AlterField(
            model_name='packetfile',
            name='document',
            field=models.FileField(storage=opentech.storage_backends.PrivateMediaStorage(), upload_to=opentech.apply.projects.models.document_path),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='file',
            field=models.FileField(storage=opentech.storage_backends.PrivateMediaStorage(), upload_to=opentech.apply.projects.models.receipt_path),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='invoice',
            field=models.FileField(storage=opentech.storage_backends.PrivateMediaStorage(), upload_to=opentech.apply.projects.models.invoice_path),
        ),
    ]
