# Generated by Django 2.2.11 on 2020-04-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset_network_resources', '0003_auto_20200303_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetnetworkresourcepage',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tag'),
        ),
    ]
