# Generated by Django 2.2.11 on 2020-03-30 17:11

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reset_network_open_calls', '0002_auto_20200303_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetnetworkopencallspage',
            name='content_long_text',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='resetnetworkopencallspage',
            name='content_text',
            field=models.TextField(blank=True, verbose_name='Intro'),
        ),
    ]
