# Generated by Django 2.2.11 on 2020-04-01 08:15

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reset_network_open_calls', '0003_add_long_text_open_calls_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetnetworkopencallspage',
            name='content_bottom_text',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Bottom'),
        ),
    ]
