# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import opentech.apply.workflow


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='workflow',
            field=models.CharField(choices=[('single', opentech.apply.workflow.SingleStage), ('double', opentech.apply.workflow.DoubleStage)], default='single', max_length=100),
        ),
    ]
