# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_fund_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='workflow',
            field=models.CharField(choices=[('single', 'Single Stage'), ('double', 'Two Stage')], default='single', max_length=100),
        ),
    ]
