# Generated by Django 2.0.2 on 2018-07-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
