# Generated by Django 2.0.13 on 2019-07-10 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0032_migrate_submission_to_generic_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='submission',
        ),
    ]
