# Generated by Django 2.2.24 on 2021-08-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0058_add_project_invoicing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("applicant", "Applicant(s)"),
                    ("team", "Staff"),
                    ("reviewers", "Reviewers"),
                    ("partners", "Partners"),
                    ("all", "All"),
                ],
                default="applicant",
                max_length=30,
            ),
        ),
    ]
