# Generated by Django 2.2.24 on 2021-09-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0059_rename_team_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='visibility',
            field=models.CharField(choices=[('applicant', 'Applicant(s)'), ('team', 'Staff'), ('reviewers', 'Reviewers'), ('partners', 'Partners'), ('finance', 'Finance(s)'), ('payment_team', 'Payment Team'), ('all', 'All')], default='applicant', max_length=30),
        ),
    ]
