# Generated by Django 4.2.8 on 2023-12-18 09:35

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import hypha.apply.activity.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0077_remove_deleted_submission_actions"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "file",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to=hypha.apply.activity.models.get_attachment_upload_path,
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="activity.activity",
                    ),
                ),
            ],
        ),
    ]
