# Generated by Django 5.2.11 on 2026-02-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0087_alter_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="deleted",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
