# Generated by Django 5.2.12 on 2026-03-25 18:29

from django.db import migrations

from hypha.apply.activity.models import APPLICANT


def convert_partner_perms_to_applicant(apps, schema_editor):
    Activity = apps.get_model("activity", "Activity")

    # Encompasses both "partner" & "applicant partner" visibilities
    Activity.objects.filter(visibility__contains="partner").update(visibility=APPLICANT)


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0088_activity_deleted"),
    ]

    operations = [migrations.RunPython(convert_partner_perms_to_applicant)]
