# Generated by Django 5.2.12 on 2026-03-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0088_activity_deleted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "base_manager_name": "objects",
                "ordering": ["-timestamp"],
                "verbose_name": "activity",
                "verbose_name_plural": "activities",
            },
        ),
        migrations.AlterModelOptions(
            name="activityattachment",
            options={
                "verbose_name": "activity attachment",
                "verbose_name_plural": "activity attachments",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "event", "verbose_name_plural": "events"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "message", "verbose_name_plural": "messages"},
        ),
        migrations.AlterField(
            model_name="activity",
            name="message",
            field=models.TextField(verbose_name="message"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("applicant", "Applicants"),
                    ("team", "Staff only"),
                    ("reviewers", "Reviewers"),
                    ("partners", "Partners"),
                    ("all", "All"),
                    ("applicant partners", "Applicants & Partners"),
                ],
                default="applicant",
                max_length=30,
                verbose_name="visibility",
            ),
        ),
    ]
