# Generated by Django 5.2.11 on 2026-03-03 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0088_activity_deleted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "base_manager_name": "objects",
                "ordering": ["-timestamp"],
                "verbose_name": "activity",
                "verbose_name_plural": "activities",
            },
        ),
        migrations.AlterModelOptions(
            name="activityattachment",
            options={
                "verbose_name": "activity attachment",
                "verbose_name_plural": "activity attachments",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "event", "verbose_name_plural": "events"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "message", "verbose_name_plural": "messages"},
        ),
    ]
