# Generated by Django 5.2.13 on 2026-04-13 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0090_alter_activity_visibility_alter_event_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("UPDATE_LEAD", "updated lead"),
                    ("BATCH_UPDATE_LEAD", "batch updated lead"),
                    ("EDIT_SUBMISSION", "edited submission"),
                    ("APPLICANT_EDIT", "edited applicant"),
                    ("NEW_SUBMISSION", "submitted new submission"),
                    ("DRAFT_SUBMISSION", "submitted new draft submission"),
                    ("SCREENING", "screened"),
                    ("TRANSITION", "transitioned"),
                    ("BATCH_TRANSITION", "batch transitioned"),
                    ("DETERMINATION_OUTCOME", "sent determination outcome"),
                    ("BATCH_DETERMINATION_OUTCOME", "sent batch determination outcome"),
                    ("INVITED_TO_PROPOSAL", "invited to proposal"),
                    ("REVIEWERS_UPDATED", "updated reviewers"),
                    ("BATCH_REVIEWERS_UPDATED", "batch updated reviewers"),
                    ("READY_FOR_REVIEW", "marked ready for review"),
                    ("BATCH_READY_FOR_REVIEW", "marked batch ready for review"),
                    ("NEW_REVIEW", "added new review"),
                    ("COMMENT", "added comment"),
                    ("PROPOSAL_SUBMITTED", "submitted proposal"),
                    ("OPENED_SEALED", "opened sealed submission"),
                    ("REVIEW_OPINION", "reviewed opinion"),
                    ("DELETE_SUBMISSION", "deleted submission"),
                    ("ANONYMIZE_SUBMISSION", "anonymized submission"),
                    ("DELETE_REVIEW", "deleted review"),
                    ("DELETE_REVIEW_OPINION", "deleted review opinion"),
                    ("CREATED_PROJECT", "created project"),
                    ("UPDATE_PROJECT_LEAD", "updated project lead"),
                    ("UPDATE_PROJECT_TITLE", "updated project title"),
                    ("EDIT_REVIEW", "edited review"),
                    ("SEND_FOR_APPROVAL", "sent for approval"),
                    ("APPROVE_PROJECT", "approved project"),
                    ("ASSIGN_PAF_APPROVER", "assign project form approver"),
                    ("APPROVE_PAF", "approved project form"),
                    ("PROJECT_TRANSITION", "transitioned project"),
                    ("REQUEST_PROJECT_CHANGE", "requested project change"),
                    ("SUBMIT_CONTRACT_DOCUMENTS", "submitted contract documents"),
                    ("UPLOAD_DOCUMENT", "uploaded document to project"),
                    ("UPLOAD_CONTRACT", "uploaded contract to project"),
                    ("APPROVE_CONTRACT", "approved contract"),
                    ("CREATE_INVOICE", "created invoice for project"),
                    ("UPDATE_INVOICE_STATUS", "updated invoice status"),
                    ("APPROVE_INVOICE", "approve invoice"),
                    ("DELETE_INVOICE", "deleted invoice"),
                    ("SENT_TO_COMPLIANCE", "sent project to compliance"),
                    ("UPDATE_INVOICE", "updated invoice"),
                    ("SUBMIT_REPORT", "submitted report"),
                    ("SKIPPED_REPORT", "skipped report"),
                    ("REPORT_FREQUENCY_CHANGED", "changed report frequency"),
                    ("DISABLED_REPORTING", "disabled reporting"),
                    ("REPORT_NOTIFY", "notified report"),
                    ("REVIEW_REMINDER", "reminder to review"),
                    ("BATCH_DELETE_SUBMISSION", "batch deleted submissions"),
                    ("BATCH_SKELETON_SUBMISSION", "batch anonymized submissions"),
                    ("BATCH_ARCHIVE_SUBMISSION", "batch archive submissions"),
                    ("BATCH_INVOICE_STATUS_UPDATE", "batch update invoice status"),
                    ("STAFF_ACCOUNT_CREATED", "created new account"),
                    ("STAFF_ACCOUNT_EDITED", "edited account"),
                    ("ARCHIVE_SUBMISSION", "archived submission"),
                    ("UNARCHIVE_SUBMISSION", "unarchived submission"),
                    ("REMOVE_TASK", "remove task"),
                    ("INVITE_COAPPLICANT", "invite co-applicant"),
                ],
                max_length=50,
                verbose_name="verb",
            ),
        ),
    ]
