# Generated by Django 4.2.11 on 2024-07-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0004_alter_task_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="message",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="code",
            field=models.CharField(
                choices=[
                    ("comment_task", "Comment Task"),
                    ("submission_draft", "Submission Draft"),
                    ("determination_draft", "Determination draft"),
                    ("review_draft", "Review Draft"),
                    ("project_waiting_paf", "Project waiting PAF"),
                    ("project_submit_paf", "Project submit PAF"),
                    ("paf_required_changes", "PAF required changes"),
                    ("paf_waiting_assignee", "PAF waiting assignee"),
                    ("paf_waiting_approval", "PAF waiting approval"),
                    ("project_waiting_contract", "Project waiting contract"),
                    (
                        "project_waiting_contract_document",
                        "Project waiting contract document",
                    ),
                    (
                        "project_waiting_contract_review",
                        "Project waiting contract review",
                    ),
                    ("project_waiting_invoice", "Project waiting invoice"),
                    ("invoice_required_changes", "Invoice required changes"),
                    ("invoice_waiting_approval", "Invoice waiting approval"),
                    ("invoice_waiting_paid", "Invoice waiting paid"),
                    ("report_due", "Report due"),
                ],
                max_length=50,
            ),
        ),
    ]
