# Generated by Django 4.2.20 on 2025-03-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0007_alter_task_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="code",
            field=models.CharField(
                choices=[
                    ("comment_task", "Comment Task"),
                    ("submission_draft", "Submission Draft"),
                    ("determination_draft", "Determination draft"),
                    ("review_draft", "Review Draft"),
                    ("project_waiting_paf", "Project waiting project form"),
                    ("project_waiting_sow", "Project waiting scope of work"),
                    ("project_submit_pfs", "Project submit project form(s)"),
                    ("project_submit_sow", "Project submit scope of work"),
                    ("paf_required_changes", "Project form required changes"),
                    ("paf_waiting_assignee", "Project form waiting assignee"),
                    ("paf_waiting_approval", "Project form waiting approval"),
                    ("project_waiting_contract", "Project waiting contract"),
                    (
                        "project_waiting_contract_document",
                        "Project waiting contract document",
                    ),
                    (
                        "project_waiting_contract_review",
                        "Project waiting contract review",
                    ),
                    ("project_waiting_invoice", "Project waiting invoice"),
                    ("invoice_required_changes", "Invoice required changes"),
                    ("invoice_waiting_approval", "Invoice waiting approval"),
                    ("invoice_waiting_paid", "Invoice waiting paid"),
                    ("report_due", "Report due"),
                    ("download_submissions_export", "Download exported submissions"),
                    (
                        "failed_submission_export",
                        "Failed to generate submissions export file",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
