# Generated by Django 5.2.11 on 2026-03-03 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0008_alter_task_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
            },
        ),
    ]
