# Generated by Django 2.2.16 on 2020-09-21 07:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="CookieConsentSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cookieconsent_active",
                    models.BooleanField(
                        default=False, verbose_name="Activate cookie consent feature"
                    ),
                ),
                (
                    "cookieconsent_title",
                    models.CharField(
                        default="Your cookie settings",
                        max_length=255,
                        verbose_name="cookie consent title",
                    ),
                ),
                (
                    "cookieconsent_message",
                    wagtail.fields.RichTextField(
                        default='<p>This website deploys cookies for basic functionality and to keep it secure. These cookies are strictly necessary. Optional analysis cookies which provide us with statistical information about the use of the website may also be deployed, but only with your consent. Please review our <a href="/data-privacy-policy/">Privacy &amp; Data Policy</a> for more information.</p>',
                        verbose_name="cookie consent message",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cookie consent settings",
            },
        ),
    ]
