# Generated by Django 4.2.9 on 2024-01-11 14:38

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cookieconsent", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cookieconsentsettings",
            name="site",
        ),
        migrations.AlterField(
            model_name="cookieconsentsettings",
            name="cookieconsent_active",
            field=models.BooleanField(
                default=False, verbose_name="Activate cookie consent feature"
            ),
        ),
        migrations.AlterField(
            model_name="cookieconsentsettings",
            name="cookieconsent_message",
            field=wagtail.fields.RichTextField(
                default='<p>This website deploys cookies for basic functionality and to keep it secure. These cookies are strictly necessary. Optional analysis cookies which provide us with statistical information about the use of the website may also be deployed, but only with your consent. Please review our <a href="/data-privacy-policy/">Privacy &amp; Data Policy</a> for more information.</p>',
                verbose_name="cookie consent message",
            ),
        ),
        migrations.AlterField(
            model_name="cookieconsentsettings",
            name="cookieconsent_title",
            field=models.CharField(
                default="Your cookie settings",
                max_length=255,
                verbose_name="cookie consent title",
            ),
        ),
    ]
