# Generated by Django 4.2.11 on 2024-06-04 19:41

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cookieconsent", "0002_remove_cookieconsentsettings_site_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cookieconsentsettings",
            options={"verbose_name": "Cookie banner settings"},
        ),
        migrations.AddField(
            model_name="cookieconsentsettings",
            name="cookieconsent_analytics",
            field=models.BooleanField(
                default=False,
                verbose_name="Include consent option for analytics cookies",
            ),
        ),
        migrations.AddField(
            model_name="cookieconsentsettings",
            name="cookieconsent_analytics_about",
            field=wagtail.fields.RichTextField(
                default="<p>With these cookies we count visits and traffic sources to help improve the performance of our services through metrics.  These cookies show us which pages on our services are the most and the least popular, and how users navigate our services.  The information collected is aggregated and contains no personally identifiable information.  If you block these cookies, then we will not know when you have used our services.</p>",
                verbose_name='Analytics cookies information to be displayed under "Learn More"',
            ),
        ),
        migrations.AddField(
            model_name="cookieconsentsettings",
            name="cookieconsent_essential_about",
            field=wagtail.fields.RichTextField(
                default="<p>Strictly necessary for the operation of a website because they enable you to navigate around the site and use features.  These cookies cannot be switched off in our systems and do not store any personally identifiable information.</p>",
                verbose_name='Essential cookies information to be displayed under "Learn More"',
            ),
        ),
        migrations.AlterField(
            model_name="cookieconsentsettings",
            name="cookieconsent_active",
            field=models.BooleanField(
                default=False, verbose_name="Activate cookie pop-up banner"
            ),
        ),
        migrations.AlterField(
            model_name="cookieconsentsettings",
            name="cookieconsent_message",
            field=wagtail.fields.RichTextField(
                default='<p>This website deploys cookies for basic functionality and to keep it secure. These cookies are strictly necessary. Optional analysis cookies which provide us with statistical information about the use of the website may also be deployed, but only with your consent. Please review our <a href="/data-privacy-policy/">Privacy &amp; Data Policy</a> for more information.</p>',
                verbose_name="Cookie consent message",
            ),
        ),
        migrations.AlterField(
            model_name="cookieconsentsettings",
            name="cookieconsent_title",
            field=models.CharField(
                default="Your cookie settings",
                max_length=255,
                verbose_name="Cookie banner title",
            ),
        ),
    ]
