# Generated by Django 2.0.2 on 2018-03-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_json_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Draft'),
        ),
    ]
