# Generated by Django 2.0.13 on 2019-08-19 11:10

import json

from django.db import migrations

from hypha.apply.review.options import NA

# Block types are matched by name rather than class: the historical streamfield
# definition deconstructs the score block to a plain StructBlock, so the
# ScoreFieldBlock helpers on the model are not available here. Using the
# historical model also keeps this migration working on a fresh database as
# fields are added to Review later on.
SCORE = "score"


def get_answers(review):
    for field in review.form_fields.raw_data:
        if field["type"] != SCORE:
            continue

        answer = review.form_data.get(field.get("id"))
        if isinstance(answer, str):
            # Scored answers used to be stored as JSON.
            answer = json.loads(answer)
        yield answer[1]


def review_score_update(apps, schema_editor):
    Review = apps.get_model("review", "Review")

    for review in Review.objects.iterator():
        # Update the score.
        scores = []
        for score in get_answers(review):
            # Include NA answers as 0.
            if int(score) == NA:
                score = 0
            scores.append(int(score))

        try:
            score = sum(scores) / len(scores)
        except ZeroDivisionError:
            score = NA

        # A queryset update leaves "updated_at" untouched.
        Review.objects.filter(pk=review.pk).update(score=score)


def review_score_revert(apps, schema_editor):
    Review = apps.get_model("review", "Review")

    for review in Review.objects.iterator():
        # Update the score.
        scores = []
        for score in get_answers(review):
            # Exclude NA answers.
            if int(score) != NA:
                scores.append(int(score))

        try:
            score = sum(scores) / len(scores)
        except ZeroDivisionError:
            score = NA

        Review.objects.filter(pk=review.pk).update(score=score)


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0019_replace_existing_author_field"),
    ]

    operations = [
        migrations.RunPython(review_score_update, review_score_revert),
    ]
