# Generated by Django 3.1 on 2022-01-11 13:14

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0023_add_score_without_text_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="form_data",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
