# Generated by Django 4.2.17 on 2025-01-14 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0025_auto_20220722_0844"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="drupal_id",
        ),
    ]
