# Generated by Django 4.2.9 on 2024-01-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0025_auto_20220722_0844"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Staff Only"),
                    ("reviewers", "Reviewers and Staff"),
                ],
                default="private",
                max_length=10,
                verbose_name="Visibility",
            ),
        ),
    ]
