# Generated by Django 4.2.7 on 2023-11-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0025_auto_20220722_0844"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="visibility",
            field=models.CharField(
                choices=[("private", "Private"), ("reviewers", "Advisors and Staff")],
                default="private",
                max_length=10,
                verbose_name="Visibility",
            ),
        ),
    ]
