# Generated by Django 5.2.11 on 2026-03-03 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0027_help_text_rich_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "review", "verbose_name_plural": "reviews"},
        ),
        migrations.AlterModelOptions(
            name="reviewform",
            options={
                "verbose_name": "review form",
                "verbose_name_plural": "review forms",
            },
        ),
        migrations.AlterModelOptions(
            name="reviewopinion",
            options={
                "verbose_name": "review opinion",
                "verbose_name_plural": "review opinions",
            },
        ),
    ]
