# Generated by Django 5.2.13 on 2026-04-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0027_help_text_rich_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "review", "verbose_name_plural": "reviews"},
        ),
        migrations.AlterModelOptions(
            name="reviewform",
            options={
                "verbose_name": "review form",
                "verbose_name_plural": "review forms",
            },
        ),
        migrations.AlterModelOptions(
            name="reviewopinion",
            options={
                "verbose_name": "review opinion",
                "verbose_name_plural": "review opinions",
            },
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="review",
            name="is_draft",
            field=models.BooleanField(default=False, verbose_name="draft"),
        ),
        migrations.AlterField(
            model_name="review",
            name="recommendation",
            field=models.IntegerField(
                choices=[(0, "No"), (1, "Maybe"), (2, "Yes")],
                default=0,
                verbose_name="recommendation",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="update time"),
        ),
        migrations.AlterField(
            model_name="review",
            name="visibility",
            field=models.CharField(
                choices=[("private", "Private"), ("reviewers", "Reviewers and Staff")],
                default="private",
                max_length=10,
                verbose_name="visibility",
            ),
        ),
    ]
