# Generated by Django 4.2.26 on 2025-11-18 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("review", "0027_help_text_rich_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="related_submission_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="related_submission_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
