# Generated by Django 5.2.12 on 2026-03-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0028_alter_review_options_alter_reviewform_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="review",
            name="is_draft",
            field=models.BooleanField(default=False, verbose_name="draft"),
        ),
        migrations.AlterField(
            model_name="review",
            name="recommendation",
            field=models.IntegerField(
                choices=[(0, "No"), (1, "Maybe"), (2, "Yes")],
                default=0,
                verbose_name="recommendation",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="update time"),
        ),
        migrations.AlterField(
            model_name="review",
            name="visibility",
            field=models.CharField(
                choices=[("private", "Private"), ("reviewers", "Reviewers and Staff")],
                default="private",
                max_length=10,
                verbose_name="visibility",
            ),
        ),
    ]
