# Generated by Django 5.2.17 on 2026-09-10 11:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0028_alter_review_options_alter_reviewform_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="form_fields",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 6),
                    ("markdown_text", 6),
                    ("char", 9),
                    ("text", 6),
                    ("text_markup", 10),
                    ("score", 11),
                    ("score_without_text", 11),
                    ("checkbox", 13),
                    ("dropdown", 16),
                    ("recommendation", 18),
                    ("comments", 18),
                    ("visibility", 18),
                ],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Label"}),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Help text", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Required", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Tick this if the answer will contain personally identifiable information, such as a name, address, phone number or date of birth. Only the applicant, their co-applicants and staff will be able to see the answer. Reviewers and other users will see that the question was asked, but not the answer.",
                            "label": "Personal information",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Default value", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 1000, "label": "Word limit"},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 0),
                                ("help_text", 1),
                                ("required", 2),
                                ("is_pii", 3),
                                ("default_value", 4),
                                ("word_limit", 5),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("email", "Email"), ("url", "URL")],
                            "label": "Format",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Default value", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 0),
                                ("help_text", 1),
                                ("required", 2),
                                ("is_pii", 3),
                                ("format", 7),
                                ("default_value", 8),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"group": "Fields", "label": "Paragraph"},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 0),
                                ("help_text", 1),
                                ("required", 2),
                                ("is_pii", 3),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    12: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 0),
                                ("help_text", 1),
                                ("required", 2),
                                ("is_pii", 3),
                                ("default_value", 12),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    14: ("wagtail.blocks.CharBlock", (), {"label": "Choice"}),
                    15: ("wagtail.blocks.ListBlock", (14,), {}),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 0),
                                ("help_text", 1),
                                ("required", 2),
                                ("is_pii", 3),
                                ("choices", 15),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    17: ("wagtail.blocks.static_block.StaticBlock", (), {}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("help_text", 1), ("info", 17)]],
                        {"group": " Required"},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="reviewform",
            name="form_fields",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 6),
                    ("markdown_text", 6),
                    ("char", 9),
                    ("text", 6),
                    ("text_markup", 10),
                    ("score", 11),
                    ("score_without_text", 11),
                    ("checkbox", 13),
                    ("dropdown", 16),
                    ("recommendation", 18),
                    ("comments", 18),
                    ("visibility", 18),
                ],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Label"}),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Help text", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Required", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Tick this if the answer will contain personally identifiable information, such as a name, address, phone number or date of birth. Only the applicant, their co-applicants and staff will be able to see the answer. Reviewers and other users will see that the question was asked, but not the answer.",
                            "label": "Personal information",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Default value", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 1000, "label": "Word limit"},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 0),
                                ("help_text", 1),
                                ("required", 2),
                                ("is_pii", 3),
                                ("default_value", 4),
                                ("word_limit", 5),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("email", "Email"), ("url", "URL")],
                            "label": "Format",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Default value", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 0),
                                ("help_text", 1),
                                ("required", 2),
                                ("is_pii", 3),
                                ("format", 7),
                                ("default_value", 8),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"group": "Fields", "label": "Paragraph"},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 0),
                                ("help_text", 1),
                                ("required", 2),
                                ("is_pii", 3),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    12: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 0),
                                ("help_text", 1),
                                ("required", 2),
                                ("is_pii", 3),
                                ("default_value", 12),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    14: ("wagtail.blocks.CharBlock", (), {"label": "Choice"}),
                    15: ("wagtail.blocks.ListBlock", (14,), {}),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 0),
                                ("help_text", 1),
                                ("required", 2),
                                ("is_pii", 3),
                                ("choices", 15),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    17: ("wagtail.blocks.static_block.StaticBlock", (), {}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("help_text", 1), ("info", 17)]],
                        {"group": " Required"},
                    ),
                },
            ),
        ),
    ]
