# Generated by Django 3.2.14 on 2022-07-22 08:44

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("public_funds", "0013_add_more_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseapplicationpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.CharBlock(
                            form_classname="full title", icon="title"
                        ),
                    ),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    (
                        "box",
                        wagtail.blocks.StructBlock(
                            [
                                ("box_content", wagtail.blocks.RichTextBlock()),
                                ("box_class", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        "more",
                        wagtail.blocks.StructBlock(
                            [
                                ("more_content", wagtail.blocks.RichTextBlock()),
                                ("more_content_more", wagtail.blocks.RichTextBlock()),
                                (
                                    "more_class",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                            ]
                        ),
                    ),
                    (
                        "apply_link",
                        wagtail.blocks.StructBlock(
                            [("application", wagtail.blocks.PageChooserBlock())]
                        ),
                    ),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        "quote",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "quote",
                                    wagtail.blocks.CharBlock(form_classname="title"),
                                ),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                ("job_title", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    ),
                    ("embed", wagtail.embeds.blocks.EmbedBlock()),
                    (
                        "call_to_action",
                        wagtail.snippets.blocks.SnippetChooserBlock(
                            "utils.CallToActionSnippet",
                            template="blocks/call_to_action_block.html",
                        ),
                    ),
                    (
                        "document",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "document",
                                    wagtail.documents.blocks.DocumentChooserBlock(),
                                ),
                                ("title", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="labpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.CharBlock(
                            form_classname="full title", icon="title"
                        ),
                    ),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    (
                        "box",
                        wagtail.blocks.StructBlock(
                            [
                                ("box_content", wagtail.blocks.RichTextBlock()),
                                ("box_class", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        "more",
                        wagtail.blocks.StructBlock(
                            [
                                ("more_content", wagtail.blocks.RichTextBlock()),
                                ("more_content_more", wagtail.blocks.RichTextBlock()),
                                (
                                    "more_class",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                            ]
                        ),
                    ),
                    (
                        "apply_link",
                        wagtail.blocks.StructBlock(
                            [("application", wagtail.blocks.PageChooserBlock())]
                        ),
                    ),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        "quote",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "quote",
                                    wagtail.blocks.CharBlock(form_classname="title"),
                                ),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                ("job_title", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    ),
                    ("embed", wagtail.embeds.blocks.EmbedBlock()),
                    (
                        "call_to_action",
                        wagtail.snippets.blocks.SnippetChooserBlock(
                            "utils.CallToActionSnippet",
                            template="blocks/call_to_action_block.html",
                        ),
                    ),
                    (
                        "document",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "document",
                                    wagtail.documents.blocks.DocumentChooserBlock(),
                                ),
                                ("title", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
