# Generated by Django 4.2.9 on 2024-01-07 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_funds", "0014_auto_20220722_0844"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseapplicationpage",
            name="social_image",
        ),
        migrations.RemoveField(
            model_name="baseapplicationpage",
            name="social_text",
        ),
        migrations.RemoveField(
            model_name="fundindex",
            name="social_image",
        ),
        migrations.RemoveField(
            model_name="fundindex",
            name="social_text",
        ),
        migrations.RemoveField(
            model_name="labindex",
            name="social_image",
        ),
        migrations.RemoveField(
            model_name="labindex",
            name="social_text",
        ),
        migrations.RemoveField(
            model_name="labpage",
            name="social_image",
        ),
        migrations.RemoveField(
            model_name="labpage",
            name="social_text",
        ),
        migrations.RemoveField(
            model_name="opencallindexpage",
            name="social_image",
        ),
        migrations.RemoveField(
            model_name="opencallindexpage",
            name="social_text",
        ),
    ]
