# Generated by Django 2.2.9 on 2020-03-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset_network_person', '0002_auto_20200221_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetnetworkperson',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
