# Generated by Django 2.2.9 on 2020-03-11 16:20

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reset_network_person', '0003_auto_20200310_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetnetworkperson',
            name='about',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
