# Generated by Django 3.2.13 on 2022-04-12 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('apply_utils', '0001_add_pdf_page_size_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='TWOFASettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_required', models.BooleanField(default=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Two Factor Settings',
            },
        ),
    ]
