# Generated by Django 4.2.11 on 2024-06-04 16:40

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("apply_utils", "0001_add_pdf_page_size_setting"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionsDetailsSetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submissions Details Page Setting",
            },
        ),
        migrations.CreateModel(
            name="SubmissionsDetailsSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "sees_related_submissions",
                    models.BooleanField(
                        default=False,
                        help_text="Should members of the above Group see the related submissions side panel when reviewing a submission?",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                (
                    "setting",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions_details_settings",
                        to="apply_utils.submissionsdetailssetting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submissions Details Page Settings",
            },
        ),
        migrations.AddConstraint(
            model_name="submissionsdetailssettings",
            constraint=models.UniqueConstraint(
                fields=("setting", "group"), name="unique_site_group"
            ),
        ),
    ]
