# Generated by Django 4.2.17 on 2024-12-05 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apply_utils", "0001_add_pdf_page_size_setting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pdfpagesettings",
            name="site",
        ),
    ]
