# Generated by Django 4.2.17 on 2024-12-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apply_utils", "0002_remove_pdfpagesettings_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdfpagesettings",
            name="download_page_size",
            field=models.CharField(
                choices=[("A4", "A4"), ("legal", "Legal"), ("letter", "Letter")],
                default="A4",
                help_text="Page size of downloadable Project and Submission PDFs",
                max_length=6,
            ),
        ),
    ]
