# Generated by Django 2.0.2 on 2018-03-15 08:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_add_common_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptreview',
            name='review_ptr',
        ),
        migrations.RemoveField(
            model_name='proposalreview',
            name='review_ptr',
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.DeleteModel(
            name='ConceptReview',
        ),
        migrations.DeleteModel(
            name='ProposalReview',
        ),
    ]
