# Generated by Django 2.0.2 on 2018-07-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_streamform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
    ]
