# Generated by Django 2.0.2 on 2018-08-14 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0041_roundbasereviewform'),
        ('review', '0006_remove_review_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='funds.ApplicationRevision'),
        ),
    ]
