# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 10:52
from __future__ import unicode_literals

from django.db import migrations, models

import opentech.apply.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', opentech.apply.users.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
