# Generated by Django 2.0.2 on 2018-03-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_drupal_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('full_name', 'email')},
        ),
    ]
