# Generated by Django 2.0.13 on 2019-09-05 15:20

from django.db import migrations


SENTINEL_EMAIL = 'finance-sentinel'


def add_sentinel_user(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.create(
        email=SENTINEL_EMAIL,
        full_name='Compliance',
        slack='sentinel',
    )


def remove_sentinel_user(apps, schema_editor):
    User = apps.get_model('users', 'User')

    try:
        User.objects.get(email=SENTINEL_EMAIL).delete()
    except User.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_add_compliance_sentinel_user'),
    ]

    operations = [
        migrations.RunPython(
            add_sentinel_user,
            reverse_code=remove_sentinel_user,
        )
    ]
