# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0005_homepage_our_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='our_work_link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='our_work_link_text',
            field=models.CharField(max_length=255, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='our_work_title',
            field=models.CharField(max_length=255, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='our_work',
            field=wagtail.wagtailcore.fields.StreamField((('work', wagtail.wagtailcore.blocks.StructBlock((('icon', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('description', wagtail.wagtailcore.blocks.TextBlock(help_text='The first word will be bold'))))),)),
        ),
    ]
