# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0006_add_our_work_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='funds_link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='funds_link_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='funds_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='labs_link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='labs_link_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='labs_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='strapline_link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='strapline_link_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
