# Generated by Django 2.2.9 on 2020-02-07 14:55

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtaildocs', '0010_document_file_hash'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('images', '0003_customimage_drupal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetNetworkResourcePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content_heading', models.CharField(max_length=255, verbose_name='Heading')),
                ('content_text', wagtail.core.fields.RichTextField(blank=True, verbose_name='Text')),
                ('content_assets_heading', models.CharField(max_length=255, verbose_name='Heading')),
                ('content_links_heading', models.CharField(max_length=255, verbose_name='Heading')),
                ('card_heading', models.CharField(max_length=100)),
                ('card_text', models.TextField(blank=True)),
                ('card_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage')),
            ],
            options={
                'verbose_name': 'Reset Network Resource Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ResetNetworkResourcesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content_heading', models.CharField(max_length=255, verbose_name='Heading')),
            ],
            options={
                'verbose_name': 'Reset Network Resources Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ResetNetworkResourcePageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('heading', models.CharField(max_length=255, verbose_name='Heading')),
                ('link', models.URLField(verbose_name='Link')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_network_resource_page_links', to='wagtailcore.Page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResetNetworkResourcePageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_network_resource_page_category', to='reset_network_resources.ResetNetworkResourcePage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_network_resources_resetnetworkresourcepagecategory_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResetNetworkResourcePageAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('heading', models.CharField(max_length=255, verbose_name='Heading')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_network_resource_page_assets', to='wagtailcore.Page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='resetnetworkresourcepage',
            name='categories',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='reset_network_resources.ResetNetworkResourcePageCategory', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='resetnetworkresourcepage',
            name='content_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage', verbose_name='Image'),
        ),
    ]
