# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-28 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_drop_first_last_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='drupal_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
