# Generated by Django 2.0.2 on 2018-07-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_update_the_ordering_of_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slack',
            field=models.CharField(blank=True, help_text='This is the name we should "@mention" when sending notifications', max_length=50, verbose_name='Slack name'),
        ),
    ]
