# Generated by Django 2.0.9 on 2019-01-10 09:28

from django.contrib.auth.models import Group, Permission
from django.db import migrations

from opentech.apply.users.groups import STAFF_GROUP_NAME


class Migration(migrations.Migration):

    def add_permissions(apps, schema_editor):
        staff_group = Group.objects.get(name=STAFF_GROUP_NAME)
        staff_add_perm = Permission.objects.get(name='Can change event')
        staff_group.permissions.add(staff_add_perm)

    dependencies = [
        ('users', '0007_user_slack'),
    ]

    operations = [
        migrations.RunPython(add_permissions)
    ]
