# Generated by Django 2.0.9 on 2019-01-10 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_slack"),
    ]

    operations = []
