# Generated by Django 2.0.9 on 2018-12-19 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_add_community_reviewer_group"),
    ]

    operations = []
