# Generated by Django 2.0.13 on 2019-08-05 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_set_applicant_group"),
    ]

    operations = []
