# Generated by Django 3.2.19 on 2023-06-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('users', '0018_add_contracting_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSettings',
            new_name='AuthSettings',
        ),
    ]
