# Generated by Django 2.2.24 on 2021-11-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_add_contracting_group'),
        ('users', '0017_add_decision_maker_group'),
    ]

    operations = [
    ]
