# Generated by Django 3.2.22 on 2023-10-31 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0020_auto_20230625_1825"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupDesc",
            fields=[
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="auth.group",
                    ),
                ),
                (
                    "help_text",
                    models.CharField(max_length=255, verbose_name="Help Text"),
                ),
            ],
        ),
    ]
