# Generated by Django 4.1.13 on 2023-11-27 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_groupdesc"),
        ("users", "0022_confirmaccesstoken"),
    ]

    operations = []
