# Generated by Django 4.2.11 on 2024-03-28 19:18

from django.db import migrations
from django.contrib.auth.models import Group

from hypha.apply.users.groups import TEAMADMIN_GROUP_NAME
from hypha.apply.users.utils import update_is_staff


def migrate_is_staff(apps, schema_editor):
    group = Group.objects.get(name=TEAMADMIN_GROUP_NAME)
    users = group.user_set.all()

    [update_is_staff(None, user) for user in users]


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_merge_0021_groupdesc_0022_confirmaccesstoken"),
    ]

    operations = [migrations.RunPython(migrate_is_staff)]
