# Generated by Django 4.2.11 on 2024-05-14 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_update_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authsettings",
            name="register_extra_text",
        ),
    ]
