# Generated by Django 4.2.16 on 2024-09-27 05:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_remove_authsettings_register_extra_text"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GroupDesc",
        ),
    ]
