# Generated by Django 5.2.12 on 2026-03-26 19:48

from django.db import migrations
from django.contrib.auth.models import Group


def migrate_partners_to_coapplicants(apps, schema_editor):
    PARTNER_GROUP_NAME = "Partner"

    if Group.objects.filter(name=PARTNER_GROUP_NAME).exists():
        Group.objects.get(name=PARTNER_GROUP_NAME).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0027_remove_drupal_id_field"),
        ("funds", "0133_remove_applicationsubmission_partners"),
    ]

    operations = [migrations.RunPython(migrate_partners_to_coapplicants)]
