# Generated by Django 5.2.11 on 2026-03-03 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0027_remove_drupal_id_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="confirmaccesstoken",
            options={
                "ordering": ("modified",),
                "verbose_name": "Confirm Access Token",
                "verbose_name_plural": "Confirm Access Tokens",
            },
        ),
        migrations.AlterModelOptions(
            name="pendingsignup",
            options={
                "ordering": ("created",),
                "verbose_name": "Pending signup",
                "verbose_name_plural": "Pending signups",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("full_name", "email"),
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
