# Generated by Django 5.2.13 on 2026-04-13 08:22

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0028_remove_partner_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="confirmaccesstoken",
            options={
                "ordering": ("modified",),
                "verbose_name": "Confirm Access Token",
                "verbose_name_plural": "Confirm Access Tokens",
            },
        ),
        migrations.AlterModelOptions(
            name="pendingsignup",
            options={
                "ordering": ("created",),
                "verbose_name": "Pending signup",
                "verbose_name_plural": "Pending signups",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("full_name", "email"),
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AlterField(
            model_name="authsettings",
            name="consent_help",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="consent help"),
        ),
        migrations.AlterField(
            model_name="authsettings",
            name="consent_show",
            field=models.BooleanField(
                default=False, verbose_name="show consent checkbox?"
            ),
        ),
        migrations.AlterField(
            model_name="authsettings",
            name="consent_text",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="consent text"
            ),
        ),
        migrations.AlterField(
            model_name="authsettings",
            name="extra_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Displayed along side login form",
                verbose_name="login extra text",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="full name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="slack",
            field=models.CharField(
                blank=True,
                help_text='This is the name we should "@mention" when sending notifications',
                max_length=50,
                verbose_name="slack name",
            ),
        ),
    ]
