# Generated by Django 5.2.12 on 2026-03-31 09:50

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0028_alter_confirmaccesstoken_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authsettings",
            name="consent_help",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="consent help"),
        ),
        migrations.AlterField(
            model_name="authsettings",
            name="consent_show",
            field=models.BooleanField(
                default=False, verbose_name="show consent checkbox?"
            ),
        ),
        migrations.AlterField(
            model_name="authsettings",
            name="consent_text",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="consent text"
            ),
        ),
        migrations.AlterField(
            model_name="authsettings",
            name="extra_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Displayed along side login form",
                verbose_name="login extra text",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="full name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="slack",
            field=models.CharField(
                blank=True,
                help_text='This is the name we should "@mention" when sending notifications',
                max_length=50,
                verbose_name="slack name",
            ),
        ),
    ]
