# Generated by Django 2.0.13 on 2019-07-16 06:01

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_metacategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacategory',
            name='available_to_applicants',
            field=models.BooleanField(default=False, help_text='Make available to applicants'),
        ),
        migrations.AddField(
            model_name='metacategory',
            name='filter_on_dashboard',
            field=models.BooleanField(default=True, help_text='Make available to filter on dashboard'),
        ),
        migrations.AddField(
            model_name='metacategory',
            name='help_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='metacategory',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
