# Generated by Django 2.0.13 on 2019-07-30 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_rename_meta_categories_to_meta_terms'),
        ('funds', '0070_rename_meta_categories_to_meta_terms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaCategory',
        ),
    ]
