# Generated by Django 3.2.16 on 2022-12-12 08:37

from django.db import migrations


class Migration(migrations.Migration):
    """This migration is added to ensure all the migrations from wagtail is
    picked up and ran during the testing.

    The migrations from wagtail are picked up while running the "python manage.py migrate"
    but it somehow fails while the database schema is generated while running the django tests.
    """

    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
    ]

    operations = []
