# Generated by Django 4.2.9 on 2024-02-15 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_wagtail_4_reference_index_dependency"),
    ]

    # Remove the mailchimp settings table, and add a reverse migration to do nothing
    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS mailchimp_newslettersettings;"),
    ]
