# Generated by Django 4.2.16 on 2024-09-10 07:30

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_systemsettings_footer_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="home_strapline",
            field=wagtail.fields.RichTextField(
                default="",
                help_text="The strapline to be displayed on the homepage.",
                verbose_name="Strapline",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="home_title",
            field=models.CharField(
                default="",
                help_text="The title to be displayed on the homepage.",
                max_length=255,
                verbose_name="Title",
            ),
        ),
    ]
