# Generated by Django 4.2.18 on 2025-03-18 19:17

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0007_remove_drupal_id_field"),
        ("core", "0007_copy_homepage_title_strapline"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="home_no_applications_msg",
            field=wagtail.fields.RichTextField(
                default="<h4>There are currently no open applications, check back later!</h4>",
                help_text="The message to be displayed when there are no open applications.",
                verbose_name="No open applications message",
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="site_logo_mobile",
            field=models.ForeignKey(
                blank=True,
                help_text="Mobile site logo (if not set default will be used)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
    ]
