# Generated by Django 2.2.9 on 2020-02-04 11:42

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetNetworkCookieAccept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_heading', models.CharField(max_length=255, verbose_name='Title')),
                ('content_text', wagtail.core.fields.RichTextField(verbose_name='Text')),
                ('content_decline_text', models.CharField(max_length=255, verbose_name='Decline Button Label')),
                ('content_accept_text', models.CharField(max_length=255, verbose_name='Accept Button Label')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Reset Network Cookie Accept',
            },
        ),
    ]
