# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_funds', '005_link_text_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundindex',
            name='introduction',
            field=models.TextField(blank=True),
        ),
    ]
