# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_funds', '0006_fundindex_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundpage',
            name='fund_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_public', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='labpage',
            name='lab_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_public', to='wagtailcore.Page'),
        ),
    ]
