# Generated by Django 2.0.2 on 2018-08-03 09:31

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import opentech.public.funds.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('wagtailcore', '0040_page_draft_title'),
        ('public_funds', '0006_fundindex_introduction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FundPageRelatedPage',
            new_name='BaseApplicationRelatedPage',
        ),
        migrations.RenameModel(
            old_name='FundPage',
            new_name='BaseApplicationPage',
        ),

        migrations.RenameField(
            model_name='baseapplicationpage',
            old_name='fund_type',
            new_name='application_type',
        ),
        migrations.AlterField(
            model_name='baseapplicationpage',
            name='application_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_public', to='wagtailcore.Page'),
        ),

        migrations.CreateModel(
            name='FundPage',
            fields=[
                ('baseapplicationpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='public_funds.BaseApplicationPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('public_funds.baseapplicationpage',),
        ),
        migrations.CreateModel(
            name='RFPPage',
            fields=[
                ('baseapplicationpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='public_funds.BaseApplicationPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('public_funds.baseapplicationpage',),
        ),

    ]
