# Generated by Django 2.0.2 on 2018-08-31 20:25

from django.db import migrations, models
import opentech.public.funds.models


class Migration(migrations.Migration):

    dependencies = [
        ('public_funds', '0008_recreate_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labpage',
            name='lab_link',
            field=models.CharField(blank=True, max_length=255, validators=[opentech.public.funds.models.MailToAndURLValidator()], verbose_name='External link'),
        ),
    ]
