# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_funds', '0004_fundpagerelatedpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labpage',
            name='link_text',
            field=models.CharField(blank=True, help_text='Text to display on the button for external links', max_length=255),
        ),
    ]
