# Generated by Django 4.2.9 on 2024-01-10 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0015_remove_newsindex_social_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsindex",
            name="header_image",
        ),
        migrations.RemoveField(
            model_name="newsindex",
            name="listing_image",
        ),
        migrations.RemoveField(
            model_name="newsindex",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="newspage",
            name="header_image",
        ),
        migrations.RemoveField(
            model_name="newspage",
            name="listing_image",
        ),
        migrations.RemoveField(
            model_name="newspage",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="newspageauthor",
            name="author",
        ),
        migrations.RemoveField(
            model_name="newspageauthor",
            name="source_page",
        ),
        migrations.RemoveField(
            model_name="newspagenewstype",
            name="news_type",
        ),
        migrations.RemoveField(
            model_name="newspagenewstype",
            name="page",
        ),
        migrations.RemoveField(
            model_name="newspagerelatedpage",
            name="page",
        ),
        migrations.RemoveField(
            model_name="newspagerelatedpage",
            name="source_page",
        ),
        migrations.RemoveField(
            model_name="newsprojectrelatedpage",
            name="page",
        ),
        migrations.RemoveField(
            model_name="newsprojectrelatedpage",
            name="source_page",
        ),
        migrations.DeleteModel(
            name="NewsFeedSettings",
        ),
        migrations.DeleteModel(
            name="NewsIndex",
        ),
        migrations.DeleteModel(
            name="NewsPage",
        ),
        migrations.DeleteModel(
            name="NewsPageAuthor",
        ),
        migrations.DeleteModel(
            name="NewsPageNewsType",
        ),
        migrations.DeleteModel(
            name="NewsPageRelatedPage",
        ),
        migrations.DeleteModel(
            name="NewsProjectRelatedPage",
        ),
        migrations.DeleteModel(
            name="NewsType",
        ),
    ]
