# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterNavigationSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_label', models.CharField(blank=True, help_text='If you wish to use a label different from the page title please enter it here.', max_length=255)),
                ('order', models.IntegerField(default='100', help_text='Menu entries are displayed in ascending order.')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PrimaryNavigationSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_label', models.CharField(blank=True, help_text='If you wish to use a label different from the page title please enter it here.', max_length=255)),
                ('order', models.IntegerField(default='100', help_text='Menu entries are displayed in ascending order.')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PrimaryNavigationSubmenuSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('menu_label', models.CharField(blank=True, help_text='If you wish to use a label different from the page title please enter it here.', max_length=255)),
                ('order', models.IntegerField(default='100', help_text='Menu entries are displayed in ascending order.')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='navigation.PrimaryNavigationSnippet')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SecondaryNavigationSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_label', models.CharField(blank=True, help_text='If you wish to use a label different from the page title please enter it here.', max_length=255)),
                ('order', models.IntegerField(default='100', help_text='Menu entries are displayed in ascending order.')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
                'ordering': ['order'],
            },
        ),
    ]
