# Generated by Django 2.2.9 on 2020-02-07 11:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetNetworkOpenCallsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content_heading', models.CharField(max_length=255, verbose_name='Heading')),
                ('content_text', models.TextField(blank=True, verbose_name='Text')),
                ('no_open_calls_heading', models.CharField(max_length=255, verbose_name='Heading')),
                ('no_open_calls_text', models.TextField(blank=True, verbose_name='Text')),
                ('no_open_calls_success', models.TextField(verbose_name='Success Message')),
            ],
            options={
                'verbose_name': 'Reset Network Open Calls Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ResetNetworkOpenCallPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content_heading', models.CharField(max_length=255, verbose_name='Heading')),
                ('content_text', wagtail.core.fields.RichTextField(verbose_name='Text')),
                ('card_heading', models.CharField(max_length=100)),
                ('card_text', models.TextField(blank=True)),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Reset Network Open Call Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
