# Generated by Django 2.0.13 on 2019-08-10 09:54

import django.core.files.storage
from django.db import migrations, models
import hypha.apply.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0011_add_packet_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packetfile',
            name='document',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to=hypha.apply.projects.models.document_path),
        ),
    ]
