# Generated by Django 2.0.13 on 2019-08-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0016_add_project_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sent_to_compliance_at',
            field=models.DateTimeField(null=True),
        ),
    ]
