# Generated by Django 2.0.13 on 2019-08-11 06:01

from django.db import migrations, models
import hypha.apply.stream_forms.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0017_add_sent_to_compliance_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectApprovalForm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "form_fields",
                    wagtail.fields.StreamField(
                        [
                            (
                                "text_markup",
                                wagtail.blocks.RichTextBlock(
                                    group="Custom", label="Section text/header"
                                ),
                            ),
                            (
                                "char",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "field_label",
                                            wagtail.blocks.CharBlock(label="Label"),
                                        ),
                                        (
                                            "help_text",
                                            wagtail.blocks.TextBlock(
                                                label="Help text", required=False
                                            ),
                                        ),
                                        (
                                            "required",
                                            wagtail.blocks.BooleanBlock(
                                                label="Required", required=False
                                            ),
                                        ),
                                        (
                                            "format",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("email", "Email"),
                                                    ("url", "URL"),
                                                ],
                                                label="Format",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "default_value",
                                            wagtail.blocks.CharBlock(
                                                label="Default value", required=False
                                            ),
                                        ),
                                    ],
                                    group="Fields",
                                ),
                            ),
                            (
                                "text",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "field_label",
                                            wagtail.blocks.CharBlock(label="Label"),
                                        ),
                                        (
                                            "help_text",
                                            wagtail.blocks.TextBlock(
                                                label="Help text", required=False
                                            ),
                                        ),
                                        (
                                            "required",
                                            wagtail.blocks.BooleanBlock(
                                                label="Required", required=False
                                            ),
                                        ),
                                        (
                                            "default_value",
                                            wagtail.blocks.TextBlock(
                                                label="Default value", required=False
                                            ),
                                        ),
                                    ],
                                    group="Fields",
                                ),
                            ),
                            (
                                "number",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "field_label",
                                            wagtail.blocks.CharBlock(label="Label"),
                                        ),
                                        (
                                            "help_text",
                                            wagtail.blocks.TextBlock(
                                                label="Help text", required=False
                                            ),
                                        ),
                                        (
                                            "required",
                                            wagtail.blocks.BooleanBlock(
                                                label="Required", required=False
                                            ),
                                        ),
                                        (
                                            "default_value",
                                            wagtail.blocks.CharBlock(
                                                label="Default value", required=False
                                            ),
                                        ),
                                    ],
                                    group="Fields",
                                ),
                            ),
                            (
                                "checkbox",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "field_label",
                                            wagtail.blocks.CharBlock(label="Label"),
                                        ),
                                        (
                                            "help_text",
                                            wagtail.blocks.TextBlock(
                                                label="Help text", required=False
                                            ),
                                        ),
                                        (
                                            "required",
                                            wagtail.blocks.BooleanBlock(
                                                label="Required", required=False
                                            ),
                                        ),
                                        (
                                            "default_value",
                                            wagtail.blocks.BooleanBlock(required=False),
                                        ),
                                    ],
                                    group="Fields",
                                ),
                            ),
                            (
                                "radios",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "field_label",
                                            wagtail.blocks.CharBlock(label="Label"),
                                        ),
                                        (
                                            "help_text",
                                            wagtail.blocks.TextBlock(
                                                label="Help text", required=False
                                            ),
                                        ),
                                        (
                                            "required",
                                            wagtail.blocks.BooleanBlock(
                                                label="Required", required=False
                                            ),
                                        ),
                                        (
                                            "choices",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.CharBlock(label="Choice")
                                            ),
                                        ),
                                    ],
                                    group="Fields",
                                ),
                            ),
                            (
                                "dropdown",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "field_label",
                                            wagtail.blocks.CharBlock(label="Label"),
                                        ),
                                        (
                                            "help_text",
                                            wagtail.blocks.TextBlock(
                                                label="Help text", required=False
                                            ),
                                        ),
                                        (
                                            "required",
                                            wagtail.blocks.BooleanBlock(
                                                label="Required", required=False
                                            ),
                                        ),
                                        (
                                            "choices",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.CharBlock(label="Choice")
                                            ),
                                        ),
                                    ],
                                    group="Fields",
                                ),
                            ),
                            (
                                "checkboxes",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "field_label",
                                            wagtail.blocks.CharBlock(label="Label"),
                                        ),
                                        (
                                            "help_text",
                                            wagtail.blocks.TextBlock(
                                                label="Help text", required=False
                                            ),
                                        ),
                                        (
                                            "required",
                                            wagtail.blocks.BooleanBlock(
                                                label="Required", required=False
                                            ),
                                        ),
                                        (
                                            "checkboxes",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.CharBlock(
                                                    label="Checkbox"
                                                )
                                            ),
                                        ),
                                    ],
                                    group="Fields",
                                ),
                            ),
                            (
                                "date",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "field_label",
                                            wagtail.blocks.CharBlock(label="Label"),
                                        ),
                                        (
                                            "help_text",
                                            wagtail.blocks.TextBlock(
                                                label="Help text", required=False
                                            ),
                                        ),
                                        (
                                            "required",
                                            wagtail.blocks.BooleanBlock(
                                                label="Required", required=False
                                            ),
                                        ),
                                        (
                                            "default_value",
                                            wagtail.blocks.DateBlock(required=False),
                                        ),
                                    ],
                                    group="Fields",
                                ),
                            ),
                            (
                                "time",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "field_label",
                                            wagtail.blocks.CharBlock(label="Label"),
                                        ),
                                        (
                                            "help_text",
                                            wagtail.blocks.TextBlock(
                                                label="Help text", required=False
                                            ),
                                        ),
                                        (
                                            "required",
                                            wagtail.blocks.BooleanBlock(
                                                label="Required", required=False
                                            ),
                                        ),
                                        (
                                            "default_value",
                                            wagtail.blocks.TimeBlock(required=False),
                                        ),
                                    ],
                                    group="Fields",
                                ),
                            ),
                            (
                                "datetime",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "field_label",
                                            wagtail.blocks.CharBlock(label="Label"),
                                        ),
                                        (
                                            "help_text",
                                            wagtail.blocks.TextBlock(
                                                label="Help text", required=False
                                            ),
                                        ),
                                        (
                                            "required",
                                            wagtail.blocks.BooleanBlock(
                                                label="Required", required=False
                                            ),
                                        ),
                                        (
                                            "default_value",
                                            wagtail.blocks.DateTimeBlock(
                                                required=False
                                            ),
                                        ),
                                    ],
                                    group="Fields",
                                ),
                            ),
                            (
                                "image",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "field_label",
                                            wagtail.blocks.CharBlock(label="Label"),
                                        ),
                                        (
                                            "help_text",
                                            wagtail.blocks.TextBlock(
                                                label="Help text", required=False
                                            ),
                                        ),
                                        (
                                            "required",
                                            wagtail.blocks.BooleanBlock(
                                                label="Required", required=False
                                            ),
                                        ),
                                    ],
                                    group="Fields",
                                ),
                            ),
                            (
                                "file",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "field_label",
                                            wagtail.blocks.CharBlock(label="Label"),
                                        ),
                                        (
                                            "help_text",
                                            wagtail.blocks.TextBlock(
                                                label="Help text", required=False
                                            ),
                                        ),
                                        (
                                            "required",
                                            wagtail.blocks.BooleanBlock(
                                                label="Required", required=False
                                            ),
                                        ),
                                    ],
                                    group="Fields",
                                ),
                            ),
                            (
                                "multi_file",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "field_label",
                                            wagtail.blocks.CharBlock(label="Label"),
                                        ),
                                        (
                                            "help_text",
                                            wagtail.blocks.TextBlock(
                                                label="Help text", required=False
                                            ),
                                        ),
                                        (
                                            "required",
                                            wagtail.blocks.BooleanBlock(
                                                label="Required", required=False
                                            ),
                                        ),
                                    ],
                                    group="Fields",
                                ),
                            ),
                            (
                                "group_toggle",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "field_label",
                                            wagtail.blocks.CharBlock(label="Label"),
                                        ),
                                        (
                                            "help_text",
                                            wagtail.blocks.TextBlock(
                                                label="Help text", required=False
                                            ),
                                        ),
                                        (
                                            "required",
                                            wagtail.blocks.BooleanBlock(
                                                default=True, label="Required"
                                            ),
                                        ),
                                        (
                                            "choices",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.CharBlock(
                                                    label="Choice"
                                                ),
                                                help_text="Please create only two choices for toggle. First choice will revel the group and the second hide it. Additional choices will be ignored.",
                                            ),
                                        ),
                                    ],
                                    group="Custom",
                                ),
                            ),
                            (
                                "group_toggle_end",
                                hypha.apply.stream_forms.blocks.GroupToggleEndBlock(
                                    group="Custom"
                                ),
                            ),
                        ]
                    ),
                ),
            ],
        ),
    ]
