# Generated by Django 2.1.11 on 2019-09-05 08:48

import django.core.files.storage
from django.db import migrations, models
import opentech.apply.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0022_update_field_definitions_for_forms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to=opentech.apply.projects.models.contract_path),
        ),
    ]
