# Generated by Django 2.1.11 on 2019-09-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0023_ensure_contracts_uses_private_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
