# Generated by Django 2.1.11 on 2019-10-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0029_report_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
    ]
