# Generated by Django 2.2.23 on 2021-06-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0036_add_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorformsettings',
            name='account_currency',
        ),
        migrations.AddField(
            model_name='vendorformsettings',
            name='account_currency_label',
            field=models.TextField(default='Bank Account Currency', verbose_name='label'),
        ),
    ]
