# Generated by Django 2.2.24 on 2021-09-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0037_add_project_invoicing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="message_for_pm",
            field=models.TextField(blank=True, verbose_name="Message"),
        ),
    ]
