# Generated by Django 2.2.24 on 2021-06-18 06:27

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0037_rename_verbose_name_of_vendor_form_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorformsettings',
            name='account_currency_help_text',
            field=wagtail.core.fields.RichTextField(blank=True, default='This is the currency of this bank account.', verbose_name='help text'),
        ),
    ]
