# Generated by Django 2.2.24 on 2021-09-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0037_add_project_invoicing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.TextField(choices=[('submitted', 'Submitted'), ('changes_requested', 'Changes Requested'), ('under_review', 'Under Review'), ('paid', 'Paid'), ('declined', 'Declined'), ('approve_finance_level_1', 'Approve Finance Level 1'), ('approve_finance_level_2', 'Approve Finance Level 2')], default='submitted'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.TextField(choices=[('submitted', 'Submitted'), ('changes_requested', 'Changes Requested'), ('under_review', 'Under Review'), ('paid', 'Paid'), ('declined', 'Declined'), ('approve_finance_level_1', 'Approve Finance Level 1'), ('approve_finance_level_2', 'Approve Finance Level 2')], default='submitted'),
        ),
    ]
