# Generated by Django 2.2.24 on 2021-09-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0039_auto_20210915_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deliverables',
            field=models.ManyToManyField(related_name='invoices', to='application_projects.Deliverable'),
        ),
    ]
