# Generated by Django 2.2.24 on 2021-09-30 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0039_add_deliverables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverable',
            name='invoice_quantity',
        ),
    ]
