# Generated by Django 2.2.24 on 2021-10-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0089_auto_20211028_1426'),
        ('application_projects', '0040_remove_deliverable_invoice_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectApprovalForm',
        ),
    ]
