# Generated by Django 2.2.24 on 2021-09-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0040_invoice_deliverables'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='invoice_quantity',
            field=models.IntegerField(default=1, help_text='Quantity Selected on an Invoice'),
            preserve_default=False,
        ),
    ]
