# Generated by Django 2.2.24 on 2021-07-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0040_add_created_and_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='user_has_updated_details',
            field=models.BooleanField(default=False),
        ),
    ]
