# Generated by Django 2.2.24 on 2021-11-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0041_payment_requests_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_projectid',
            field=models.CharField(blank=True, help_text='ID of this project at integrated payment service.', max_length=30),
        ),
    ]
