# Generated by Django 2.2.24 on 2021-10-27 10:48

from django.db import migrations
from django.contrib.contenttypes.models import ContentType

def remove_payment_request_activities(apps, schema_editor):
    activities = apps.get_model('activity', 'activity')
    activities.objects.filter(related_content_type__model='paymentrequest').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0041_payment_requests_cleanup'),
    ]

    operations = [
        migrations.RunPython(remove_payment_request_activities),
    ]
