# Generated by Django 2.2.24 on 2021-11-22 07:11

from django.db import migrations


def migrate_label_and_relations(apps, schema_editor):
    ProjectApprovalForm = apps.get_model("application_projects", "ProjectApprovalForm")
    ProjectApprovalForm.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0041_payment_requests_cleanup"),
    ]

    operations = [
        migrations.RunPython(migrate_label_and_relations, migrations.RunPython.noop)
    ]
