# Generated by Django 2.2.24 on 2021-11-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0042_delete_project_approval_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectApprovalForm',
        ),
    ]
