# Generated by Django 2.2.24 on 2021-11-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0042_add_external_project_id_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID of this deliverable at integrated payment service.', max_length=30),
        ),
    ]
