# Generated by Django 2.2.24 on 2021-12-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0044_add_resubmitted_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID of this deliverable at integrated payment service.', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='external_projectid',
            field=models.CharField(blank=True, help_text='ID of this project at integrated payment service.', max_length=30),
        ),
    ]
