# Generated by Django 2.2.24 on 2021-12-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0044_add_resubmitted_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.TextField(choices=[('submitted', 'Submitted'), ('changes_requested', 'Changes Requested By PM'), ('changes_requested_by_finance1', 'Changes Requested By Finance1'), ('changes_requested_by_finance2', 'Changes Requested By Finance2'), ('approved_by_staff', 'Approved by staff'), ('approved_by_finance1', 'Approved By Finance 1'), ('approved_by_finance2', 'Approved By Finance 2'), ('Resubmitted', 'Resubmitted'), ('paid', 'Paid'), ('declined', 'Declined')], default='submitted'),
        ),
    ]
