# Generated by Django 2.2.26 on 2022-01-26 17:22

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0044_add_resubmitted_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=django_fsm.FSMField(choices=[('submitted', 'Submitted'), ('resubmitted', 'Resubmitted'), ('changes_requested_pm', 'Changes Requested by PM'), ('changes_requested_finance_1', 'Changes Requested by Finance 1'), ('changes_requested_finance_2', 'Changes Requested by Finance 2'), ('approved_by_pm', 'Approved by PM'), ('approved_by_finance_1', 'Approved by Finance 1'), ('approved_by_finance_2', 'Approved by Finance 2'), ('paid', 'Paid'), ('declined', 'Declined')], default='submitted', max_length=50),
        ),
    ]
