# Generated by Django 3.1 on 2022-01-11 13:14

from django.db import migrations, models
import hypha.apply.stream_forms.files


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0044_add_resubmitted_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='form_data',
            field=models.JSONField(default=dict, encoder=hypha.apply.stream_forms.files.StreamFieldDataEncoder),
        ),
    ]
