# Generated by Django 3.2.12 on 2022-02-21 12:36

from django.db import migrations, models
import hypha.apply.stream_forms.files


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0046_add_required_checks_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="form_data",
            field=models.JSONField(
                default=dict,
                encoder=hypha.apply.stream_forms.files.StreamFieldDataEncoder,
            ),
        ),
    ]
