# Generated by Django 2.2.26 on 2022-02-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0046_add_required_checks_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID of this deliverable at integrated payment service.', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='external_projectid',
            field=models.CharField(blank=True, help_text='ID of this project at integrated payment service.', max_length=30),
        ),
    ]
