# Generated by Django 3.2.12 on 2022-03-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0047_alter_project_form_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="value",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
