# Generated by Django 3.2.12 on 2022-04-12 05:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0050_add_new_invoice_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="date_from",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="date_to",
        ),
    ]
