# Generated by Django 3.2.13 on 2022-05-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0051_remove_unnecessary_fields_from_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconfig',
            name='frequency',
            field=models.CharField(blank=True, choices=[('', '---'), ('week', 'Weeks'), ('month', 'Months'), ('year', 'Years')], default='', max_length=5),
        ),
    ]
