# Generated by Django 3.2.13 on 2022-07-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0054_paf_reviewers_roles__alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='paf_reviews_meta_data',
            field=models.JSONField(default=dict, help_text='Reviewers role and their actions/comments'),
        ),
    ]
