# Generated by Django 3.2.16 on 2022-12-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0056_packetfile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconfig',
            name='frequency',
            field=models.CharField(blank=True, choices=[('', '---'), ('one_time', 'One Time'), ('week', 'Weeks'), ('month', 'Months'), ('year', 'Years')], default='month', max_length=10),
        ),
    ]
