# Generated by Django 3.2.16 on 2023-01-31 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0057_alter_report_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='valid_checks',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='valid_checks_link',
        ),
    ]
