# Generated by Django 3.2.16 on 2023-01-10 07:07

from django.db import migrations


def set_value_to_ready_for_final_approval(apps, schema_editor):
    from hypha.apply.projects.models.project import Project, WAITING_FOR_APPROVAL

    for project in Project.objects.filter(status=WAITING_FOR_APPROVAL):
        if project.can_make_final_approval:
            project.ready_for_final_approval = True
            project.save(update_fields={'ready_for_final_approval'})


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0057_project_ready_for_final_approval'),
    ]

    operations = [
        migrations.RunPython(set_value_to_ready_for_final_approval)
    ]
