# Generated by Django 3.2.16 on 2023-01-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0059_set_ready_for_final_approval"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectsettings",
            name="compliance_email",
        ),
        migrations.AddField(
            model_name="projectsettings",
            name="contracting_gp_email",
            field=models.TextField(
                blank=True, null=True, verbose_name="Contracting Group Email"
            ),
        ),
        migrations.AddField(
            model_name="projectsettings",
            name="finance_gp_email",
            field=models.TextField(
                blank=True, null=True, verbose_name="Finance Group Email"
            ),
        ),
        migrations.AddField(
            model_name="projectsettings",
            name="staff_gp_email",
            field=models.TextField(
                blank=True, null=True, verbose_name="Staff Group Email"
            ),
        ),
    ]
