# Generated by Django 3.2.17 on 2023-02-14 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0060_auto_20230116_0712"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="valid_checks",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="valid_checks_link",
        ),
    ]
