# Generated by Django 3.2.18 on 2023-02-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('application_projects', '0061_remove_checks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pafreviewersrole',
            old_name='role',
            new_name='label',
        ),
        migrations.AddField(
            model_name='pafreviewersrole',
            name='user_roles',
            field=models.ManyToManyField(help_text="Only selected group's users will be listed for this PAFReviewerRole", related_name='paf_reviewers_roles', to='auth.Group', verbose_name='user groups'),
        ),
    ]
