# Generated by Django 3.2.18 on 2023-02-23 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application_projects', '0062_auto_20230223_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAFApprovals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('paf_reviewer_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paf_approvals', to='application_projects.pafreviewersrole')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paf_approvals', to='application_projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paf_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'paf_reviewer_role')},
            },
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
    ]
