# Generated by Django 3.2.18 on 2023-03-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0062_auto_20230228_1218"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsettings",
            name="paf_approval_sequential",
            field=models.BooleanField(
                default=True, help_text="Uncheck it to approve PAF parallely"
            ),
        ),
    ]
