# Generated by Django 3.2.18 on 2023-05-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0072_pafapprovals_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractdocumentcategory',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contractdocumentcategory',
            name='recommended_minimum',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='recommended_minimum',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
