# Generated by Django 3.2.19 on 2023-05-23 05:51

import django.core.files.storage
from django.db import migrations, models
import hypha.apply.projects.models.project


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0075_auto_20230503_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='template',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=hypha.apply.projects.models.project.document_template_path),
        ),
    ]
