# Generated by Django 3.2.19 on 2023-05-25 04:41

import django.core.files.storage
from django.db import migrations, models
import hypha.apply.projects.models.project


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0076_documentcategory_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractdocumentcategory',
            options={'ordering': ('-required', 'name'), 'verbose_name_plural': 'Contract Document Categories'},
        ),
        migrations.AddField(
            model_name='contractdocumentcategory',
            name='template',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=hypha.apply.projects.models.project.contract_document_template_path),
        ),
    ]
