# Generated by Django 3.2.19 on 2023-05-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0077_auto_20230525_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdocumentcategory',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
