# Generated by Django 3.2.20 on 2023-09-19 06:23

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0079_alter_invoice_add_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("submitted", "Submitted"),
                    ("resubmitted", "Resubmitted"),
                    ("changes_requested_staff", "Changes requested by staff"),
                    ("changes_requested_finance_1", "Changes requested by finance"),
                    ("approved_by_staff", "Approved by staff"),
                    ("approved_by_finance_1", "Approved by finance"),
                    ("paid", "Paid"),
                    ("payment_failed", "Payment failed"),
                    ("declined", "Declined"),
                ],
                default="submitted",
                max_length=50,
            ),
        ),
    ]
