# Generated by Django 4.2.8 on 2023-12-11 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0080_alter_invoice_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(limit_value=0)],
            ),
        ),
    ]
