# Generated by Django 4.2.11 on 2024-05-07 06:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0115_list_on_front_page"),
        ("application_projects", "0081_alter_project_value"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProjectApprovalForm",
            new_name="ProjectForm",
        ),
        migrations.AlterModelTable(
            name="projectform",
            table="project_form",
        ),
        migrations.AlterModelTable(
            name="projectsowform",
            table="project_sow_form",
        ),
    ]
