# Generated by Django 4.2.11 on 2024-05-07 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0118_labbaseprojectreportform_and_more"),
        ("application_projects", "0082_projectreportform_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProjectApprovalForm",
            new_name="ProjectForm",
        ),
        migrations.AlterModelTable(
            name="projectform",
            table="project_form",
        ),
        migrations.AlterModelTable(
            name="projectsowform",
            table="project_sow_form",
        ),
    ]
