# Generated by Django 4.2.11 on 2024-05-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "application_projects",
            "0083_rename_projectapprovalform_projectform_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="signed_and_approved",
            field=models.BooleanField(
                default=False, verbose_name="Signed and approved"
            ),
        ),
    ]
