# Generated by Django 4.2.11 on 2024-06-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0084_contract_signed_and_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectsettings",
            name="paf_approval_sequential",
            field=models.BooleanField(
                default=True, help_text="Uncheck it to approve project parallely"
            ),
        ),
    ]
