# Generated by Django 4.2.11 on 2024-05-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0084_contract_signed_and_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsettings",
            name="staff_upload_contract",
            field=models.BooleanField(
                default=False,
                help_text="Check to allow the Staff role to upload contracts.",
            ),
        ),
    ]
