# Generated by Django 4.2.11 on 2024-06-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0085_alter_projectsettings_paf_approval_sequential"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_date",
            field=models.DateTimeField(null=True, verbose_name="Invoice date"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="paid_date",
            field=models.DateTimeField(null=True, verbose_name="Paid date"),
        ),
    ]
