# Generated by Django 4.2.16 on 2024-09-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0085_invoice_invoice_date_invoice_paid_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_date",
            field=models.DateField(null=True, verbose_name="Invoice date"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="paid_date",
            field=models.DateField(null=True, verbose_name="Paid date"),
        ),
    ]
