# Generated by Django 4.2.11 on 2024-08-21 13:01

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("application_projects", "0086_invoice_invoice_date_invoice_paid_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pafreviewersrole",
            name="user_roles",
            field=modelcluster.fields.ParentalManyToManyField(
                help_text="Only selected group's users will be listed for this ProjectFormReviewerRole",
                related_name="paf_reviewers_roles",
                to="auth.group",
                verbose_name="user groups",
            ),
        ),
    ]
