# Generated by Django 4.2.11 on 2024-08-12 11:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0087_alter_pafreviewersrole_user_roles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="duediligencedocument",
            name="vendor",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="bank_info",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="user",
        ),
        migrations.RemoveField(
            model_name="vendorformsettings",
            name="site",
        ),
        migrations.RemoveField(
            model_name="project",
            name="vendor",
        ),
        migrations.RemoveField(
            model_name="projectsettings",
            name="vendor_setup_required",
        ),
        migrations.DeleteModel(
            name="BankInformation",
        ),
        migrations.DeleteModel(
            name="DueDiligenceDocument",
        ),
        migrations.DeleteModel(
            name="Vendor",
        ),
        migrations.DeleteModel(
            name="VendorFormSettings",
        ),
    ]
