# Generated by Django 4.2.15 on 2024-09-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("application_projects", "0087_alter_pafreviewersrole_user_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractdocumentcategory",
            name="restrict_document_access_view",
            field=models.ManyToManyField(
                blank=True,
                help_text="Only selected group's users will be restricted from document access",
                related_name="contract_document_category",
                to="auth.group",
                verbose_name="Restrict document access for groups",
            ),
        ),
    ]
