# Generated by Django 4.2.16 on 2024-10-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("application_projects", "0088_remove_duediligencedocument_vendor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractdocumentcategory",
            name="document_access_view",
            field=models.ManyToManyField(
                blank=True,
                help_text="Only selected group's users can access the document",
                limit_choices_to={
                    "name__in": ["Staff", "Staff Admin", "Finance", "Contracting"]
                },
                related_name="contract_document_category",
                to="auth.group",
                verbose_name="Allow document access for groups",
            ),
        ),
    ]
