# Generated by Django 4.2.16 on 2024-10-18 14:30

from django.db import migrations
from hypha.apply.users.groups import GROUPS_ORG_FACULTY


def allow_internal_groups_to_contractdocumentcategory(apps, schema_editor):
    ContractDocumentCategory = apps.get_model(
        "application_projects", "ContractDocumentCategory"
    )
    Group = apps.get_model("auth", "Group")

    groups = Group.objects.filter(name__in=GROUPS_ORG_FACULTY)
    for category in ContractDocumentCategory.objects.all():
        # Add the default groups to the document_access_view field
        category.document_access_view.add(*groups)


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0089_contractdocumentcategory_document_access_view"),
    ]

    operations = [
        migrations.RunPython(allow_internal_groups_to_contractdocumentcategory)
    ]
