# Generated by Django 4.2.16 on 2024-11-19 04:29

from django.db import migrations


def migrate_reportversion_formfields_to_report_formfields(apps, schema_editor):
    Report = apps.get_model("application_projects", "Report")
    for report in Report.objects.filter(current__isnull=False):
        if report.current.form_fields is not None:
            report.form_fields = report.current.form_fields
            report.form_data = report.current.form_data
            report.save()


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0091_report_form_data_report_form_fields"),
    ]

    operations = [
        migrations.RunPython(migrate_reportversion_formfields_to_report_formfields)
    ]
