# Generated by Django 4.2.16 on 2024-11-19 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "application_projects",
            "0092_migrate_reportversion_streamform_to_report_streamform",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportversion",
            name="form_fields",
        ),
    ]
