# Generated by Django 4.2.16 on 2024-12-06 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0093_remove_reportversion_form_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="user_has_updated_details",
        ),
    ]
