# Generated by Django 4.2.16 on 2024-12-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0094_remove_project_user_has_updated_pf_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportconfig",
            name="disable_reporting",
            field=models.BooleanField(default=True),
        ),
    ]
