# Generated by Django 4.2.17 on 2024-12-16 22:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0095_alter_reportconfig_disable_reporting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoicedeliverable",
            name="deliverable",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="deliverables",
        ),
        migrations.DeleteModel(
            name="Deliverable",
        ),
        migrations.DeleteModel(
            name="InvoiceDeliverable",
        ),
    ]
