# Generated by Django 4.2.20 on 2025-04-08 19:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0099_remove_reportconfig_project_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="proposed_end",
        ),
        migrations.RemoveField(
            model_name="project",
            name="proposed_start",
        ),
    ]
