# Generated by Django 4.2.20 on 2025-04-10 17:27

import datetime
from django.db import migrations, models


def migration_set_project_start_date(apps, schema_editor):
    Project = apps.get_model("application_projects", "Project")
    for project in Project.objects.all():
        if not project.proposed_start:
            project.proposed_start = project.created_at
            project.save(update_fields=["proposed_start"])


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0099_remove_reportconfig_project_and_more"),
    ]

    operations = [
        migrations.RunPython(migration_set_project_start_date),
        migrations.AlterField(
            model_name="project",
            name="proposed_end",
            field=models.DateField(null=True, verbose_name="Proposed end date"),
        ),
        migrations.AlterField(
            model_name="project",
            name="proposed_start",
            field=models.DateField(
                default=datetime.date.today,
                null=True,
                verbose_name="Proposed start date",
            ),
        ),
    ]
