# Generated by Django 4.2.21 on 2025-06-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0101_alter_invoice_message_for_pm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("resubmitted", "Resubmitted"),
                    ("changes_requested_staff", "Changes requested by staff"),
                    ("changes_requested_finance_1", "Changes requested by finance"),
                    ("approved_by_staff", "Approved by staff"),
                    ("approved_by_finance_1", "Approved by finance"),
                    ("paid", "Paid"),
                    ("payment_failed", "Payment failed"),
                    ("declined", "Declined"),
                ],
                default="submitted",
                max_length=30,
            ),
        ),
    ]
