# Generated by Django 5.2.11 on 2026-03-03 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0102_alter_invoice_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contract",
            options={"verbose_name": "contract", "verbose_name_plural": "contracts"},
        ),
        migrations.AlterModelOptions(
            name="contractdocumentcategory",
            options={
                "ordering": ("-required", "name"),
                "verbose_name": "Contrat Document Category",
                "verbose_name_plural": "Contract Document Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="contractpacketfile",
            options={
                "verbose_name": "contract packet file",
                "verbose_name_plural": "contract packet files",
            },
        ),
        migrations.AlterModelOptions(
            name="documentcategory",
            options={
                "ordering": ("-required", "name"),
                "verbose_name": "Document Category",
                "verbose_name_plural": "Project Document Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="invoice",
            options={"verbose_name": "invoice", "verbose_name_plural": "invoices"},
        ),
        migrations.AlterModelOptions(
            name="packetfile",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "packet files",
                "verbose_name_plural": "packet files",
            },
        ),
        migrations.AlterModelOptions(
            name="pafapprovals",
            options={
                "ordering": ["paf_reviewer_role__sort_order"],
                "verbose_name": "PAF approval",
                "verbose_name_plural": "PAF approvals",
            },
        ),
        migrations.AlterModelOptions(
            name="pafreviewersrole",
            options={
                "verbose_name": "PAF reviewers role",
                "verbose_name_plural": "PAF reviewers roles",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "project", "verbose_name_plural": "projects"},
        ),
        migrations.AlterModelOptions(
            name="projectform",
            options={
                "verbose_name": "project form",
                "verbose_name_plural": "project forms",
            },
        ),
        migrations.AlterModelOptions(
            name="projectreminderfrequency",
            options={
                "verbose_name": "project reminder frequency",
                "verbose_name_plural": "project reminder frequencies",
            },
        ),
        migrations.AlterModelOptions(
            name="projectreportform",
            options={
                "verbose_name": "project report form",
                "verbose_name_plural": "project report forms",
            },
        ),
        migrations.AlterModelOptions(
            name="projectsettings",
            options={"verbose_name": "project settings"},
        ),
        migrations.AlterModelOptions(
            name="projectsow",
            options={
                "verbose_name": "project SOW",
                "verbose_name_plural": "project SOW",
            },
        ),
        migrations.AlterModelOptions(
            name="projectsowform",
            options={
                "verbose_name": "project SOW form",
                "verbose_name_plural": "project SOW forms",
            },
        ),
        migrations.AlterModelOptions(
            name="supportingdocument",
            options={
                "verbose_name": "supporting document",
                "verbose_name_plural": "supporting documents",
            },
        ),
    ]
