# Generated by Django 5.2.12 on 2026-03-31 09:50

import datetime
import django.core.files.storage
import django.core.validators
import hypha.apply.projects.models.payment
import hypha.apply.projects.models.project
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0103_alter_contract_options_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=hypha.apply.projects.models.project.contract_path,
                verbose_name="file",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="signed_and_approved",
            field=models.BooleanField(
                default=False, verbose_name="signed and approved"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="signed_by_applicant",
            field=models.BooleanField(default=False, verbose_name="counter signed?"),
        ),
        migrations.AlterField(
            model_name="contractdocumentcategory",
            name="document_access_view",
            field=models.ManyToManyField(
                blank=True,
                help_text="Only selected group's users can access the document",
                limit_choices_to={
                    "name__in": ["Staff", "Staff Admin", "Finance", "Contracting"]
                },
                related_name="contract_document_category",
                to="auth.group",
                verbose_name="allow document access for groups",
            ),
        ),
        migrations.AlterField(
            model_name="contractdocumentcategory",
            name="name",
            field=models.CharField(max_length=254, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="contractdocumentcategory",
            name="recommended_minimum",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="recommended minimum"
            ),
        ),
        migrations.AlterField(
            model_name="contractdocumentcategory",
            name="required",
            field=models.BooleanField(default=True, verbose_name="required"),
        ),
        migrations.AlterField(
            model_name="contractdocumentcategory",
            name="template",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=hypha.apply.projects.models.project.contract_document_template_path,
                verbose_name="template",
            ),
        ),
        migrations.AlterField(
            model_name="contractpacketfile",
            name="document",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=hypha.apply.projects.models.project.contract_document_path,
                verbose_name="document",
            ),
        ),
        migrations.AlterField(
            model_name="contractpacketfile",
            name="title",
            field=models.TextField(verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="documentcategory",
            name="name",
            field=models.CharField(max_length=254, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="documentcategory",
            name="recommended_minimum",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="recommended minimum"
            ),
        ),
        migrations.AlterField(
            model_name="documentcategory",
            name="required",
            field=models.BooleanField(default=False, verbose_name="required"),
        ),
        migrations.AlterField(
            model_name="documentcategory",
            name="template",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=hypha.apply.projects.models.project.document_template_path,
                verbose_name="template",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="comment",
            field=models.TextField(blank=True, verbose_name="comment"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="document",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=hypha.apply.projects.models.payment.invoice_path,
                verbose_name="document",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="invoice amount",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_date",
            field=models.DateField(null=True, verbose_name="invoice date"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                max_length=50, null=True, verbose_name="invoice number"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="message_for_pm",
            field=models.TextField(
                blank=True,
                help_text="This will be displayed as a comment in the comments tab",
                verbose_name="comment",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="paid_date",
            field=models.DateField(null=True, verbose_name="paid date"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="paid_value",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="paid value",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("resubmitted", "Resubmitted"),
                    ("changes_requested_staff", "Changes requested by staff"),
                    ("changes_requested_finance_1", "Changes requested by finance"),
                    ("approved_by_staff", "Approved by staff"),
                    ("approved_by_finance_1", "Approved by finance"),
                    ("paid", "Paid"),
                    ("payment_failed", "Payment failed"),
                    ("declined", "Declined"),
                ],
                default="submitted",
                max_length=30,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="packetfile",
            name="document",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=hypha.apply.projects.models.project.document_path,
                verbose_name="document",
            ),
        ),
        migrations.AlterField(
            model_name="packetfile",
            name="title",
            field=models.TextField(verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_locked",
            field=models.BooleanField(default=False, verbose_name="locked"),
        ),
        migrations.AlterField(
            model_name="project",
            name="proposed_end",
            field=models.DateField(null=True, verbose_name="proposed end date"),
        ),
        migrations.AlterField(
            model_name="project",
            name="proposed_start",
            field=models.DateField(
                default=datetime.date.today,
                null=True,
                verbose_name="proposed start date",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.TextField(
                choices=[
                    ("draft", "Draft"),
                    ("internal_approval", "Internal approval"),
                    ("contracting", "Contracting"),
                    ("invoicing_and_reporting", "Invoicing and reporting"),
                    ("closing", "Closing"),
                    ("complete", "Complete"),
                ],
                default="draft",
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="submitted_contract_documents",
            field=models.BooleanField(
                default=False, verbose_name="submit contracting documents"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.TextField(verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="project",
            name="value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(limit_value=0)],
                verbose_name="value",
            ),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="contracting_gp_email",
            field=models.TextField(
                blank=True, null=True, verbose_name="contracting group email"
            ),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="finance_gp_email",
            field=models.TextField(
                blank=True, null=True, verbose_name="finance group email"
            ),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="staff_gp_email",
            field=models.TextField(
                blank=True, null=True, verbose_name="staff group email"
            ),
        ),
        migrations.AlterField(
            model_name="supportingdocument",
            name="document",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="supporting_documents",
                verbose_name="document",
            ),
        ),
    ]
