# Generated by Django 5.2.15 on 2026-06-09 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0103_alter_contract_options_and_more"),
        ("funds", "0135_alter_applicationsubmission_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ("pk",),
                "verbose_name": "project",
                "verbose_name_plural": "projects",
            },
        ),
        migrations.AlterField(
            model_name="project",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="funds.applicationsubmission",
            ),
        ),
    ]
