# Generated by Django 5.2.15 on 2026-06-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0103_alter_contract_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "invoice tag",
                "verbose_name_plural": "invoice tags",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="invoices",
                to="application_projects.invoicetag",
                verbose_name="tags",
            ),
        ),
    ]
