# Generated by Django 5.2.15 on 2026-06-13 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0104_invoice_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceExportManager",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("export_data", models.TextField()),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("completed_time", models.DateTimeField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("error", "Failed"),
                            ("success", "Success"),
                            ("generating", "In Progress"),
                        ],
                        default="generating",
                    ),
                ),
                ("total_export", models.IntegerField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "invoice export manager",
                "verbose_name_plural": "invoice export managers",
            },
        ),
    ]
