# Generated by Django 5.2.15 on 2026-07-21 17:15

from django.db import migrations


def create_pf_pointers(apps, schema_editor):
    ProjectFormPointer = apps.get_model("application_projects", "ProjectFormPointer")
    all_projects = apps.get_model("application_projects", "Project").objects.all()
    for project in all_projects:
        if bool(project.form_fields):
            ProjectFormPointer.objects.create(project=project)


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0104_projectformpointer"),
    ]

    operations = [
        migrations.RunPython(create_pf_pointers),
    ]
