# Generated by Django 5.2.16 on 2026-07-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0105_alter_project_options_alter_project_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contract_number",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="contract number"
            ),
        ),
    ]
