# Generated by Django 5.2.15 on 2026-07-21 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0107_invoiceexportmanager"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectFormPointer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pfp",
                        to="application_projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "project form",
                "verbose_name_plural": "project forms",
            },
        ),
    ]
