# Generated by Django 5.2.17 on 2026-09-10 11:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0109_create_project_form_pointers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="form_fields",
            field=wagtail.fields.StreamField(
                [
                    ("text_markup", 0),
                    ("header_markup", 3),
                    ("char", 10),
                    ("multi_inputs_char", 13),
                    ("text", 16),
                    ("number", 17),
                    ("checkbox", 19),
                    ("radios", 22),
                    ("dropdown", 22),
                    ("checkboxes", 25),
                    ("date", 27),
                    ("time", 29),
                    ("datetime", 31),
                    ("image", 32),
                    ("file", 32),
                    ("multi_file", 32),
                    ("group_toggle", 35),
                    ("group_toggle_end", 36),
                    ("rich_text", 16),
                    ("markdown_text", 16),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"group": "Custom", "label": "Paragraph"},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("h2", "H2"), ("h3", "H3"), ("h4", "H4")]},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 1), ("size", 2)]],
                        {"group": "Custom", "label": "Section header"},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Label"}),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Help text", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Required", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Tick this if the answer will contain personally identifiable information, such as a name, address, phone number or date of birth. Only the applicant, their co-applicants and staff will be able to see the answer. Reviewers and other users will see that the question was asked, but not the answer.",
                            "label": "Personal information",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("email", "Email"), ("url", "URL")],
                            "label": "Format",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Default value", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("format", 8),
                                ("default_value", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    11: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 2, "label": "Max number of inputs"},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Add new item", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("format", 8),
                                ("default_value", 9),
                                ("number_of_inputs", 11),
                                ("add_button_text", 12),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    14: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Default value", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 1000, "label": "Word limit"},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 14),
                                ("word_limit", 15),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    18: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 18),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    20: ("wagtail.blocks.CharBlock", (), {"label": "Choice"}),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("choices", 21),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    23: ("wagtail.blocks.CharBlock", (), {"label": "Checkbox"}),
                    24: ("wagtail.blocks.ListBlock", (23,), {}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("checkboxes", 24),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    26: ("wagtail.blocks.DateBlock", (), {"required": False}),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 26),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    28: ("wagtail.blocks.TimeBlock", (), {"required": False}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 28),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    30: ("wagtail.blocks.DateTimeBlock", (), {"required": False}),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 30),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    33: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "label": "Required", "required": False},
                    ),
                    34: (
                        "wagtail.blocks.ListBlock",
                        (20,),
                        {
                            "help_text": "Please create only two choices for toggle. First choice will revel the group and the second hide it. Additional choices will be ignored."
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 33),
                                ("choices", 34),
                            ]
                        ],
                        {"group": "Custom"},
                    ),
                    36: (
                        "hypha.apply.stream_forms.blocks.GroupToggleEndBlock",
                        (),
                        {"group": "Custom"},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectform",
            name="form_fields",
            field=wagtail.fields.StreamField(
                [
                    ("text_markup", 0),
                    ("header_markup", 3),
                    ("char", 10),
                    ("multi_inputs_char", 13),
                    ("text", 16),
                    ("number", 17),
                    ("checkbox", 19),
                    ("radios", 22),
                    ("dropdown", 22),
                    ("checkboxes", 25),
                    ("date", 27),
                    ("time", 29),
                    ("datetime", 31),
                    ("image", 32),
                    ("file", 32),
                    ("multi_file", 32),
                    ("group_toggle", 35),
                    ("group_toggle_end", 36),
                    ("rich_text", 16),
                    ("markdown_text", 16),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"group": "Custom", "label": "Paragraph"},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("h2", "H2"), ("h3", "H3"), ("h4", "H4")]},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 1), ("size", 2)]],
                        {"group": "Custom", "label": "Section header"},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Label"}),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Help text", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Required", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Tick this if the answer will contain personally identifiable information, such as a name, address, phone number or date of birth. Only the applicant, their co-applicants and staff will be able to see the answer. Reviewers and other users will see that the question was asked, but not the answer.",
                            "label": "Personal information",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("email", "Email"), ("url", "URL")],
                            "label": "Format",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Default value", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("format", 8),
                                ("default_value", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    11: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 2, "label": "Max number of inputs"},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Add new item", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("format", 8),
                                ("default_value", 9),
                                ("number_of_inputs", 11),
                                ("add_button_text", 12),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    14: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Default value", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 1000, "label": "Word limit"},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 14),
                                ("word_limit", 15),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    18: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 18),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    20: ("wagtail.blocks.CharBlock", (), {"label": "Choice"}),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("choices", 21),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    23: ("wagtail.blocks.CharBlock", (), {"label": "Checkbox"}),
                    24: ("wagtail.blocks.ListBlock", (23,), {}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("checkboxes", 24),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    26: ("wagtail.blocks.DateBlock", (), {"required": False}),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 26),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    28: ("wagtail.blocks.TimeBlock", (), {"required": False}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 28),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    30: ("wagtail.blocks.DateTimeBlock", (), {"required": False}),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 30),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    33: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "label": "Required", "required": False},
                    ),
                    34: (
                        "wagtail.blocks.ListBlock",
                        (20,),
                        {
                            "help_text": "Please create only two choices for toggle. First choice will revel the group and the second hide it. Additional choices will be ignored."
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 33),
                                ("choices", 34),
                            ]
                        ],
                        {"group": "Custom"},
                    ),
                    36: (
                        "hypha.apply.stream_forms.blocks.GroupToggleEndBlock",
                        (),
                        {"group": "Custom"},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="projectreportform",
            name="form_fields",
            field=wagtail.fields.StreamField(
                [
                    ("text_markup", 0),
                    ("header_markup", 3),
                    ("char", 10),
                    ("multi_inputs_char", 13),
                    ("text", 16),
                    ("number", 17),
                    ("checkbox", 19),
                    ("radios", 22),
                    ("dropdown", 22),
                    ("checkboxes", 25),
                    ("date", 27),
                    ("time", 29),
                    ("datetime", 31),
                    ("image", 32),
                    ("file", 32),
                    ("multi_file", 32),
                    ("group_toggle", 35),
                    ("group_toggle_end", 36),
                    ("rich_text", 16),
                    ("markdown_text", 16),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"group": "Custom", "label": "Paragraph"},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("h2", "H2"), ("h3", "H3"), ("h4", "H4")]},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 1), ("size", 2)]],
                        {"group": "Custom", "label": "Section header"},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Label"}),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Help text", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Required", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Tick this if the answer will contain personally identifiable information, such as a name, address, phone number or date of birth. Only the applicant, their co-applicants and staff will be able to see the answer. Reviewers and other users will see that the question was asked, but not the answer.",
                            "label": "Personal information",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("email", "Email"), ("url", "URL")],
                            "label": "Format",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Default value", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("format", 8),
                                ("default_value", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    11: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 2, "label": "Max number of inputs"},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Add new item", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("format", 8),
                                ("default_value", 9),
                                ("number_of_inputs", 11),
                                ("add_button_text", 12),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    14: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Default value", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 1000, "label": "Word limit"},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 14),
                                ("word_limit", 15),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    18: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 18),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    20: ("wagtail.blocks.CharBlock", (), {"label": "Choice"}),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("choices", 21),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    23: ("wagtail.blocks.CharBlock", (), {"label": "Checkbox"}),
                    24: ("wagtail.blocks.ListBlock", (23,), {}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("checkboxes", 24),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    26: ("wagtail.blocks.DateBlock", (), {"required": False}),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 26),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    28: ("wagtail.blocks.TimeBlock", (), {"required": False}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 28),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    30: ("wagtail.blocks.DateTimeBlock", (), {"required": False}),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 30),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    33: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "label": "Required", "required": False},
                    ),
                    34: (
                        "wagtail.blocks.ListBlock",
                        (20,),
                        {
                            "help_text": "Please create only two choices for toggle. First choice will revel the group and the second hide it. Additional choices will be ignored."
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 33),
                                ("choices", 34),
                            ]
                        ],
                        {"group": "Custom"},
                    ),
                    36: (
                        "hypha.apply.stream_forms.blocks.GroupToggleEndBlock",
                        (),
                        {"group": "Custom"},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="projectsow",
            name="form_fields",
            field=wagtail.fields.StreamField(
                [
                    ("text_markup", 0),
                    ("header_markup", 3),
                    ("char", 10),
                    ("multi_inputs_char", 13),
                    ("text", 16),
                    ("number", 17),
                    ("checkbox", 19),
                    ("radios", 22),
                    ("dropdown", 22),
                    ("checkboxes", 25),
                    ("date", 27),
                    ("time", 29),
                    ("datetime", 31),
                    ("image", 32),
                    ("file", 32),
                    ("multi_file", 32),
                    ("group_toggle", 35),
                    ("group_toggle_end", 36),
                    ("rich_text", 16),
                    ("markdown_text", 16),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"group": "Custom", "label": "Paragraph"},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("h2", "H2"), ("h3", "H3"), ("h4", "H4")]},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 1), ("size", 2)]],
                        {"group": "Custom", "label": "Section header"},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Label"}),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Help text", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Required", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Tick this if the answer will contain personally identifiable information, such as a name, address, phone number or date of birth. Only the applicant, their co-applicants and staff will be able to see the answer. Reviewers and other users will see that the question was asked, but not the answer.",
                            "label": "Personal information",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("email", "Email"), ("url", "URL")],
                            "label": "Format",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Default value", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("format", 8),
                                ("default_value", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    11: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 2, "label": "Max number of inputs"},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Add new item", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("format", 8),
                                ("default_value", 9),
                                ("number_of_inputs", 11),
                                ("add_button_text", 12),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    14: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Default value", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 1000, "label": "Word limit"},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 14),
                                ("word_limit", 15),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    18: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 18),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    20: ("wagtail.blocks.CharBlock", (), {"label": "Choice"}),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("choices", 21),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    23: ("wagtail.blocks.CharBlock", (), {"label": "Checkbox"}),
                    24: ("wagtail.blocks.ListBlock", (23,), {}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("checkboxes", 24),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    26: ("wagtail.blocks.DateBlock", (), {"required": False}),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 26),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    28: ("wagtail.blocks.TimeBlock", (), {"required": False}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 28),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    30: ("wagtail.blocks.DateTimeBlock", (), {"required": False}),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 30),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    33: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "label": "Required", "required": False},
                    ),
                    34: (
                        "wagtail.blocks.ListBlock",
                        (20,),
                        {
                            "help_text": "Please create only two choices for toggle. First choice will revel the group and the second hide it. Additional choices will be ignored."
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 33),
                                ("choices", 34),
                            ]
                        ],
                        {"group": "Custom"},
                    ),
                    36: (
                        "hypha.apply.stream_forms.blocks.GroupToggleEndBlock",
                        (),
                        {"group": "Custom"},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectsowform",
            name="form_fields",
            field=wagtail.fields.StreamField(
                [
                    ("text_markup", 0),
                    ("header_markup", 3),
                    ("char", 10),
                    ("multi_inputs_char", 13),
                    ("text", 16),
                    ("number", 17),
                    ("checkbox", 19),
                    ("radios", 22),
                    ("dropdown", 22),
                    ("checkboxes", 25),
                    ("date", 27),
                    ("time", 29),
                    ("datetime", 31),
                    ("image", 32),
                    ("file", 32),
                    ("multi_file", 32),
                    ("group_toggle", 35),
                    ("group_toggle_end", 36),
                    ("rich_text", 16),
                    ("markdown_text", 16),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"group": "Custom", "label": "Paragraph"},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("h2", "H2"), ("h3", "H3"), ("h4", "H4")]},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 1), ("size", 2)]],
                        {"group": "Custom", "label": "Section header"},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Label"}),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Help text", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Required", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Tick this if the answer will contain personally identifiable information, such as a name, address, phone number or date of birth. Only the applicant, their co-applicants and staff will be able to see the answer. Reviewers and other users will see that the question was asked, but not the answer.",
                            "label": "Personal information",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("email", "Email"), ("url", "URL")],
                            "label": "Format",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Default value", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("format", 8),
                                ("default_value", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    11: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 2, "label": "Max number of inputs"},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Add new item", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("format", 8),
                                ("default_value", 9),
                                ("number_of_inputs", 11),
                                ("add_button_text", 12),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    14: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Default value", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 1000, "label": "Word limit"},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 14),
                                ("word_limit", 15),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    18: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 18),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    20: ("wagtail.blocks.CharBlock", (), {"label": "Choice"}),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("choices", 21),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    23: ("wagtail.blocks.CharBlock", (), {"label": "Checkbox"}),
                    24: ("wagtail.blocks.ListBlock", (23,), {}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("checkboxes", 24),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    26: ("wagtail.blocks.DateBlock", (), {"required": False}),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 26),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    28: ("wagtail.blocks.TimeBlock", (), {"required": False}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 28),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    30: ("wagtail.blocks.DateTimeBlock", (), {"required": False}),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                                ("default_value", 30),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 7),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    33: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "label": "Required", "required": False},
                    ),
                    34: (
                        "wagtail.blocks.ListBlock",
                        (20,),
                        {
                            "help_text": "Please create only two choices for toggle. First choice will revel the group and the second hide it. Additional choices will be ignored."
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 33),
                                ("choices", 34),
                            ]
                        ],
                        {"group": "Custom"},
                    ),
                    36: (
                        "hypha.apply.stream_forms.blocks.GroupToggleEndBlock",
                        (),
                        {"group": "Custom"},
                    ),
                },
            ),
        ),
    ]
