# Generated by Django 5.2.17 on 2026-09-22 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0109_create_project_form_pointers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pafreviewersrole",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "PAF reviewers role",
                "verbose_name_plural": "PAF reviewers roles",
            },
        ),
        migrations.AlterModelOptions(
            name="projectreminderfrequency",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "project reminder frequency",
                "verbose_name_plural": "project reminder frequencies",
            },
        ),
    ]
