# Generated by Django 5.2.13 on 2026-08-13 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "application_projects",
            "0110_projectevaluation_author_projectevaluation_submitted",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="amount_approved",
            field=models.DecimalField(decimal_places=19, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="amount_requested",
            field=models.DecimalField(decimal_places=19, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="currency",
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("currency__isnull", True),
                    ("currency__regex", "^[A-Z]{3}$"),
                    _connector="OR",
                ),
                name="contract_currency_code_format",
            ),
        ),
    ]
