# Harmonize Contract ordering with Disbursement: both newest-first
# (reverse-chronological), matching the activity feed and invoice lists.
#
# Generated by Django 5.2.13 on 2026-08-23 00:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application_projects", "0112_disbursement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contract",
            options={"ordering": ["-created_at"]},
        ),
    ]
