# Generated by Django 4.2.9 on 2024-01-10 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_remove_projectindexpage_social_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectfunding",
            name="page",
        ),
        migrations.RemoveField(
            model_name="projectfunding",
            name="source",
        ),
        migrations.RemoveField(
            model_name="projectindexpage",
            name="header_image",
        ),
        migrations.RemoveField(
            model_name="projectindexpage",
            name="listing_image",
        ),
        migrations.RemoveField(
            model_name="projectindexpage",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="projectpage",
            name="header_image",
        ),
        migrations.RemoveField(
            model_name="projectpage",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="projectpage",
            name="listing_image",
        ),
        migrations.RemoveField(
            model_name="projectpage",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="projectpagerelatedpage",
            name="page",
        ),
        migrations.RemoveField(
            model_name="projectpagerelatedpage",
            name="source_page",
        ),
        migrations.DeleteModel(
            name="ProjectContactDetails",
        ),
        migrations.DeleteModel(
            name="ProjectFunding",
        ),
        migrations.DeleteModel(
            name="ProjectIndexPage",
        ),
        migrations.DeleteModel(
            name="ProjectPage",
        ),
        migrations.DeleteModel(
            name="ProjectPageRelatedPage",
        ),
    ]
