# Generated by Django 2.2.9 on 2020-02-07 14:23

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('images', '0003_customimage_drupal_id'),
        ('wagtaildocs', '0010_document_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetNetworkHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content_heading', models.CharField(max_length=255, verbose_name='Heading')),
                ('content_text', models.TextField(blank=True, verbose_name='Text')),
                ('content_link_text', models.CharField(blank=True, max_length=255, verbose_name='Link text')),
                ('section_1_heading', models.CharField(blank=True, max_length=255, verbose_name='Heading')),
                ('section_1_text', models.TextField(blank=True, verbose_name='Text')),
                ('section_1_link_text', models.CharField(blank=True, max_length=255, verbose_name='Link text')),
                ('section_2_heading', models.CharField(blank=True, max_length=255, verbose_name='Heading')),
                ('section_2_text', models.TextField(blank=True, verbose_name='Text')),
                ('section_2_link_text', models.CharField(blank=True, max_length=255, verbose_name='Link text')),
                ('section_3_heading', models.CharField(blank=True, max_length=255, verbose_name='Heading')),
                ('section_3_link_text', models.CharField(blank=True, max_length=255, verbose_name='Link text')),
                ('content_heading_gif_desktop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document', verbose_name='Heading image desktop')),
                ('content_heading_gif_mobile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document', verbose_name='Heading image mobile')),
                ('content_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.Page', verbose_name='Link')),
                ('section_1_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage')),
                ('section_1_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.Page', verbose_name='Link')),
                ('section_2_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage')),
                ('section_2_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.Page', verbose_name='Link')),
                ('section_3_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.Page', verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Reset Network Home Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ResetNetworkHomePageOpenCalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('open_call_link_page', models.ForeignKey(help_text='The page to link to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Open calls Page')),
                ('open_calls_link', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_network_home_page_open_calls', to='reset_network_home.ResetNetworkHomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResetNetworkHomePageHeroImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_network_home_page_hero_images', to='reset_network_home.ResetNetworkHomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResetNetworkHomePageFeatured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('heading', models.CharField(max_length=255, verbose_name='Heading')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('link', models.URLField(verbose_name='Link')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_network_home_page_featured', to='reset_network_home.ResetNetworkHomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
