# Generated by Django 2.2.9 on 2020-02-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset_network_person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetnetworkperson',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resetnetworkperson',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resetnetworkperson',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
