# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0019_protect_submission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationsubmission',
            options={},
        ),
        migrations.AddField(
            model_name='applicationsubmission',
            name='status',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationsubmission',
            name='workflow',
            field=models.CharField(choices=[('single', 'Single Stage'), ('double', 'Two Stage')], default='single', max_length=100),
        ),
    ]
