# Generated by Django 2.0.2 on 2018-09-05 10:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import opentech.apply.stream_forms.files


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0041_roundbasereviewform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrevision',
            name='form_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=opentech.apply.stream_forms.files.StreamFieldDataEncoder),
        ),
        migrations.AlterField(
            model_name='applicationsubmission',
            name='form_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=opentech.apply.stream_forms.files.StreamFieldDataEncoder),
        ),
    ]
