# Generated by Django 2.0.9 on 2019-02-24 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0062_data_migrate_type_for_assigned_reviewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedreviewers',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group'),
        ),
    ]
