# Generated by Django 2.1.11 on 2019-09-05 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0068_link_funds_and_labs_to_paf'),
        ('funds', '0068_add_help_link_field'),
    ]

    operations = [
    ]
