# Generated by Django 2.2.11 on 2020-03-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0073_reminder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='reminder',
            name='medium',
            field=models.CharField(choices=[('slack', 'slack'), ('email', 'email')], default='email', max_length=15),
        ),
    ]
