# Generated by Django 2.2.13 on 2020-06-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0074_add_word_limit_to_text_blocks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationbase",
            name="slack_channel",
            field=models.CharField(
                blank=True,
                help_text="The slack #channel for notifications. If left empty, notifications will go to the default channel.",
                max_length=128,
            ),
        ),
    ]
