# Generated by Django 2.2.11 on 2020-03-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0074_auto_20200310_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='medium',
            field=models.CharField(choices=[('slack', 'Slack'), ('email', 'Email')], default='email', max_length=15),
        ),
    ]
