# Generated by Django 2.2.11 on 2020-03-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0075_auto_20200310_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='medium',
            field=models.CharField(choices=[('email', 'Email')], default='email', max_length=15),
        ),
    ]
