# Generated by Django 2.2.11 on 2020-03-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0077_auto_20200316_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='action',
            field=models.CharField(choices=[('reviewers_review', 'Remind reviewers to Review')], default='review', max_length=50),
        ),
    ]
