# Generated by Django 2.2.11 on 2020-03-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0079_auto_20200316_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='action',
            field=models.CharField(choices=[('reviewers_review', 'Remind reviewers to Review')], max_length=50),
        ),
    ]
