# Generated by Django 2.2.16 on 2020-11-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0079_add_reviewer_settings_for_submission_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationbaseform',
            name='minimize_form',
            field=models.BooleanField(default=False, help_text='Minimize application form to only show required fields.'),
        ),
        migrations.AddField(
            model_name='labbaseform',
            name='minimize_form',
            field=models.BooleanField(default=False, help_text='Minimize application form to only show required fields.'),
        ),
        migrations.AddField(
            model_name='roundbaseform',
            name='minimize_form',
            field=models.BooleanField(default=False, help_text='Minimize application form to only show required fields.'),
        ),
    ]
