# Generated by Django 2.2.16 on 2020-10-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0079_add_reviewer_settings_for_submission_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsubmission',
            name='screening_statuses',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='funds.ScreeningStatus'),
        ),
    ]
