# Generated by Django 2.2.16 on 2020-10-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0082_remove_screening_status_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningstatus',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Default Yes/No'),
        ),
        migrations.AddField(
            model_name='screeningstatus',
            name='yes',
            field=models.BooleanField(default=False, verbose_name='Yes/No'),
        ),
    ]
