# Generated by Django 2.2.16 on 2020-11-09 05:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0082_migrate_screening_status_to_screening_statuses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationsubmission",
            name="screening_status",
        ),
    ]
