# Generated by Django 2.2.18 on 2021-02-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0084_add_all_except_dismissed_outcome_reviewersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsubmission',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
