# Generated by Django 2.2.16 on 2020-12-22 08:18

from django.contrib.postgres.operations import CryptoExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0084_add_all_except_dismissed_outcome_reviewersettings'),
    ]

    operations = [
        CryptoExtension(),
    ]
