# Generated by Django 2.2.18 on 2021-02-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0085_applicationsubmission_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsubmission',
            name='summary',
            field=models.TextField(default='', null=True),
        ),
    ]
