# Generated by Django 2.2.18 on 2021-02-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0086_auto_20210215_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsubmission',
            name='summary',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
