# Generated by Django 2.2.19 on 2021-04-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0087_applicationsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reminder",
            name="title",
            field=models.CharField(default="", max_length=60),
        ),
    ]
