# Generated by Django 2.2.20 on 2021-04-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0087_applicationsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screeningstatus',
            options={'verbose_name_plural': 'screening decisions'},
        ),
        migrations.AlterField(
            model_name='screeningstatus',
            name='default',
            field=models.BooleanField(default=False, help_text='Only one Yes and No screening decision can be set as default.', verbose_name='Default Yes/No'),
        ),
    ]
