# Generated by Django 2.2.24 on 2021-10-08 15:23

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0088_auto_20210423_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='labbase',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='labbase',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
