# Generated by Django 2.2.24 on 2021-10-08 15:40

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0089_auto_20211008_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationbase',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='applicationbase',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
