# Generated by Django 3.1 on 2022-01-11 13:14

from django.db import migrations, models
import hypha.apply.stream_forms.files


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0089_remove_project_approval_form_refrences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationrevision",
            name="form_data",
            field=models.JSONField(
                encoder=hypha.apply.stream_forms.files.StreamFieldDataEncoder
            ),
        ),
        migrations.AlterField(
            model_name="applicationsubmission",
            name="form_data",
            field=models.JSONField(
                encoder=hypha.apply.stream_forms.files.StreamFieldDataEncoder
            ),
        ),
    ]
