# Generated by Django 3.2.12 on 2022-03-08 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0090_auto_20220111_1314'),
        ('funds', '0091_auto_20220222_0619'),
    ]

    operations = [
    ]
