# Generated by Django 3.2.13 on 2022-04-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0094_auto_20220406_0800"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewersettings",
            name="state",
            field=models.CharField(
                choices=[
                    ("all", "All States"),
                    ("ext_state_or_higher", "Only External review and higher"),
                    ("ext_state_only", "Only External review"),
                ],
                default="all",
                help_text="Submissions states for which reviewers should have access to",
                max_length=20,
            ),
        ),
    ]
