# Generated by Django 3.2.15 on 2022-09-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0102_add_projectapprovalform_to_fundbase_labbase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screeningstatus',
            options={'verbose_name': 'Screening Decision', 'verbose_name_plural': 'screening decisions'},
        ),
    ]
