# Generated by Django 3.2.16 on 2022-10-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0103_alter_screeningstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsubmission',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
