# Generated by Django 3.2.16 on 2022-11-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0103_alter_screeningstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationbase',
            name='show_deadline',
            field=models.BooleanField(default=True, help_text='Should the deadline date be visible for users.'),
        ),
    ]
