# Generated by Django 3.2.16 on 2022-11-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0105_applicationbase_activity_digest_recipient_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationsubmission",
            name="is_archive",
            field=models.BooleanField(default=False),
        ),
    ]
