# Generated by Django 3.2.18 on 2023-03-31 11:54

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0109_rename_section_text_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsubmission',
            name='search_document',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='applicationsubmission',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_document'], name='funds_appli_search__43a072_gin'),
        ),
    ]
