# Generated by Django 4.1.8 on 2023-05-09 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funds', '0110_auto_20230418_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationbase',
            name='reviewers',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, limit_choices_to={'groups__name': 'Reviewer', 'is_active': True}, related_name='%(class)s_reviewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roundbase',
            name='lead',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Staff', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roundbase',
            name='reviewers',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, limit_choices_to={'groups__name': 'Reviewer', 'is_active': True}, related_name='%(class)s_reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
