# Generated by Django 3.2.21 on 2023-10-06 17:57

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0080_auto_20231006_1757'),
        ('funds', '0112_add_organization_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabBaseProjectReportForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application_projects.projectreportform')),
                ('lab', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_forms', to='funds.labbase')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationBaseProjectReportForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('application', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_forms', to='funds.applicationbase')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application_projects.projectreportform')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
