# Generated by Django 4.2.7 on 2023-11-29 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("funds", "0113_alter_assignedreviewers_reviewer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignedreviewers",
            name="reviewer",
            field=models.ForeignKey(
                limit_choices_to={
                    "groups__name__in": ["Staff", "Reviewer", "Community reviewer"],
                    "is_active": True,
                },
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
