# Generated by Django 4.2.9 on 2024-01-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0114_alter_assignedreviewers_reviewer"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationbase",
            name="list_on_front_page",
            field=models.BooleanField(
                default=True, help_text="Should the fund be listed on the front page."
            ),
        ),
        migrations.AddField(
            model_name="labbase",
            name="list_on_front_page",
            field=models.BooleanField(
                default=True, help_text="Should the lab be listed on the front page."
            ),
        ),
    ]
