# Generated by Django 4.2.9 on 2024-01-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0114_alter_assignedreviewers_reviewer"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationbase",
            name="preview_required",
            field=models.BooleanField(
                default=False,
                help_text="Require the applicant to view a preview of their application before submitting.",
                verbose_name="Require Preview Before Submitting",
            ),
        ),
        migrations.AddField(
            model_name="labbase",
            name="preview_required",
            field=models.BooleanField(
                default=False,
                help_text="Require the applicant to view a preview of their application before submitting.",
                verbose_name="Require Preview Before Submitting",
            ),
        ),
    ]
