# Generated by Django 4.2.11 on 2024-05-07 06:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "application_projects",
            "0082_rename_projectapprovalform_projectform_and_more",
        ),
        ("funds", "0115_list_on_front_page"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ApplicationBaseProjectApprovalForm",
            new_name="ApplicationBaseProjectForm",
        ),
        migrations.RenameModel(
            old_name="LabBaseProjectApprovalForm",
            new_name="LabBaseProjectForm",
        ),
    ]
