# Generated by Django 4.2.10 on 2024-03-13 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0117_applicationrevision_is_draft"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationrevision",
            name="is_preview",
        ),
    ]
