# Generated by Django 4.2.11 on 2024-05-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "funds",
            "0119_rename_applicationbaseprojectapprovalform_applicationbaseprojectform_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationsubmission",
            name="public_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="labbase",
            name="submission_id_prefix",
            field=models.SlugField(
                blank=True,
                default="",
                help_text='Prefix for the submission id. e.g. "HYPHA23-" will result in a submission id of "HYPHA23-1".',
                max_length=10,
                verbose_name="Submission ID Prefix",
            ),
        ),
        migrations.AddField(
            model_name="roundbase",
            name="submission_id_prefix",
            field=models.SlugField(
                blank=True,
                default="",
                help_text='Prefix for the submission id. e.g. "HYPHA23-" will result in a submission id of "HYPHA23-1".',
                max_length=10,
                verbose_name="Submission ID Prefix",
            ),
        ),
    ]
