# Generated by Django 4.2.17 on 2025-01-14 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0121_alter_applicationbase_workflow_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationsubmission",
            name="drupal_id",
        ),
    ]
