# Generated by Django 4.2.20 on 2025-04-23 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("funds", "0123_help_text_rich_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoApplicantInvite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invited_user_email", models.EmailField(max_length=254)),
                ("token", models.CharField(max_length=256, unique=True)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="co_applicant_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="co_applicant_invites",
                        to="funds.applicationsubmission",
                    ),
                ),
            ],
            options={
                "unique_together": {("submission", "invited_user_email")},
            },
        ),
        migrations.CreateModel(
            name="CoApplicant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="accepted",
                        max_length=20,
                    ),
                ),
                ("accepted_on", models.DateTimeField(blank=True, null=True)),
                (
                    "invite",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="co_applicant",
                        to="funds.coapplicantinvite",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="co_applicants",
                        to="funds.applicationsubmission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="co_applicants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("submission", "user")},
            },
        ),
    ]
