# Generated by Django 4.2.20 on 2025-03-24 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("funds", "0123_help_text_rich_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionExportManager",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("export_data", models.TextField()),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("completed_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("error", "Failed"),
                            ("success", "Success"),
                            ("generating", "In Progress"),
                        ],
                        default="generating",
                    ),
                ),
                ("total_export", models.IntegerField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "Staff", "is_active": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
