# Generated by Django 4.2.20 on 2025-04-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0124_coapplicantinvite_coapplicant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coapplicant",
            name="accepted_on",
        ),
        migrations.RemoveField(
            model_name="coapplicant",
            name="status",
        ),
        migrations.RemoveField(
            model_name="coapplicantinvite",
            name="is_used",
        ),
        migrations.RemoveField(
            model_name="coapplicantinvite",
            name="token",
        ),
        migrations.AddField(
            model_name="coapplicant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="coapplicantinvite",
            name="responded_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coapplicantinvite",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
