# Generated by Django 4.2.20 on 2025-05-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0125_remove_coapplicant_accepted_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coapplicant",
            name="role",
            field=models.CharField(
                choices=[
                    ("read_only", "Read Only"),
                    ("comment", "Comment"),
                    ("full_access", "Full Access"),
                ],
                default="read_only",
            ),
        ),
    ]
