# Generated by Django 4.2.20 on 2025-05-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0126_add_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="coapplicant",
            name="project_permission",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
