# Generated by Django 4.2.20 on 2025-05-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0126_alter_coapplicant_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="coapplicantinvite",
            name="invited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coapplicantinvite",
            name="role",
            field=models.CharField(
                choices=[
                    ("read_only", "Read Only"),
                    ("comment", "Comment"),
                    ("full_access", "Full Access"),
                ],
                default="read_only",
            ),
        ),
    ]
