# Generated by Django 4.2.21 on 2025-05-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0127_coapplicant_project_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coapplicant",
            name="role",
            field=models.CharField(
                choices=[("view", "View"), ("comment", "Comment"), ("edit", "Edit")],
                default="view",
            ),
        ),
        migrations.AlterField(
            model_name="coapplicantinvite",
            name="role",
            field=models.CharField(
                choices=[("view", "View"), ("comment", "Comment"), ("edit", "Edit")],
                default="view",
            ),
        ),
    ]
