# Generated by Django 4.2.21 on 2025-06-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0128_alter_coapplicant_role_alter_coapplicantinvite_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="coapplicantinvite",
            name="project_permission",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
