# Generated by Django 5.2.12 on 2026-03-25 16:46

from django.db import migrations
from django.contrib.auth.models import Group

from hypha.apply.funds.models.co_applicants import (
    CoApplicantRole,
    CoApplicantInviteStatus,
)


def migrate_partners_to_coapplicants(apps, schema_editor):
    PARTNER_GROUP_NAME = "Partner"

    CoApplicant = apps.get_model("funds", "CoApplicant")
    CoApplicantInvite = apps.get_model("funds", "CoApplicantInvite")
    ApplicationSubmission = apps.get_model("funds", "ApplicationSubmission")

    qs = ApplicationSubmission.objects.all()
    if hasattr(qs, "partners"):
        partnered_subs = ApplicationSubmission.objects.filter(
            partners__isnull=False
        ).values_list("id", "partners__id", "partners__email")

        for submission_id, partner_id, partner_email in partnered_subs:
            # Co-Applicants are shown on submissions by the state of their invite, so create a dummy invite
            coapp_invite, created = CoApplicantInvite.objects.get_or_create(
                submission_id=submission_id, invited_user_email=partner_email
            )
            coapp_invite.role = CoApplicantRole.COMMENT
            coapp_invite.status = CoApplicantInviteStatus.ACCEPTED
            coapp_invite.save()
            CoApplicant.objects.get_or_create(
                submission_id=submission_id,
                user_id=partner_id,
                role=CoApplicantRole.COMMENT,
                invite=coapp_invite,
            )

    if Group.objects.filter(name=PARTNER_GROUP_NAME).exists():
        all_partner_ids = Group.objects.get(
            name=PARTNER_GROUP_NAME
        ).user_set.values_list("id", flat=True)
        Group.objects.get(name="Applicant").user_set.add(*all_partner_ids)


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0131_delete_orphaned_attachments"),
    ]

    operations = [migrations.RunPython(migrate_partners_to_coapplicants)]
