# Generated by Django 5.2.11 on 2026-03-03 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0131_delete_orphaned_attachments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationbase",
            options={
                "verbose_name": "application base",
                "verbose_name_plural": "application bases",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationbasedeterminationform",
            options={
                "verbose_name": "application base determination form",
                "verbose_name_plural": "application base determination forms",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationbaseexternalreviewform",
            options={
                "verbose_name": "application base external review form",
                "verbose_name_plural": "application base external review form",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationbaseform",
            options={
                "verbose_name": "application base form",
                "verbose_name_plural": "application base forms",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationbaseprojectform",
            options={
                "verbose_name": "application base project form",
                "verbose_name_plural": "application base project forms",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationbaseprojectreportform",
            options={
                "verbose_name": "application base project report form",
                "verbose_name_plural": "application base project report forms",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationbaseprojectsowform",
            options={
                "verbose_name": "application base project SOW form",
                "verbose_name_plural": "application base project SOW forms",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationbasereviewform",
            options={
                "verbose_name": "application base review form",
                "verbose_name_plural": "application base review forms",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationform",
            options={
                "verbose_name": "application form",
                "verbose_name_plural": "applications forms",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationrevision",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "application revision",
                "verbose_name_plural": "application revisions",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationsubmission",
            options={
                "verbose_name": "application submission",
                "verbose_name_plural": "application submissions",
            },
        ),
        migrations.AlterModelOptions(
            name="assignedreviewers",
            options={
                "verbose_name": "assigned reviewer",
                "verbose_name_plural": "assigned reviewers",
            },
        ),
        migrations.AlterModelOptions(
            name="coapplicant",
            options={
                "verbose_name": "co-applicant",
                "verbose_name_plural": "co-applicants",
            },
        ),
        migrations.AlterModelOptions(
            name="coapplicantinvite",
            options={
                "verbose_name": "co-applicant invite",
                "verbose_name_plural": "co-applicant invites",
            },
        ),
        migrations.AlterModelOptions(
            name="fundtype",
            options={"verbose_name": "Fund", "verbose_name_plural": "Funds"},
        ),
        migrations.AlterModelOptions(
            name="labbase",
            options={"verbose_name": "lab base", "verbose_name_plural": "lab bases"},
        ),
        migrations.AlterModelOptions(
            name="labbasedeterminationform",
            options={
                "verbose_name": "lab base determination form",
                "verbose_name_plural": "lab base determination forms",
            },
        ),
        migrations.AlterModelOptions(
            name="labbaseexternalreviewform",
            options={
                "verbose_name": "lab base external review form",
                "verbose_name_plural": "lab base external review forms",
            },
        ),
        migrations.AlterModelOptions(
            name="labbaseform",
            options={
                "verbose_name": "lab base form",
                "verbose_name_plural": "lab base forms",
            },
        ),
        migrations.AlterModelOptions(
            name="labbaseprojectform",
            options={
                "verbose_name": "lab base project form",
                "verbose_name_plural": "lab base project forms",
            },
        ),
        migrations.AlterModelOptions(
            name="labbaseprojectreportform",
            options={
                "verbose_name": "lab base project report form",
                "verbose_name_plural": "lab base project report forms",
            },
        ),
        migrations.AlterModelOptions(
            name="labbaseprojectsowform",
            options={
                "verbose_name": "lab base project SOW form",
                "verbose_name_plural": "lab base project SOW forms",
            },
        ),
        migrations.AlterModelOptions(
            name="labbasereviewform",
            options={
                "verbose_name": "lab base review form",
                "verbose_name_plural": "lab base review forms",
            },
        ),
        migrations.AlterModelOptions(
            name="labtype",
            options={"verbose_name": "Lab", "verbose_name_plural": "Labs"},
        ),
        migrations.AlterModelOptions(
            name="reminder",
            options={
                "ordering": ["-time"],
                "verbose_name": "reminder",
                "verbose_name_plural": "reminders",
            },
        ),
        migrations.AlterModelOptions(
            name="requestforpartners",
            options={"verbose_name": "RFP", "verbose_name_plural": "RFPs"},
        ),
        migrations.AlterModelOptions(
            name="reviewerrole",
            options={
                "verbose_name": "reviewer role",
                "verbose_name_plural": "reviewer roles",
            },
        ),
        migrations.AlterModelOptions(
            name="round",
            options={"verbose_name": "Round", "verbose_name_plural": "Rounds"},
        ),
        migrations.AlterModelOptions(
            name="roundbase",
            options={
                "verbose_name": "round base",
                "verbose_name_plural": "round bases",
            },
        ),
        migrations.AlterModelOptions(
            name="roundbasedeterminationform",
            options={
                "verbose_name": "round base determination form",
                "verbose_name_plural": "round base determination forms",
            },
        ),
        migrations.AlterModelOptions(
            name="roundbaseexternalreviewform",
            options={
                "verbose_name": "round base externa review form",
                "verbose_name_plural": "round base external review forms",
            },
        ),
        migrations.AlterModelOptions(
            name="roundbaseform",
            options={
                "verbose_name": "round base form",
                "verbose_name_plural": "round base forms",
            },
        ),
        migrations.AlterModelOptions(
            name="roundbasereviewform",
            options={
                "verbose_name": "round base review form",
                "verbose_name_plural": "round base review forms",
            },
        ),
        migrations.AlterModelOptions(
            name="roundsandlabs",
            options={
                "verbose_name": "round and lab",
                "verbose_name_plural": "rounds and labs",
            },
        ),
        migrations.AlterModelOptions(
            name="sealedround",
            options={
                "verbose_name": "Sealed round",
                "verbose_name_plural": "Sealed rounds",
            },
        ),
        migrations.AlterModelOptions(
            name="submissionexportmanager",
            options={
                "verbose_name": "submission export manager",
                "verbose_name_plural": "submission export managers",
            },
        ),
    ]
