# Generated by Django 4.2.25 on 2025-11-05 20:04

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("funds", "0131_delete_orphaned_attachments"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationSubmissionSkeleton",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("almost", "Accepted but additional info required"),
                            ("com_accepted", "Accepted"),
                            ("com_almost", "Accepted but additional info required"),
                            ("com_community_review", "Community Review"),
                            ("com_determination", "Ready for Determination"),
                            ("com_external_review", "External Review"),
                            ("com_internal_review", "Internal Review"),
                            ("com_more_info", "More information required"),
                            ("com_open_call", "Open Call (public)"),
                            (
                                "com_post_external_review_discussion",
                                "Ready For Discussion",
                            ),
                            (
                                "com_post_external_review_more_info",
                                "More information required",
                            ),
                            ("com_post_review_discussion", "Ready For Discussion"),
                            ("com_post_review_more_info", "More information required"),
                            ("com_rejected", "Dismissed"),
                            (
                                "concept_determination",
                                "Ready for Preliminary Determination",
                            ),
                            ("concept_internal_review", "Internal Review"),
                            ("concept_more_info", "More information required"),
                            ("concept_rejected", "Dismissed"),
                            ("concept_review_discussion", "Ready For Discussion"),
                            ("concept_review_more_info", "More information required"),
                            ("determination", "Ready for Determination"),
                            ("draft", "Draft"),
                            ("draft_proposal", "Invited for Proposal"),
                            ("ext_accepted", "Accepted"),
                            ("ext_almost", "Accepted but additional info required"),
                            ("ext_determination", "Ready for Determination"),
                            ("ext_external_review", "External Review"),
                            ("ext_internal_review", "Internal Review"),
                            ("ext_more_info", "More information required"),
                            (
                                "ext_post_external_review_discussion",
                                "Ready For Discussion",
                            ),
                            (
                                "ext_post_external_review_more_info",
                                "More information required",
                            ),
                            ("ext_post_review_discussion", "Ready For Discussion"),
                            ("ext_post_review_more_info", "More information required"),
                            ("ext_rejected", "Dismissed"),
                            ("external_review", "External Review"),
                            ("in_discussion", "Need screening"),
                            ("internal_review", "Internal Review"),
                            ("invited_to_proposal", "Concept Accepted"),
                            ("more_info", "More information required"),
                            ("post_external_review_discussion", "Ready For Discussion"),
                            (
                                "post_external_review_more_info",
                                "More information required",
                            ),
                            ("post_proposal_review_discussion", "Ready For Discussion"),
                            (
                                "post_proposal_review_more_info",
                                "More information required",
                            ),
                            ("post_review_discussion", "Ready For Discussion"),
                            ("post_review_more_info", "More information required"),
                            ("proposal_accepted", "Accepted"),
                            (
                                "proposal_almost",
                                "Accepted but additional info required",
                            ),
                            ("proposal_determination", "Ready for Final Determination"),
                            ("proposal_discussion", "Proposal Received"),
                            ("proposal_internal_review", "Internal Review"),
                            ("proposal_more_info", "More information required"),
                            ("proposal_rejected", "Dismissed"),
                            ("rejected", "Dismissed"),
                            ("same_accepted", "Accepted"),
                            ("same_almost", "Accepted but additional info required"),
                            ("same_determination", "Ready for Determination"),
                            ("same_internal_review", "Review"),
                            ("same_more_info", "More information required"),
                            ("same_post_review_discussion", "Ready For Discussion"),
                            ("same_post_review_more_info", "More information required"),
                            ("same_rejected", "Dismissed"),
                        ],
                        default="in_discussion",
                        max_length=100,
                    ),
                ),
                (
                    "category",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(), null=True, size=None
                    ),
                ),
                ("submit_time", models.DateTimeField(verbose_name="submit time")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="skeleton_submissions",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "screening_statuses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="skeleton_submissions",
                        to="funds.screeningstatus",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
