# Generated by Django 5.2.12 on 2026-03-26 21:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("funds", "0132_convert_partners_to_coapplicants")]

    operations = [
        migrations.RemoveField(
            model_name="applicationsubmission",
            name="partners",
        ),
    ]
