# Generated by Django 5.2.12 on 2026-03-31 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0132_alter_applicationbase_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationbaseexternalreviewform",
            options={
                "verbose_name": "application base external review form",
                "verbose_name_plural": "application base external review forms",
            },
        ),
        migrations.AlterModelOptions(
            name="roundbaseexternalreviewform",
            options={
                "verbose_name": "round base external review form",
                "verbose_name_plural": "round base external review forms",
            },
        ),
        migrations.AlterField(
            model_name="applicationbase",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="applicationbase",
            name="guide_link",
            field=models.URLField(
                blank=True,
                help_text="Link to the apply guide.",
                max_length=255,
                verbose_name="guide link",
            ),
        ),
        migrations.AlterField(
            model_name="applicationbase",
            name="list_on_front_page",
            field=models.BooleanField(
                default=True,
                help_text="Should the fund be listed on the front page.",
                verbose_name="list on front page",
            ),
        ),
        migrations.AlterField(
            model_name="applicationbase",
            name="show_deadline",
            field=models.BooleanField(
                default=True,
                help_text="Should the deadline date be visible for users.",
                verbose_name="show deadline",
            ),
        ),
        migrations.AlterField(
            model_name="applicationbase",
            name="workflow_name",
            field=models.CharField(
                choices=[
                    ("single", "Request"),
                    ("single_same", "Request with same time review"),
                    ("single_ext", "Request with external review"),
                    ("single_com", "Request with community review"),
                    ("double", "Concept & Proposal"),
                ],
                default="single",
                max_length=100,
                verbose_name="workflow",
            ),
        ),
        migrations.AlterField(
            model_name="applicationsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("almost", "Accepted but additional info required"),
                    ("com_accepted", "Accepted"),
                    ("com_almost", "Accepted but additional info required"),
                    ("com_community_review", "Community Review"),
                    ("com_determination", "Ready for Determination"),
                    ("com_external_review", "External Review"),
                    ("com_internal_review", "Internal Review"),
                    ("com_more_info", "More information required"),
                    ("com_open_call", "Open Call (public)"),
                    ("com_post_external_review_discussion", "Ready For Discussion"),
                    ("com_post_external_review_more_info", "More information required"),
                    ("com_post_review_discussion", "Ready For Discussion"),
                    ("com_post_review_more_info", "More information required"),
                    ("com_rejected", "Dismissed"),
                    ("concept_determination", "Ready for Preliminary Determination"),
                    ("concept_internal_review", "Internal Review"),
                    ("concept_more_info", "More information required"),
                    ("concept_rejected", "Dismissed"),
                    ("concept_review_discussion", "Ready For Discussion"),
                    ("concept_review_more_info", "More information required"),
                    ("determination", "Ready for Determination"),
                    ("draft", "Draft"),
                    ("draft_proposal", "Invited for Proposal"),
                    ("ext_accepted", "Accepted"),
                    ("ext_almost", "Accepted but additional info required"),
                    ("ext_determination", "Ready for Determination"),
                    ("ext_external_review", "External Review"),
                    ("ext_internal_review", "Internal Review"),
                    ("ext_more_info", "More information required"),
                    ("ext_post_external_review_discussion", "Ready For Discussion"),
                    ("ext_post_external_review_more_info", "More information required"),
                    ("ext_post_review_discussion", "Ready For Discussion"),
                    ("ext_post_review_more_info", "More information required"),
                    ("ext_rejected", "Dismissed"),
                    ("external_review", "External Review"),
                    ("in_discussion", "Need screening"),
                    ("internal_review", "Internal Review"),
                    ("invited_to_proposal", "Concept Accepted"),
                    ("more_info", "More information required"),
                    ("post_external_review_discussion", "Ready For Discussion"),
                    ("post_external_review_more_info", "More information required"),
                    ("post_proposal_review_discussion", "Ready For Discussion"),
                    ("post_proposal_review_more_info", "More information required"),
                    ("post_review_discussion", "Ready For Discussion"),
                    ("post_review_more_info", "More information required"),
                    ("proposal_accepted", "Accepted"),
                    ("proposal_almost", "Accepted but additional info required"),
                    ("proposal_determination", "Ready for Final Determination"),
                    ("proposal_discussion", "Proposal Received"),
                    ("proposal_internal_review", "Internal Review"),
                    ("proposal_more_info", "More information required"),
                    ("proposal_rejected", "Dismissed"),
                    ("rejected", "Dismissed"),
                    ("same_accepted", "Accepted"),
                    ("same_almost", "Accepted but additional info required"),
                    ("same_determination", "Ready for Determination"),
                    ("same_internal_review", "Review"),
                    ("same_more_info", "More information required"),
                    ("same_post_review_discussion", "Ready For Discussion"),
                    ("same_post_review_more_info", "More information required"),
                    ("same_rejected", "Dismissed"),
                ],
                default="in_discussion",
                max_length=100,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="applicationsubmission",
            name="summary",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="summary"
            ),
        ),
        migrations.AlterField(
            model_name="applicationsubmission",
            name="workflow_name",
            field=models.CharField(
                choices=[
                    ("single", "Request"),
                    ("single_same", "Request with same time review"),
                    ("single_ext", "Request with external review"),
                    ("single_com", "Request with community review"),
                    ("double", "Concept & Proposal"),
                ],
                default="single",
                max_length=100,
                verbose_name="workflow",
            ),
        ),
        migrations.AlterField(
            model_name="coapplicant",
            name="role",
            field=models.CharField(
                choices=[("view", "View"), ("comment", "Comment"), ("edit", "Edit")],
                default="view",
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="coapplicantinvite",
            name="invited_user_email",
            field=models.EmailField(max_length=254, verbose_name="invited user email"),
        ),
        migrations.AlterField(
            model_name="coapplicantinvite",
            name="role",
            field=models.CharField(
                choices=[("view", "View"), ("comment", "Comment"), ("edit", "Edit")],
                default="view",
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="coapplicantinvite",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="labbase",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="labbase",
            name="guide_link",
            field=models.URLField(
                blank=True,
                help_text="Link to the apply guide.",
                max_length=255,
                verbose_name="guide link",
            ),
        ),
        migrations.AlterField(
            model_name="labbase",
            name="list_on_front_page",
            field=models.BooleanField(
                default=True,
                help_text="Should the lab be listed on the front page.",
                verbose_name="list on front page",
            ),
        ),
        migrations.AlterField(
            model_name="labbase",
            name="workflow_name",
            field=models.CharField(
                choices=[
                    ("single", "Request"),
                    ("single_same", "Request with same time review"),
                    ("single_ext", "Request with external review"),
                    ("single_com", "Request with community review"),
                    ("double", "Concept & Proposal"),
                ],
                default="single",
                max_length=100,
                verbose_name="workflow",
            ),
        ),
        migrations.AlterField(
            model_name="roundbase",
            name="end_date",
            field=models.DateField(
                blank=True,
                default=datetime.date.today,
                help_text="When no end date is provided the round will remain open indefinitely.",
                null=True,
                verbose_name="end date",
            ),
        ),
        migrations.AlterField(
            model_name="roundbase",
            name="sealed",
            field=models.BooleanField(default=False, verbose_name="sealed"),
        ),
        migrations.AlterField(
            model_name="roundbase",
            name="start_date",
            field=models.DateField(
                blank=True,
                default=datetime.date.today,
                null=True,
                verbose_name="start date",
            ),
        ),
        migrations.AlterField(
            model_name="roundbase",
            name="workflow_name",
            field=models.CharField(
                choices=[
                    ("single", "Request"),
                    ("single_same", "Request with same time review"),
                    ("single_ext", "Request with external review"),
                    ("single_com", "Request with community review"),
                    ("double", "Concept & Proposal"),
                ],
                default="single",
                max_length=100,
                verbose_name="workflow",
            ),
        ),
        migrations.AlterField(
            model_name="screeningstatus",
            name="default",
            field=models.BooleanField(
                default=False,
                help_text="Only one Yes and No screening decision can be set as default.",
                verbose_name="default yes/no",
            ),
        ),
        migrations.AlterField(
            model_name="screeningstatus",
            name="yes",
            field=models.BooleanField(
                default=False,
                help_text="Tick mark for Yes otherwise No.",
                verbose_name="yes/no",
            ),
        ),
    ]
