# Generated by Django 5.2.12 on 2026-04-06 17:10

from django.db import migrations
from django.contrib.auth.models import Group


def assigned_review_migrate_from_partners(apps, schema_editor):
    PARTNER_GROUP_NAME = "Partner"
    REVIEWER_GROUP_NAME = "Reviewer"

    AssignedReviewers = apps.get_model("funds", "AssignedReviewers")

    reviewer_id = Group.objects.get(name=REVIEWER_GROUP_NAME).id

    if id_qs := Group.objects.filter(name=PARTNER_GROUP_NAME).values_list(
        "id", flat=True
    ):
        AssignedReviewers.objects.filter(type_id=id_qs.first()).update(
            type_id=reviewer_id
        )


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0133_remove_applicationsubmission_partners"),
    ]

    operations = [migrations.RunPython(assigned_review_migrate_from_partners)]
