# Generated by Django 5.2.13 on 2026-04-13 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0133_remove_applicationsubmission_partners"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationbase",
            options={
                "verbose_name": "application base",
                "verbose_name_plural": "application bases",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationbasedeterminationform",
            options={
                "verbose_name": "application base determination form",
                "verbose_name_plural": "application base determination forms",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationbaseexternalreviewform",
            options={
                "verbose_name": "application base external review form",
                "verbose_name_plural": "application base external review forms",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationbaseform",
            options={
                "verbose_name": "application base form",
                "verbose_name_plural": "application base forms",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationbaseprojectform",
            options={
                "verbose_name": "application base project form",
                "verbose_name_plural": "application base project forms",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationbaseprojectreportform",
            options={
                "verbose_name": "application base project report form",
                "verbose_name_plural": "application base project report forms",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationbaseprojectsowform",
            options={
                "verbose_name": "application base project SOW form",
                "verbose_name_plural": "application base project SOW forms",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationbasereviewform",
            options={
                "verbose_name": "application base review form",
                "verbose_name_plural": "application base review forms",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationform",
            options={
                "verbose_name": "application form",
                "verbose_name_plural": "applications forms",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationrevision",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "application revision",
                "verbose_name_plural": "application revisions",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationsubmission",
            options={
                "verbose_name": "application submission",
                "verbose_name_plural": "application submissions",
            },
        ),
        migrations.AlterModelOptions(
            name="assignedreviewers",
            options={
                "verbose_name": "assigned reviewer",
                "verbose_name_plural": "assigned reviewers",
            },
        ),
        migrations.AlterModelOptions(
            name="coapplicant",
            options={
                "verbose_name": "co-applicant",
                "verbose_name_plural": "co-applicants",
            },
        ),
        migrations.AlterModelOptions(
            name="coapplicantinvite",
            options={
                "verbose_name": "co-applicant invite",
                "verbose_name_plural": "co-applicant invites",
            },
        ),
        migrations.AlterModelOptions(
            name="fundtype",
            options={"verbose_name": "Fund", "verbose_name_plural": "Funds"},
        ),
        migrations.AlterModelOptions(
            name="labbase",
            options={"verbose_name": "lab base", "verbose_name_plural": "lab bases"},
        ),
        migrations.AlterModelOptions(
            name="labbasedeterminationform",
            options={
                "verbose_name": "lab base determination form",
                "verbose_name_plural": "lab base determination forms",
            },
        ),
        migrations.AlterModelOptions(
            name="labbaseexternalreviewform",
            options={
                "verbose_name": "lab base external review form",
                "verbose_name_plural": "lab base external review forms",
            },
        ),
        migrations.AlterModelOptions(
            name="labbaseform",
            options={
                "verbose_name": "lab base form",
                "verbose_name_plural": "lab base forms",
            },
        ),
        migrations.AlterModelOptions(
            name="labbaseprojectform",
            options={
                "verbose_name": "lab base project form",
                "verbose_name_plural": "lab base project forms",
            },
        ),
        migrations.AlterModelOptions(
            name="labbaseprojectreportform",
            options={
                "verbose_name": "lab base project report form",
                "verbose_name_plural": "lab base project report forms",
            },
        ),
        migrations.AlterModelOptions(
            name="labbaseprojectsowform",
            options={
                "verbose_name": "lab base project SOW form",
                "verbose_name_plural": "lab base project SOW forms",
            },
        ),
        migrations.AlterModelOptions(
            name="labbasereviewform",
            options={
                "verbose_name": "lab base review form",
                "verbose_name_plural": "lab base review forms",
            },
        ),
        migrations.AlterModelOptions(
            name="labtype",
            options={"verbose_name": "Lab", "verbose_name_plural": "Labs"},
        ),
        migrations.AlterModelOptions(
            name="reminder",
            options={
                "ordering": ["-time"],
                "verbose_name": "reminder",
                "verbose_name_plural": "reminders",
            },
        ),
        migrations.AlterModelOptions(
            name="requestforpartners",
            options={"verbose_name": "RFP", "verbose_name_plural": "RFPs"},
        ),
        migrations.AlterModelOptions(
            name="reviewerrole",
            options={
                "verbose_name": "reviewer role",
                "verbose_name_plural": "reviewer roles",
            },
        ),
        migrations.AlterModelOptions(
            name="round",
            options={"verbose_name": "Round", "verbose_name_plural": "Rounds"},
        ),
        migrations.AlterModelOptions(
            name="roundbase",
            options={
                "verbose_name": "round base",
                "verbose_name_plural": "round bases",
            },
        ),
        migrations.AlterModelOptions(
            name="roundbasedeterminationform",
            options={
                "verbose_name": "round base determination form",
                "verbose_name_plural": "round base determination forms",
            },
        ),
        migrations.AlterModelOptions(
            name="roundbaseexternalreviewform",
            options={
                "verbose_name": "round base external review form",
                "verbose_name_plural": "round base external review forms",
            },
        ),
        migrations.AlterModelOptions(
            name="roundbaseform",
            options={
                "verbose_name": "round base form",
                "verbose_name_plural": "round base forms",
            },
        ),
        migrations.AlterModelOptions(
            name="roundbasereviewform",
            options={
                "verbose_name": "round base review form",
                "verbose_name_plural": "round base review forms",
            },
        ),
        migrations.AlterModelOptions(
            name="roundsandlabs",
            options={
                "verbose_name": "round and lab",
                "verbose_name_plural": "rounds and labs",
            },
        ),
        migrations.AlterModelOptions(
            name="sealedround",
            options={
                "verbose_name": "Sealed round",
                "verbose_name_plural": "Sealed rounds",
            },
        ),
        migrations.AlterModelOptions(
            name="submissionexportmanager",
            options={
                "verbose_name": "submission export manager",
                "verbose_name_plural": "submission export managers",
            },
        ),
        migrations.AlterField(
            model_name="applicationbase",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="applicationbase",
            name="guide_link",
            field=models.URLField(
                blank=True,
                help_text="Link to the apply guide.",
                max_length=255,
                verbose_name="guide link",
            ),
        ),
        migrations.AlterField(
            model_name="applicationbase",
            name="list_on_front_page",
            field=models.BooleanField(
                default=True,
                help_text="Should the fund be listed on the front page.",
                verbose_name="list on front page",
            ),
        ),
        migrations.AlterField(
            model_name="applicationbase",
            name="show_deadline",
            field=models.BooleanField(
                default=True,
                help_text="Should the deadline date be visible for users.",
                verbose_name="show deadline",
            ),
        ),
        migrations.AlterField(
            model_name="applicationbase",
            name="workflow_name",
            field=models.CharField(
                choices=[
                    ("single", "Request"),
                    ("single_same", "Request with same time review"),
                    ("single_ext", "Request with external review"),
                    ("single_com", "Request with community review"),
                    ("double", "Concept & Proposal"),
                ],
                default="single",
                max_length=100,
                verbose_name="workflow",
            ),
        ),
        migrations.AlterField(
            model_name="applicationsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("almost", "Accepted but additional info required"),
                    ("com_accepted", "Accepted"),
                    ("com_almost", "Accepted but additional info required"),
                    ("com_community_review", "Community Review"),
                    ("com_determination", "Ready for Determination"),
                    ("com_external_review", "External Review"),
                    ("com_internal_review", "Internal Review"),
                    ("com_more_info", "More information required"),
                    ("com_open_call", "Open Call (public)"),
                    ("com_post_external_review_discussion", "Ready For Discussion"),
                    ("com_post_external_review_more_info", "More information required"),
                    ("com_post_review_discussion", "Ready For Discussion"),
                    ("com_post_review_more_info", "More information required"),
                    ("com_rejected", "Dismissed"),
                    ("concept_determination", "Ready for Preliminary Determination"),
                    ("concept_internal_review", "Internal Review"),
                    ("concept_more_info", "More information required"),
                    ("concept_rejected", "Dismissed"),
                    ("concept_review_discussion", "Ready For Discussion"),
                    ("concept_review_more_info", "More information required"),
                    ("determination", "Ready for Determination"),
                    ("draft", "Draft"),
                    ("draft_proposal", "Invited for Proposal"),
                    ("ext_accepted", "Accepted"),
                    ("ext_almost", "Accepted but additional info required"),
                    ("ext_determination", "Ready for Determination"),
                    ("ext_external_review", "External Review"),
                    ("ext_internal_review", "Internal Review"),
                    ("ext_more_info", "More information required"),
                    ("ext_post_external_review_discussion", "Ready For Discussion"),
                    ("ext_post_external_review_more_info", "More information required"),
                    ("ext_post_review_discussion", "Ready For Discussion"),
                    ("ext_post_review_more_info", "More information required"),
                    ("ext_rejected", "Dismissed"),
                    ("external_review", "External Review"),
                    ("in_discussion", "Need screening"),
                    ("internal_review", "Internal Review"),
                    ("invited_to_proposal", "Concept Accepted"),
                    ("more_info", "More information required"),
                    ("post_external_review_discussion", "Ready For Discussion"),
                    ("post_external_review_more_info", "More information required"),
                    ("post_proposal_review_discussion", "Ready For Discussion"),
                    ("post_proposal_review_more_info", "More information required"),
                    ("post_review_discussion", "Ready For Discussion"),
                    ("post_review_more_info", "More information required"),
                    ("proposal_accepted", "Accepted"),
                    ("proposal_almost", "Accepted but additional info required"),
                    ("proposal_determination", "Ready for Final Determination"),
                    ("proposal_discussion", "Proposal Received"),
                    ("proposal_internal_review", "Internal Review"),
                    ("proposal_more_info", "More information required"),
                    ("proposal_rejected", "Dismissed"),
                    ("rejected", "Dismissed"),
                    ("same_accepted", "Accepted"),
                    ("same_almost", "Accepted but additional info required"),
                    ("same_determination", "Ready for Determination"),
                    ("same_internal_review", "Review"),
                    ("same_more_info", "More information required"),
                    ("same_post_review_discussion", "Ready For Discussion"),
                    ("same_post_review_more_info", "More information required"),
                    ("same_rejected", "Dismissed"),
                ],
                default="in_discussion",
                max_length=100,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="applicationsubmission",
            name="summary",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="summary"
            ),
        ),
        migrations.AlterField(
            model_name="applicationsubmission",
            name="workflow_name",
            field=models.CharField(
                choices=[
                    ("single", "Request"),
                    ("single_same", "Request with same time review"),
                    ("single_ext", "Request with external review"),
                    ("single_com", "Request with community review"),
                    ("double", "Concept & Proposal"),
                ],
                default="single",
                max_length=100,
                verbose_name="workflow",
            ),
        ),
        migrations.AlterField(
            model_name="coapplicant",
            name="role",
            field=models.CharField(
                choices=[("view", "View"), ("comment", "Comment"), ("edit", "Edit")],
                default="view",
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="coapplicantinvite",
            name="invited_user_email",
            field=models.EmailField(max_length=254, verbose_name="invited user email"),
        ),
        migrations.AlterField(
            model_name="coapplicantinvite",
            name="role",
            field=models.CharField(
                choices=[("view", "View"), ("comment", "Comment"), ("edit", "Edit")],
                default="view",
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="coapplicantinvite",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="labbase",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="labbase",
            name="guide_link",
            field=models.URLField(
                blank=True,
                help_text="Link to the apply guide.",
                max_length=255,
                verbose_name="guide link",
            ),
        ),
        migrations.AlterField(
            model_name="labbase",
            name="list_on_front_page",
            field=models.BooleanField(
                default=True,
                help_text="Should the lab be listed on the front page.",
                verbose_name="list on front page",
            ),
        ),
        migrations.AlterField(
            model_name="labbase",
            name="workflow_name",
            field=models.CharField(
                choices=[
                    ("single", "Request"),
                    ("single_same", "Request with same time review"),
                    ("single_ext", "Request with external review"),
                    ("single_com", "Request with community review"),
                    ("double", "Concept & Proposal"),
                ],
                default="single",
                max_length=100,
                verbose_name="workflow",
            ),
        ),
        migrations.AlterField(
            model_name="roundbase",
            name="end_date",
            field=models.DateField(
                blank=True,
                default=datetime.date.today,
                help_text="When no end date is provided the round will remain open indefinitely.",
                null=True,
                verbose_name="end date",
            ),
        ),
        migrations.AlterField(
            model_name="roundbase",
            name="sealed",
            field=models.BooleanField(default=False, verbose_name="sealed"),
        ),
        migrations.AlterField(
            model_name="roundbase",
            name="start_date",
            field=models.DateField(
                blank=True,
                default=datetime.date.today,
                null=True,
                verbose_name="start date",
            ),
        ),
        migrations.AlterField(
            model_name="roundbase",
            name="workflow_name",
            field=models.CharField(
                choices=[
                    ("single", "Request"),
                    ("single_same", "Request with same time review"),
                    ("single_ext", "Request with external review"),
                    ("single_com", "Request with community review"),
                    ("double", "Concept & Proposal"),
                ],
                default="single",
                max_length=100,
                verbose_name="workflow",
            ),
        ),
        migrations.AlterField(
            model_name="screeningstatus",
            name="default",
            field=models.BooleanField(
                default=False,
                help_text="Only one Yes and No screening decision can be set as default.",
                verbose_name="default yes/no",
            ),
        ),
        migrations.AlterField(
            model_name="screeningstatus",
            name="yes",
            field=models.BooleanField(
                default=False,
                help_text="Tick mark for Yes otherwise No.",
                verbose_name="yes/no",
            ),
        ),
    ]
