# Generated by Django 5.2.17 on 2026-09-10 14:01

import hypha.apply.categories.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0137_alter_anonymizedsubmission_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationform",
            name="form_fields",
            field=wagtail.fields.StreamField(
                [
                    ("text_markup", 0),
                    ("header_markup", 3),
                    ("char", 10),
                    ("multi_inputs_char", 13),
                    ("text", 16),
                    ("number", 17),
                    ("checkbox", 19),
                    ("radios", 22),
                    ("dropdown", 22),
                    ("checkboxes", 25),
                    ("date", 27),
                    ("time", 29),
                    ("datetime", 31),
                    ("image", 32),
                    ("file", 32),
                    ("multi_file", 32),
                    ("group_toggle", 35),
                    ("group_toggle_end", 36),
                    ("rich_text", 16),
                    ("markdown_text", 16),
                    ("category", 41),
                    ("title", 46),
                    ("email", 49),
                    ("full_name", 52),
                    ("value", 53),
                    ("organization_name", 53),
                    ("address", 53),
                    ("duration", 55),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"group": "Custom", "label": "Paragraph"},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("h2", "H2"), ("h3", "H3"), ("h4", "H4")]},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 1), ("size", 2)]],
                        {"group": "Custom", "label": "Section header"},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Label"}),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Help text", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Required", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("email", "Email"), ("url", "URL")],
                            "label": "Format",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Default value", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Tick this if the answer will contain personally identifiable information, such as a name, address, phone number or date of birth. Only the applicant, their co-applicants and staff will be able to see the answer. Reviewers and other users will see that the question was asked, but not the answer.",
                            "label": "Personal information",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("format", 7),
                                ("default_value", 8),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    11: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 2, "label": "Max number of inputs"},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Add new item", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("format", 7),
                                ("default_value", 8),
                                ("number_of_inputs", 11),
                                ("add_button_text", 12),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    14: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Default value", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 1000, "label": "Word limit"},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("default_value", 14),
                                ("word_limit", 15),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("default_value", 8),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    18: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("default_value", 18),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    20: ("wagtail.blocks.CharBlock", (), {"label": "Choice"}),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("choices", 21),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    23: ("wagtail.blocks.CharBlock", (), {"label": "Checkbox"}),
                    24: ("wagtail.blocks.ListBlock", (23,), {}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("checkboxes", 24),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    26: ("wagtail.blocks.DateBlock", (), {"required": False}),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("default_value", 26),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    28: ("wagtail.blocks.TimeBlock", (), {"required": False}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("default_value", 28),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    30: ("wagtail.blocks.DateTimeBlock", (), {"required": False}),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("default_value", 30),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    33: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "label": "Required", "required": False},
                    ),
                    34: (
                        "wagtail.blocks.ListBlock",
                        (20,),
                        {
                            "help_text": "Please create only two choices for toggle. First choice will revel the group and the second hide it. Additional choices will be ignored."
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 33),
                                ("choices", 34),
                            ]
                        ],
                        {"group": "Custom"},
                    ),
                    36: (
                        "hypha.apply.stream_forms.blocks.GroupToggleEndBlock",
                        (),
                        {"group": "Custom"},
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the default Category label",
                            "label": "Label",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the default Category help text",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": hypha.apply.categories.blocks.get_categories_as_choices
                        },
                    ),
                    40: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Multi select", "required": False},
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 37),
                                ("help_text", 38),
                                ("required", 6),
                                ("category", 39),
                                ("multi", 40),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Custom"},
                    ),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "What is the title of your application?",
                            "label": "Label",
                        },
                    ),
                    43: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "This project name can be changed if a full proposal is requested.",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"label": "Max length", "required": False},
                    ),
                    45: ("wagtail.blocks.static_block.StaticBlock", (), {}),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 42),
                                ("help_text", 43),
                                ("max_length", 44),
                                ("info", 45),
                            ]
                        ],
                        {"group": " Required"},
                    ),
                    47: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "What email address should we use to contact you?",
                            "label": "Label",
                        },
                    ),
                    48: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "We will use this email address to communicate with you about your proposal.",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 47), ("help_text", 48), ("info", 45)]],
                        {"group": " Required"},
                    ),
                    50: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "What is your name?", "label": "Label"},
                    ),
                    51: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "We will use this name when we communicate with you about your proposal.",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 50), ("help_text", 51), ("info", 45)]],
                        {"group": " Required"},
                    ),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("info", 45),
                            ]
                        ],
                        {"group": "Custom"},
                    ),
                    54: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("days", "Days"),
                                ("weeks", "Weeks"),
                                ("months", "Months"),
                            ],
                            "help_text": "Duration type is used to display duration choices in Days, Weeks or Months in application forms. Be careful, changing the duration type in the active round can result in data inconsistency.",
                        },
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("duration_type", 54),
                                ("info", 45),
                            ]
                        ],
                        {"group": "Custom"},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="applicationsubmission",
            name="form_fields",
            field=wagtail.fields.StreamField(
                [
                    ("text_markup", 0),
                    ("header_markup", 3),
                    ("char", 10),
                    ("multi_inputs_char", 13),
                    ("text", 16),
                    ("number", 17),
                    ("checkbox", 19),
                    ("radios", 22),
                    ("dropdown", 22),
                    ("checkboxes", 25),
                    ("date", 27),
                    ("time", 29),
                    ("datetime", 31),
                    ("image", 32),
                    ("file", 32),
                    ("multi_file", 32),
                    ("group_toggle", 35),
                    ("group_toggle_end", 36),
                    ("rich_text", 16),
                    ("markdown_text", 16),
                    ("category", 41),
                    ("title", 46),
                    ("email", 49),
                    ("full_name", 52),
                    ("value", 53),
                    ("organization_name", 53),
                    ("address", 53),
                    ("duration", 55),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"group": "Custom", "label": "Paragraph"},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("h2", "H2"), ("h3", "H3"), ("h4", "H4")]},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 1), ("size", 2)]],
                        {"group": "Custom", "label": "Section header"},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Label"}),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Help text", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Required", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("email", "Email"), ("url", "URL")],
                            "label": "Format",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Default value", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Tick this if the answer will contain personally identifiable information, such as a name, address, phone number or date of birth. Only the applicant, their co-applicants and staff will be able to see the answer. Reviewers and other users will see that the question was asked, but not the answer.",
                            "label": "Personal information",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("format", 7),
                                ("default_value", 8),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    11: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 2, "label": "Max number of inputs"},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Add new item", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("format", 7),
                                ("default_value", 8),
                                ("number_of_inputs", 11),
                                ("add_button_text", 12),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    14: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Default value", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 1000, "label": "Word limit"},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("default_value", 14),
                                ("word_limit", 15),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("default_value", 8),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    18: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("default_value", 18),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    20: ("wagtail.blocks.CharBlock", (), {"label": "Choice"}),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("choices", 21),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    23: ("wagtail.blocks.CharBlock", (), {"label": "Checkbox"}),
                    24: ("wagtail.blocks.ListBlock", (23,), {}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("checkboxes", 24),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    26: ("wagtail.blocks.DateBlock", (), {"required": False}),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("default_value", 26),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    28: ("wagtail.blocks.TimeBlock", (), {"required": False}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("default_value", 28),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    30: ("wagtail.blocks.DateTimeBlock", (), {"required": False}),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("default_value", 30),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Fields"},
                    ),
                    33: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "label": "Required", "required": False},
                    ),
                    34: (
                        "wagtail.blocks.ListBlock",
                        (20,),
                        {
                            "help_text": "Please create only two choices for toggle. First choice will revel the group and the second hide it. Additional choices will be ignored."
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 33),
                                ("choices", 34),
                            ]
                        ],
                        {"group": "Custom"},
                    ),
                    36: (
                        "hypha.apply.stream_forms.blocks.GroupToggleEndBlock",
                        (),
                        {"group": "Custom"},
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the default Category label",
                            "label": "Label",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the default Category help text",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": hypha.apply.categories.blocks.get_categories_as_choices
                        },
                    ),
                    40: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Multi select", "required": False},
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 37),
                                ("help_text", 38),
                                ("required", 6),
                                ("category", 39),
                                ("multi", 40),
                                ("is_pii", 9),
                            ]
                        ],
                        {"group": "Custom"},
                    ),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "What is the title of your application?",
                            "label": "Label",
                        },
                    ),
                    43: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "This project name can be changed if a full proposal is requested.",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"label": "Max length", "required": False},
                    ),
                    45: ("wagtail.blocks.static_block.StaticBlock", (), {}),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 42),
                                ("help_text", 43),
                                ("max_length", 44),
                                ("info", 45),
                            ]
                        ],
                        {"group": " Required"},
                    ),
                    47: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "What email address should we use to contact you?",
                            "label": "Label",
                        },
                    ),
                    48: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "We will use this email address to communicate with you about your proposal.",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 47), ("help_text", 48), ("info", 45)]],
                        {"group": " Required"},
                    ),
                    50: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "What is your name?", "label": "Label"},
                    ),
                    51: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "We will use this name when we communicate with you about your proposal.",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 50), ("help_text", 51), ("info", 45)]],
                        {"group": " Required"},
                    ),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("info", 45),
                            ]
                        ],
                        {"group": "Custom"},
                    ),
                    54: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("days", "Days"),
                                ("weeks", "Weeks"),
                                ("months", "Months"),
                            ],
                            "help_text": "Duration type is used to display duration choices in Days, Weeks or Months in application forms. Be careful, changing the duration type in the active round can result in data inconsistency.",
                        },
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 4),
                                ("help_text", 5),
                                ("required", 6),
                                ("duration_type", 54),
                                ("info", 45),
                            ]
                        ],
                        {"group": "Custom"},
                    ),
                },
            ),
        ),
    ]
