# Generated by Django 5.2.17 on 2026-09-22 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0138_add_is_pii_to_application_form_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationbasedeterminationform",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "application base determination form",
                "verbose_name_plural": "application base determination forms",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationbaseexternalreviewform",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "application base external review form",
                "verbose_name_plural": "application base external review forms",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationbaseform",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "application base form",
                "verbose_name_plural": "application base forms",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationbaseprojectform",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "application base project form",
                "verbose_name_plural": "application base project forms",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationbaseprojectreportform",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "application base project report form",
                "verbose_name_plural": "application base project report forms",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationbaseprojectsowform",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "application base project SOW form",
                "verbose_name_plural": "application base project SOW forms",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationbasereviewform",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "application base review form",
                "verbose_name_plural": "application base review forms",
            },
        ),
        migrations.AlterModelOptions(
            name="labbasedeterminationform",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "lab base determination form",
                "verbose_name_plural": "lab base determination forms",
            },
        ),
        migrations.AlterModelOptions(
            name="labbaseexternalreviewform",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "lab base external review form",
                "verbose_name_plural": "lab base external review forms",
            },
        ),
        migrations.AlterModelOptions(
            name="labbaseform",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "lab base form",
                "verbose_name_plural": "lab base forms",
            },
        ),
        migrations.AlterModelOptions(
            name="labbaseprojectform",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "lab base project form",
                "verbose_name_plural": "lab base project forms",
            },
        ),
        migrations.AlterModelOptions(
            name="labbaseprojectreportform",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "lab base project report form",
                "verbose_name_plural": "lab base project report forms",
            },
        ),
        migrations.AlterModelOptions(
            name="labbaseprojectsowform",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "lab base project SOW form",
                "verbose_name_plural": "lab base project SOW forms",
            },
        ),
        migrations.AlterModelOptions(
            name="labbasereviewform",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "lab base review form",
                "verbose_name_plural": "lab base review forms",
            },
        ),
        migrations.AlterModelOptions(
            name="roundbasedeterminationform",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "round base determination form",
                "verbose_name_plural": "round base determination forms",
            },
        ),
        migrations.AlterModelOptions(
            name="roundbaseexternalreviewform",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "round base external review form",
                "verbose_name_plural": "round base external review forms",
            },
        ),
        migrations.AlterModelOptions(
            name="roundbaseform",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "round base form",
                "verbose_name_plural": "round base forms",
            },
        ),
        migrations.AlterModelOptions(
            name="roundbasereviewform",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "round base review form",
                "verbose_name_plural": "round base review forms",
            },
        ),
    ]
